### ISSUE TITLE
Filter "Lieu-dit"" in french

### ISSUE THREAD

**Issue by frodrigo** [addok/addok#100]
Filter "lieu dit" in french search.
/!\ maybe some addresses contains legitimate "lieu dit" ?

**Comment by cquest** [comment]
only 2 streets containing "lieu-dit" in their name...
- rue de la rente du lieu-dit la gimbaudière
- rue de la rente du lieu-dit la gachère

Both are still found when "lieu-dit" is remove, so it seems safe to remove "lieu-dit" or "lieu dit" in the input

**Comment by yohanboniface** [comment]
Why have you closed it? :)

**Comment by cquest** [comment]
Issue reçue par mail... que je retransmet

> Notamment  pour les adresses qui contiennent le terme « lieu dit » et qui ne sont pas du tout reconnues
>
> Exemple
>
> LIEU DIT SERRES 31450 FOURQUEVAUX n’est pas du tout reconnu
>
> En enlevant terme :  SERRES 31450 FOURQUEVAUX est reconnu
