### ISSUE TITLE
Proposer des coordonnées en X/Y légal en plus du WGS84

### ISSUE THREAD

**Issue by cquest** [addok/addok#112]
Les administrations ont souvent besoin de travailler en projection légale (Lambert93 en métropole et autre dans les DOM).

On peut soit ajouter des champs X et Y dans les données json, ou bien faire la reprojection avant de fournir la réponse...

**Comment by davidbgk** [comment]
Devrait être fait dans un plugin.

**Comment by cquest** [comment]
Autre solution: pré-calculé et conservé dans le document... mais à faire une fois qu'on a mis en place le stockage des documents hors redis.

**Comment by davidbgk** [comment]
Ce qui a été mergé ce jour https://github.com/addok/addok/pull/222 ;)

**Comment by cquest** [comment]
👍

**Comment by cquest** [comment]
Bientôt disponible... https://github.com/etalab/ban-data/commit/ac815998a5c2003cfd500061c8c0354921785596

**Comment by cquest** [comment]
Je ferme car l'ajout des X/Y en plus du lat/lon se fait directement dans les fichiers json (pour la BAN).
