### ISSUE TITLE
extract_address is called before synonym matching

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#12]
So an adresse like "PARC D ACTIVITE DE SAUMATY 26 AV ANDRE ROUSSIN 13016 MARSEILLE 16" will no be extracted (av => avenue).

**Comment by davidbgk** [comment]
Current status:

```
> TOKENIZE PARC D ACTIVITE DE SAUMATY 26 AV ANDRE ROUSSIN 13016 MARSEILLE 16
park d aktivit de saumati 26 avenu andr rousin 13016 marseil seiz
```

`park d aktivit de saumati` should not be present.

**Comment by yohanboniface** [comment]
Should be fixed by https://github.com/addok/addok-france/commit/1d2174b1234aef64bd44d5a799b247593bbc350b#diff-fae749b0bacb725bc49873af6b0e6cf2R6
