### ISSUE TITLE
SEN, Sente & Sentier

### ISSUE THREAD

**Issue by parville** [addok/addok#129]
Bonjour,

serait-il possible qu'ADDOK considére que SEN veut dire Sente ou Sentier .
Que par conséquent chercher 

http://api.adresse.data.gouv.fr/search/?q=sente%20DES%20GRECS&citycode=76599
retourne
- sente des grecs

http://api.adresse.data.gouv.fr/search/?q=sen%20DES%20GRECS&citycode=76599
retourne
- sente des grecs
- sentier des grecs

et que
http://api.adresse.data.gouv.fr/search/?q=sentier%20DES%20GRECS&citycode=76599
retourne toujours
- sentier des grecs

Actuellement les deux premières interrogations ne retourne rien et c'est fort dommageable car la voie s'appelle bien SENTE et non SENTIER DES GRECS.

Merci

**Comment by parville** [comment]
Petite relance car c'est toujours d'actualité vue les erreurs dans les données BAN !

**Comment by cquest** [comment]
Pour les trois cas, je n'ai que "Sentier des Grecs" retourné avec les données actuelles ?
Est-ce bien le résultat cohérent ?

**Comment by parville** [comment]
Hélas, (joke) le bon résultat terrain est "sente des grecs" !

**Comment by cquest** [comment]
C'est une erreur dans les données livrées par l'IGN, le libellé est bien 'Sente des Grecs' pour La Poste. A remonter à leur niveau.

Je ferme le ticket pour addok.
