### ISSUE TITLE
definir une zone pour le geocodeur csv

### ISSUE THREAD

**Issue by AlexisEidelman** [addok/addok#132]
Parfois on a des données d'une seule zone (par exemple Paris) et pas de colonne dans le csv, on peut l'ajouter bien sûr mais peut-être qu'on peut demander si on sait que les données concernent une zone définie.

**Comment by yohanboniface** [comment]
Ça dépend ce que tu appelles une "zone" :)

Il n'y a pas de notion de polygon dans addok (ni dans Redis, qui est le moteur d'addok), et les maigres notions de géographie (basées sur du geohash) ne permettent pas de cibler des géométries complexes, et ne sont aujourd'hui utilisées que pour prioriser les résultats.

En conséquence, les seuls filtres possibles sont des filtres sémantiques, mais ça peut néanmoins être un code insee par exemple, qui correspond au final à une zone géographique. Autre limite: une seule valeur par filtre est supportée à l'heure actuelle.

Ensuite, si ta demande c'est "ajouter un paramètre à l'appel CSV pour dire que tous les résultats doivent être filtrés via le code insee xxx", alors oui le plus simple est d'ajouter la colonne :)

On peut réfléchir à prendre en charge des paramètres supplémentaires pour filtrer la recherche selon une valeur, comme pour une recherche normale, mais j'ai peur qu'on aboutisse à une API compliquée (actuellement, passer "insee=xxx" en paramètre signifie qu'on veut utiliser la colonne xxx pour filtrer les résultats. Là il faudrait pouvoir distinguer "insee=unecolonne" et "insee=unevaleur". On a un risque de faire un pas trop loin à mon sens.)

**Comment by AlexisEidelman** [comment]
Ce que je voulais dire c'est plutôt la fin de ton mail. Tu as bien compris et tu as bien répondu.
Ajouter une colonne n'est pas compliqué, il faut peut-être juste indiquer quelque part à l'utilisateur qu'il a intérêt à le faire.
