### ISSUE TITLE
plus de /search/csv ou /reverse/csv

### ISSUE THREAD

**Issue by ssoulier** [addok/addok#144]
Je ne trouve plus aucune référence aux requêtes de type batch dans le code (anciennement dans server.py). Est-ce toujours possible et si oui, comment et où l'url est-elle parser ?
Merci d'avance pour l'aide.

**Comment by yohanboniface** [comment]
@ssoulier attention, le master est en cours de full refactor, et la doc n'est pas mise à jour, donc à utiliser à tes risques et périls. ;)

Pour le CSV, ça se passe désormais via un plugin: https://github.com/addok/addok-csv

Je ferme ici par qu'aucune action n'est attendue, mais n'hésite pas si tu as des questions (et je redis que si c'est pour de la prod faut rester sur une install stable via pip :) ).

**Comment by ssoulier** [comment]
Merci @yohanboniface pour ta réponse.
