### ISSUE TITLE
Ajout d'un nouveau champ

### ISSUE THREAD

**Issue by ThibautGery** [addok/addok#146]
Je souhaitais savoir s'il était possible d'ajouter le champ  RIVOLI (ccoriv)
qui est un champ sur 4 caractères en alphanumérique utilisé par (au moins) [les impots](http://www.impots.gouv.fr/portal/deploiement/p1/fichedescriptive_6407/fichedescriptive_6407.pdf)

**Comment by yohanboniface** [comment]
Je l'ai pas stricto sensu dans les données en l'état, mais il est dans l'id des voies. Je vais voir pour faire un petit plugin pour l'exposer dès que j'ai mis en prod la prochaine version.
Pour info, le RIVOLI s'appelle FANOIR maintenant afaik.

**Comment by ThibautGery** [comment]
Merci @yohanboniface, je passe lien de l'issue à la personne intéressée

**Comment by REIMSMetropole** [comment]
Fantoir, avec un T.
Et effectivement, cela serait un plus.

**Comment by cquest** [comment]
On n'a malheureusement pas toujours ce code dans les données BAN.
A minima, une amélioration consisterai à retourner l'id du document (voie ou lieu-dit) lorsque l'on retourne un housenumber.
Le RIVOLI/FANTOIR se trouvera potentiellement dedans et on peut aussi l'extraire.

**Comment by yohanboniface** [comment]
Pourra se faire via un plugin avec la 1.0 (imminente).
