### ISSUE TITLE
le géocodage inversé ne fonctionne pas sur la carte interactive

### ISSUE THREAD

**Issue by FERRATON** [addok/addok#148]
Si on se déplace sur la carte interactive, on n'accède pas à la fonction inverse de géocodage : sur la page des outils de carte interactive, il est indiqué de cliquer pour faire un géocodage inverse, mais aucun traitement ne se lance.

**Comment by yohanboniface** [comment]
En effet, c'est une erreur: il ne faut pas cliquer, il suffit de déplacer la carte, à condition d'être à un zoom supérieur ou égal à 15. Je vais mettre à jour le texte.
