### ISSUE TITLE
erreur de géocodage

### ISSUE THREAD

**Issue by FERRATON** [addok/addok#149]
Lorsque que le géocodeur ne trouve pas la rue dans une ville, il géocode l'adresse dans une autre ville. Exemple "11 rue de la chapelle MME à HEM (nord)" géocodé "11 rue MME fernand Halphen dans l'Oise)"
Au lieu de trouver la rue Madame. 

N'interpréte pas les abréviations.
devrait prioriser la ville (même en l'absence de code INSEE).

**Comment by yohanboniface** [comment]
> devrait prioriser la ville (même en l'absence de code INSEE).

Malheureusement, le géocodeur ne sait pas ce qu'est une ville: "Paris, avenue de Saint-Mandé", où est la ville?
Et c'est justement le principe d'un géocodeur: passer d'une chaîne non formatée à une chaîne formatée. Si on savait où est la ville dans la chaîne, on aurait pas besoin de gécodeur, en d'autres termes. ;)

> N'interpréte pas les abréviations.

C'est aller un peu vite à la conclusion: https://github.com/addok/addok/blob/master/addok/resources/synonyms/fr.txt
Mais il manque en effet l'abréviation "mme", que je vais ajouter de ce pas. :)

**Comment by FERRATON** [comment]
Concernant la prise en compte de la ville... Elle peut dans certains cas être dans une colonne à part. Ne peut-on envisager de la prendre en compte dans ce cas (comme le champ INSEE) ?

exemple ci-joint
[adresses_bibliotheques_2014.zip](https://github.com/addok/addok/files/187898/adresses_bibliotheques_2014.zip)

**Comment by yohanboniface** [comment]
Ça dépend de la façon dont l'index est construit, et quel sont les filtres possibles. En l'occurrence sur l'instance adresse.data.gouv.fr les villes ne sont pas dans la liste des index pour filtres. Mais c'est théoriquement possible.
Après, les filtres ne sont, grosso modo, adaptés qu'à des données non ambiguës, parce qu'il ne sont pas processés comme des chaînes de caractères. Donc, si on indexait la ville de 'Vernou-la-Celle-sur-Seine', il faudrait utiliser cette exacte chaîne pour activer le filtre, une erreur de casse, d'accent, de tiret ou apostrophe suffirait pour ne pas matcher.
