### ISSUE TITLE
street au lieu de locality

### ISSUE THREAD

**Issue by FERRATON** [addok/addok#150]
dans le fichier joint
[Echantillon_AER.zip](https://github.com/addok/addok/files/178035/Echantillon_AER.zip)

Quelques points sont placés de manière aléatoire en état street et devraient être en locality (?). Ils sont au centre du village bati.

Le fichier était les aéroports et aérodromes d'ile-de-france.

**Comment by yohanboniface** [comment]
L'instance d'addok sur adresse.data.gouv.fr ne contient pas les points d'intérêt, et va donc chercher à géocoder sur les éléments signifiants sans grande chance de trouver le "bon" résultat vu qu'il n'est pas dans les données indexées.
