### ISSUE TITLE
incomplétude des zones artisanales

### ISSUE THREAD

**Issue by FERRATON** [addok/addok#151]
ne géolocalise pas correctement les zones artisanales.
Exemple : zone artisanale de la martinière, rue du Mans, 72300 sable.
Pourtant, cela apparait bien en fond de plan.

**Comment by yohanboniface** [comment]
Les données se trouvent-elles dans les exports de la BAN? http://bano.openstreetmap.fr/BAN_odbl/

**Comment by cquest** [comment]
La ZA n'est pas présente, mais la rue du Mans oui:

> rue du Mans, 72300 sable
Rue du Mans 72300 Sablé-sur-Sarthe (72264_1010_b006fe | 0.8355545454545453)

> martinière 72300 sable
Rue de la Martinière 72300 Sablé-sur-Sarthe (72264_1041_b78b41 | 0.6498181818181817)
Rue Pierre et Marie Curie, LA MARTINIERE 72300 Sablé-sur-Sarthe (72264_B519_dc4fd5 | 0.6459090909090908)
La Martiniere 72300 Sablé-sur-Sarthe (72264_B519_5b0a5a | 0.6448999999999999)
Route de Sable, LA PETITE MARTINIERE 72300 Solesmes (72336_0640B361_062f5f | 0.4439953436807095)

**Comment by yohanboniface** [comment]
Problème de données.
