### ISSUE TITLE
mauvais ratio de géocodage sur les lieux-dits

### ISSUE THREAD

**Issue by FERRATON** [addok/addok#152]
La précison de géocodage des lieux-dits habités en Sarthe est très moyenne.
Pour les lieux-dits habités issus de la BD_TOPO, seuls 13 138 lieux-dits habités sont géocodés sur 22 085.

Pour reproduire : Créer une table des lieux-dits habités de la BD_TOPO et y inclure le code INSEE.
Géocoder le fichier (il faut le tronquer en 2 partie car la limite se situe entre 15 000 et 20 000 enregistrements)

**Comment by FERRATON** [comment]
En complément, Lorsque l'adresse est "Le bourg", le point est souvent mal positionné et loin du centre bourg de la commune. Par exemple sur Le Vigean dans le Cantal, la carte interactive positionne bien mais pas l'outil .CSV

**Comment by yohanboniface** [comment]
>  Pour les lieux-dits habités issus de la BD_TOPO, seuls 13 138 lieux-dits habités sont géocodés sur 22 085.

Est-ce que les lieux-dits qui ne sont pas trouvés existent dans les exports de la BAN actuelle? cf http://bano.openstreetmap.fr/BAN_odbl/

**Comment by FERRATON** [comment]
Ci-joint une table des lieux-dits issue des la Bdtopo. Il semble que l'on ne retrouve pas ces lieux-dits.
[lieux_dits_habites_sarthe_bd_topo151.zip](https://github.com/addok/addok/files/192986/lieux_dits_habites_sarthe_bd_topo151.zip)

Est-ce que les lieux-dits de la Bdtopo sont inclus (en théorie) dans la BAN ?

**Comment by yohanboniface** [comment]
> Est-ce que les lieux-dits de la Bdtopo sont inclus (en théorie) dans la BAN ?

Je dirais que non, sinon on les aurait dans le géocodeur, mais il peut y avoir un loup néanmoins.
Du coup, c'est une question pour @cquest

**Comment by cquest** [comment]
Les lieux dits sans adresse numérotée ne sont pas présents dans la BAN, le géocodeur ne peut donc pas les trouver.

**Comment by FERRATON** [comment]
Est-il envisageable de les rajouter ou est-ce une limite intrinsèque au moteur ?

**Comment by cquest** [comment]
Le moteur n'est pas limité, c'est une limite des données BAN diffusées actuellement.
La BD Topo n'est pas en opendata, nous ne pouvons l'utiliser pour compéter les données BAN à l'heure actuelle.

**Comment by yohanboniface** [comment]
Je ferme ici, c'est une affaire de données, pas d'algo.
