### ISSUE TITLE
pertinence du result_score ?

### ISSUE THREAD

**Issue by FERRATON** [addok/addok#153]
Le score de précision sur les lieux-dits habités BD_TOPO de la Sarthe varie de 0,81 à 0,15 alors que certains lieux dits sont géolocalisés précisément par rapport à la BD_TOPO.
Il n'y a pas de vraie logique apparente sur la détermination de la valeur de géocodage :
il semblerait qu'à partir de 0,61 on commence à bien géolocaliser les lieux-dits.
Mais on peut avoir 0,61 avec un lieux dit trouvé (moins de 10 mètres d'écart).

**Comment by yohanboniface** [comment]
Le géocodeur ne sait pas ce qui est cherché, et ne peut donc pas déterminer de score par rapport à un résultat absolu.
Pour déterminer le score (qui sert seulement à ordonner les résultats, et n'est retourné que pour information), il compare grosso modo la chaîne en entrée avec les résultats possibles. Donc les score peuvent varier selon la qualité des données en entrée et leur conformité aux règles habituelles de nommage des adresses (numéro + rue +  code postal + ville, en très simplifié).
Bref, c'est une indication, qu'il faut ensuite ou bien ignorer ou bien interpréter selon le jeu de données utilisé.
