### ISSUE TITLE
carte interactive ne fonctionne pas sous IE9

### ISSUE THREAD

**Issue by FERRATON** [addok/addok#154]
La carte interactive ne fonctionne pas sous Internet Explorer 9.0.8
Cliquez sur l'outil carte interactive, sous Windows, dans IE9.
Aucun fond de plan ne s'affiche, pas de possibilité de saisie d'adresse.

**Comment by yohanboniface** [comment]
Utilisez un navigateur libre, comme Firefox ;)
(Et ce n'est jamais qu'une carte de démo.)
