### ISSUE TITLE
nombre limite d'adresses à géocoder ?

### ISSUE THREAD

**Issue by FERRATON** [addok/addok#155]
[Lille2a(2).zip](https://github.com/addok/addok/files/178063/Lille2a.2.zip)

Message d'erreur "Oops, quelque chose tourne pas rond ..." lorsque j'essaie de géocoder un fichier contenant 22000 adresses.
En réduisant le nombre d'adresses à 500, le géocodage fonctionne. 

- import du fichier csv
- choix des colonnes : adresse annuelle ligne 1, adresse annuelle ville
- paramètres avancés / colonne contenant le code postal: adresse fixe -commune code

**Comment by yohanboniface** [comment]
Environ 6Mo ou 15000 lignes.
