### ISSUE TITLE
souhait de pouvoir avoir accès aux coordonnées du point géolocalisé dans la carte interactive

### ISSUE THREAD

**Issue by FERRATON** [addok/addok#156]
Saisir une adresse, la carte se positionne sur le point dans la rue, mais nous n'avons pas accès aux coordonnées X,Y du point.

**Comment by yohanboniface** [comment]
Pour adresse.data.gouv.fr, ça se passe par là: https://github.com/etalab/adresse.data.gouv.fr/issues :)
