### ISSUE TITLE
souhait de visualiser les numéros de rue dans la carte interactive

### ISSUE THREAD

**Issue by FERRATON** [addok/addok#157]
Evolution :permettre de visualiser les numéros dans la rue, à l'image de ce que fait http://openstreetmap.fr/ban  dans son outil de visualisation BANO http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/47.95571/0.09416
Facilite la recherche d'un numéro dans une rue.

**Comment by yohanboniface** [comment]
=> https://github.com/etalab/adresse.data.gouv.fr/issues ;)
