### ISSUE TITLE
souhait de pouvoir préciser un SRS pour le géocodage inversé

### ISSUE THREAD

**Issue by FERRATON** [addok/addok#160]
Il serait souhaitable de pouvoir préciser un SRS (Lambert93 (unités : mètres)) pour réaliser un géocodage inversé. Seul le wgs84 (long/lat) est possible.

**Comment by cquest** [comment]
Cela amènera un nouveau problème avec les adresses dans les DOM... il faudrait connaitre la zone du résultat pour passer un SRS qui y sera cohérent.
Ceci tient plus du traitement à faire côté client.

**Comment by frodrigo** [comment]
cf #112

**Comment by yohanboniface** [comment]
N'a pas sa place dans le cœur, peut se faire via un plugin pour des besoins maison.
