### ISSUE TITLE
Barre de recherche d'adresse Leaflet

### ISSUE THREAD

**Issue by sylvain-m** [addok/addok#163]
_In French (english below)_

Bonjour et bravo à tous pour le travail effectué sur BAN(O) et Addok !
N'étant pas vraiment développeur, je trouve qu'il serait intéressant de publier une démo de l'utilisation d'Addok dans une carte Leaflet, afin de montrer la puissance de ce moteur de recherche et de faciliter son utilisation par des novices comme moi en Javascript.
Qu'en pensez-vous ?
(peut-être cela existe-t-il déjà, auquel cas veuillez m'excuser)
A+

Sylvain M.

_In English :
Hello and congratulations for the work done on BAN (O) and ADDOK!
I'm not being really developer, and I think it would be interesting to publish a demo of using Addok in Leaflet map to show the power of this search engine and to facilitate its use by novices like me in javascript.
What do you think about it ?
(Perhaps it's already exist, in which case I apologize)
Thanks !

Sylvain M._

**Comment by sylvain-m** [comment]
Sorry : i did not see the leaflet-control-geocoders with addok demo.
https://github.com/Cyrille37/leaflet-control-geocoders
https://github.com/Cyrille37/leaflet-control-geocoders/blob/master/demo/demo-addok.html
It's perfect !

Sylvain M.

**Comment by yohanboniface** [comment]
@sylvain-m http://adresse.data.gouv.fr/map/ itou ;)
