### ISSUE TITLE
filtre à valeur multiple

### ISSUE THREAD

**Issue by cquest** [addok/addok#165]
Pour permettre une recherche sur:
- plusieurs codes postaux
- plusieurs codes INSEE

il faudrait pourvoir passer une liste de valeurs, par exemple: postcode=75016+75116 (pour le 16ème arrondissement)

**Comment by Ismael-Hery** [comment]
Je plussoie ! Pour l'instant on n'utilise plus la BAN sur LaBonneBoite car on est passé sur une recherche par ville qu'on ne peut pas faire en l'état :-(

**Comment by yohanboniface** [comment]
> on est passé sur une recherche par ville qu'on ne peut pas faire en l'état

Tu peux être un peu plus précis?

**Comment by yohanboniface** [comment]
> il faudrait pourvoir passer une liste de valeurs, par exemple: type=city+town+village

Redis ne connaît pas le "OR" dans les inersections de set, alors c'est vraiment pas gagné. C'est une limitation du modèle qui il me semble est claire depuis le début. Si on veut corriger ça faut mettre les mains dans le C, et je suis même pas sûr que ça soit faisable (sinon ce serait peut-être déjà fait).

On peut certainement réfléchir à des contournerments, par exemple en faisant plusieurs passes (une par valeur de filtre), mais la time complexity serait terrible, ça pourrait coûter très très cher si on met beaucoup de valeurs et/ou combine les filtres.

> plusieurs type (city+town+village)

C'est un détail ici, mais au passage: je pense que ces trois types devraient être unifiés.

**Comment by Ismael-Hery** [comment]
@yohanboniface : tu peux jouer avec la recherche géo dans La Bonne Boite, ça te montre notre usage : http://labonneboite.pole-emploi.fr/

En gros:
* recherche par ville ou code postal. Pas de doublon quand plusieurs code postaux pour une ville.
* completion dès la 3eme lettre
* ordonnancement par population

**Comment by Ismael-Hery** [comment]
@yohanboniface : la solution de fusionner les 3 types répond aussi à mon besoin ;-)

**Comment by cquest** [comment]
La fusion city+town+village répond au troisième point, pas aux deux
premiers forts utiles aussi.

On peut commencer faire ça comme ça pour palier au manque de cumul.

2016-04-26 21:20 GMT+02:00 Ismael Hery <notifications@github.com>:

> @yohanboniface <https://github.com/yohanboniface> : la solution de
> fusionner les 3 types répond aussi à mon besoin ;-)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/addok/addok/issues/165#issuecomment-214857239>
>



-- 
Christian Quest - OpenStreetMap France

**Comment by frodrigo** [comment]
Moi aussi dès ma première mise en place d'Addok j'ai fusionné city+town+village
https://github.com/etalab/ban-data/issues/64

**Comment by frodrigo** [comment]
cf #106

**Comment by cquest** [comment]
city, town et village ont été fusionnés en "municipality" début janvier...

**Comment by yohanboniface** [comment]
Malheureusement trop coûteux avec le code actuel et les possibilités de Redis pour intersecter les sets.
