### ISSUE TITLE
Explain how addok work

### ISSUE THREAD

**Issue by frodrigo** [addok/addok#167]
Explain the underlay algo in the doc.

**Comment by yohanboniface** [comment]
https://speakerdeck.com/yohanboniface/addok-presentation

**Comment by yohanboniface** [comment]
Added to the [documentation](http://addok.readthedocs.io/en/latest/).

**Comment by yohanboniface** [comment]
See also http://addok.readthedocs.io/en/latest/concepts/ and http://addok.readthedocs.io/en/latest/faq/
