### ISSUE TITLE
géoloc csv très lente

### ISSUE THREAD

**Issue by dzaouch** [addok/addok#168]
La géolocalisation à partir d'un csv est très lente, autant avec un addok sur le réseau local qu'en passant par l'api data.gouv, le temps de traitement pour 10 000 lignes (fichier de 600ko) est d'approx. 3 min.
Je peux avoir des fichier de plus de 500 000 lignes à passer, ce qui prendrait approx 2h15, ce qui est assez long.

N'y a-t-il pas un moyen de réduire cette durée ?

**Comment by parville** [comment]
Bonjour David,

Tu veux bien nous expliquer combien de millions d'adresse tu dois géocoder chaque jour ? Ca correspond à quoi pour ma gouverne ?  Vu le nombre d'adresses en France j'ai du mal à concevoir que ce besoin soit récurrent.

Tout de même 55 géocodages à la seconde, moi ça me parait pas mal vu que ce n'est pas une donnée élémentaire ! 
As-tu envisagé de multiplier tes serveurs internes en // ? Tu en mets 5, tu iras 5 fois plus vite !

**Comment by dzaouch** [comment]
Salut,

Je n'ai pas des millions d'adresse à géocoder chaque jour, la plupart du temps, ça tourne autour de 50 000. Je t'avoue n'avoir aucune idée de la vitesse de traitement des requêtes sous redis. Mes notions des SQBD plus classiques m'ont fait dire que ce traitement était long, mais à priori, je me trompe.

Je vais regarder de plus près comment fonctionne addok et redis. 
En attendant, ta suggestion de multiplier les serveurs internets en // me semble une très bonne idée ;)

**Comment by yohanboniface** [comment]
>  En attendant, ta suggestion de multiplier les serveurs internets en // me semble une très bonne idée

Multiplier les

**Comment by parville** [comment]
Cool !

**Comment by cquest** [comment]
addok fonctionne en multithread, il faut segmenter le CSV et paralleliser ou alors faire des appels directs parallèles.

A utiliser sans modération sur une instance privée, mais à ne pas faire sur l'instance publique. nginx est d'ailleurs configurer pour n'autoriser que 2 requêtes simultanées depuis la même IP.
