### ISSUE TITLE
Combien de RAM pour la base BANO full data ?

### ISSUE THREAD

**Issue by dzaouch** [addok/addok#169]
Salut,

Combien de ram conseillez-vous pour le stockage redis de http://bano.openstreetmap.fr/data/full.sjson.gz

J'ai un serveur avec 26Go de mémoire, redis prends 25Go (95%) et j'ai l'impression que mon problème de perf vient en partie de là.

En attendant votre réponse, je vais tester avec des jeux de données plus petits (seulement sur certains départements)

Merci ;)

**Comment by cquest** [comment]
25Go c'est étonnant, l'instance de adresse.data.gouv.fr prends moins de 16Go et tourne dans un container de 20Go sur les données BAN de http://bano.openstreetmap.fr/BAN_odbl/BAN_odbl.json.bz2 qui contiennent plus d'adresses, mais n'ont pas les lieux-dits (ce qui peut expliquer la différence).

**Comment by dzaouch** [comment]
Ok, je devais avoir un gros souci avec mon redis, faut dire que je l'ai pas mal bidouillé...

Donc j'ai tout reset et j'ai refait un import de http://bano.openstreetmap.fr/data/full.sjson.gz et redis occupe 14Go de RAM, pour 12,5 millions de keys
Je laisse cette info ici pour qui le voudrait
