### ISSUE TITLE
Identify mac os x

### ISSUE THREAD

**Issue by tmerlier** [addok/addok#172]
Enhance #171 solution to avoid try catch

**Comment by yohanboniface** [comment]
We cannot avoid the `try/catch` in any case I think.
But we can avoid the need for the Mac fan boy to install `gnureadline` by hand :)

**Comment by yohanboniface** [comment]
Fixed by https://github.com/addok/addok/commit/efb32b4b407fb807aa778165e5b021c7dd3fc4c5 AFAIK.
