### ISSUE TITLE
Manque répertoire helpers 

### ISSUE THREAD

**Issue by fracolo** [addok/addok#177]
La commande `pip install addok` ne copie pas le répertoire helpers du code source.

**Comment by yohanboniface** [comment]
`pip install addok` va installer la version stable (0.5.x), donc c'est "normal".
Il faut installer depuis git pour avoir la version en développement.

**Comment by fracolo** [comment]
Merci d'avoir répondu si rapidement.
Le problème est que dans le README.md, la documentation donnée est celle de la dernière version http://addok.readthedocs.org/en/latest/
Et, dans celle-ci, en suivant le tutoriel, dans une procédure d'installation à partir de pip, le fichier local.py suppose une présence du module helpers (et qui n'y est pas avec `pip install addok`).
A côté de ça, l'installation du plugins trigrams plante pour la même raison.
