### ISSUE TITLE
Installation sur ubuntu 16.04

### ISSUE THREAD

**Issue by BrunoGee** [addok/addok#186]
Bonjour,
Impossible d'importer une base de données...
Voici les commandes effectuées :
sudo apt-get install redis-server python3 python3-dev python-pip python-virtualenv virtualenvwrapper
sudo mkdir /ban && cd /ban
sudo virtualenv addok –python=/usr/bin/python3.5
source addok/bin/activate
sudo -H pip install addok
wget http://bano.openstreetmap.fr/data/bano-29.json.gz
gzip -d bano-29.json.gz
addok batch /home/sigeo/bano-29.json

Voici les erreurs :
Traceback (most recent call last):
  File "/usr/local/bin/addok", line 9, in <module>
    load_entry_point('addok==0.5.0', 'console_scripts', 'addok')()
  File "/usr/local/lib/python2.7/dist-packages/addok/bin/__init__.py", line 43, in main
    from addok import config
  File "/usr/local/lib/python2.7/dist-packages/addok/config/__init__.py", line 5, in <module>
    from .default import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/addok/config/default.py", line 2, in <module>
    from pathlib import Path
ImportError: No module named pathlib

**Comment by yohanboniface** [comment]
> /usr/local/lib/**python2.7**/dist-packages/addok/config/default.py

Il faut python >= 3.4. D'une manière ou d'une autre le virtualenv n'était pas actif au moment de l'installation d'addok.

**Comment by BrunoGee** [comment]
Bonjour,
Merci pour la réponse, mais lorsque je fait :
source addok/bin/activate
puis python -V,  je suis bien en python 3.5.2

J'ai donc fait un : sudo -H pip uninstall addok
puis vérifié que j'installai addok avec la version 3.5.2
Mais il installe dans le repertoire /usr/local/lib/python2.7/

(addok) sigeo@SIGEO-MAPSRV:/ban$ python -V
Python 3.5.2
(addok) sigeo@SIGEO-MAPSRV:/ban$ sudo -H pip install addok --upgrade
Collecting addok
Requirement already up-to-date: Werkzeug==0.11.3 in /usr/local/lib/python2.7/dist-packages (from addok)
Requirement already up-to-date: docopt==0.6.2 in /usr/local/lib/python2.7/dist-packages (from addok)
Requirement already up-to-date: ngram==3.3.0 in /usr/local/lib/python2.7/dist-packages (from addok)
Requirement already up-to-date: redis==2.10.5 in /usr/local/lib/python2.7/dist-packages (from addok)
Requirement already up-to-date: gunicorn==19.4.5 in /usr/local/lib/python2.7/dist-packages (from addok)
Requirement already up-to-date: Unidecode==0.04.18 in /usr/local/lib/python2.7/dist-packages (from addok)
Requirement already up-to-date: hiredis==0.2.0 in /usr/local/lib/python2.7/dist-packages (from addok)
Requirement already up-to-date: python-geohash==0.8.5 in /usr/local/lib/python2.7/dist-packages (from addok)
Installing collected packages: addok
Successfully installed addok-0.5.0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by yohanboniface** [comment]
`pip install addok` pas `sudo -H pip install addok`

**Comment by BrunoGee** [comment]
Le problème c'est que j'ai un message d'erreur : 

Exception:
Traceback (most recent call last):
  File "/ban/addok/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/ban/addok/lib/python3.5/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/ban/addok/lib/python3.5/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/ban/addok/lib/python3.5/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/ban/addok/lib/python3.5/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/ban/addok/lib/python3.5/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/ban/addok/lib/python3.5/site-packages/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/ban/addok/lib/python3.5/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/ban/addok/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission non accordée: '/ban/addok/lib/python3.5/site-packages/hiredis-0.2.0.dist-info'

**Comment by yohanboniface** [comment]
Il faut supprimer le virtualenv et recommencer depuis le début, là les paquets installés sont vraisemblablement en user root.

**Comment by BrunoGee** [comment]
Effectivement...
rm - r /ban
Puis réinstallation...
C'est le mkdir /ban de : http://geotribu.net/node/811
qui m'a induit en erreur car je ne pouvais pas le créer à la racine...

Merci Yohan pour votre aide...

**Comment by BrunoGee** [comment]
Je viens de trouver le tutoriel (je tombais sur http://addok.readthedocs.io/en/0.5.x/ et non http://addok.readthedocs.io/en/latest/ ;-))
J'ai donc fait pip install addok-fr addok-france addok-csv
et voici les messages :
(addok) sigeo@SIGEO-MAPSRV:~/ban$ pip install addok-fr
Collecting addok-fr
  Could not find a version that satisfies the requirement addok-fr (from versions: )
No matching distribution found for addok-fr
(addok) sigeo@SIGEO-MAPSRV:~/ban$ pip install addok-france
Collecting addok-france
  Could not find a version that satisfies the requirement addok-france (from versions: )
No matching distribution found for addok-france
(addok) sigeo@SIGEO-MAPSRV:~/ban$ pip install addok-csv
Collecting addok-csv
  Could not find a version that satisfies the requirement addok-csv (from versions: )
No matching distribution found for addok-csv

(Je suis toujours sur ubuntu 16.04)

**Comment by yohanboniface** [comment]
Désolé, le tutoriel est un peu en avance, il n'y a pas de release sur pypi, mais on approche! ;)
Il faut installer via git pour l'instant, donc:

    pip install git+https://github.com/addok/addok
    pip install git+https://github.com/addok/addok-fr
    …

**Comment by BrunoGee** [comment]
Merci pour votre réactivité.
Je suis un très bon béta-testeur pour chercher les bugs et pour pour l'écriture des tutos ;-)
J'ai donc réussi à faire fonctionner addok avec une base bano.
La suite sera de produire une base d'adresse sur la Nouvelle-Calédonie.
Comme j'utilise QGIS et postgis, j'aimerais utiliser le plugin addok-postgis.
Est-ce qu'il est mieux de partir sur une autre "issue" ?

**Comment by BrunoGee** [comment]
Désolé, encore un soucis de config. Impossible d'avoir accès à l'API addok
http://202.171.68.203:7878/search/?q=bur
Pourtant, le serveur dit :
$ addok serve
Blocked plugins:
Blocked plugins:
Serving HTTP on 127.0.0.1:7878…

j'ai fait un sudo iptables -I INPUT -p tcp -i eth0 --dport 7878 -j ACCEPT

**Comment by yohanboniface** [comment]
--host 0.0.0.0 pour qu'il soit accessible via n'importe quelle IP (pas seulement 127.0.0.1).

Pour le plugin addok-qgis, je connais pas, je suis pas sûr de pouvoir aider.

**Comment by BrunoGee** [comment]
Merci.
Je parlais du plugin addok-**post**gis
