### ISSUE TITLE
French translation: how to manage it?

### ISSUE THREAD

**Issue by ThomasG77** [addok/addok#188]
I've done a first full translation with [this branch](https://github.com/webgeodatavore/addok/tree/0.5.x-fr)
I could always publish like the official project through RDTD but I wanted to inform: Addok is open source but one point of entry would be better IMO.

A review of the translation would also be needed.

Waiting for feedbacks.

**Comment by ThomasG77** [comment]
I've published the documentation for 0.5.x-fr at http://addok-fr.readthedocs.io/fr/0.5.x-fr/
I can always remove it later to put everything addok related under the same official website http://addok.readthedocs.org

**Comment by yohanboniface** [comment]
https://docs.readthedocs.io/en/latest/localization.html

Seems to be working only with Sphinx (while we are using mkdocs). And it does not seem that easy.
I'm not sure it's worth it, so may the way you made it is OK.

**Comment by ThomasG77** [comment]
Ok so I will do not change anything and close the ticket.
Ask if at a moment, for any reasons, you need ownership or at least write access to the repository.

**Comment by ThomasG77** [comment]
Just for the follow-up, I've now nearly full French translation for the 1.0 branch

Remaining  jobs are:
* catch some recent docs changes in approximately the last 10 commits
* finish the changelog translation
* review my translation: some parts, a bit rough, can be improved. I also have some thoughts about replacing or not some technical words from English to French

You can see the result at http://addok-fr.readthedocs.io/fr/master-b00b342-fr/

Feedbacks are welcome

**Comment by ThomasG77** [comment]
With current 1.0.0 stable release, the French docs translation has been updated for current master http://addok.readthedocs.io/fr/master-0f766f7-fr/ and 1.0.0 tag http://addok.readthedocs.io/fr/1.0.0-fr/

**Comment by davidbgk** [comment]
That's great, how can we promote it? How do you currently deal with diffs/versions?

**Comment by ThomasG77** [comment]
## Promotion

In fact, it's partly promoted at http://addok.readthedocs.io. It seems @yohanboniface has set a redirection from the official project. Go to the bottom left and you will see the following 
![selection_641](https://cloud.githubusercontent.com/assets/642120/25785366/c23570a2-337e-11e7-9270-867d7425ce33.png) It redirects to http://addok-fr.readthedocs.io under the hood.
IMO, to promote this translation, we could mention it explicitly on the Github README.md or make a reference in the doc itself.

## Maintenance

For a branch, I make a diff between both English current branch and the SHA1 version at the moment I've done the French translation using Meld. With this operation, I'm able to locate changes and make the update on the French translation branch accordingly.

Mkdocs does not manage translation and I do not want to change the entire process for documentation in the project. So, it's the best solution I've found.
Switching to Sphinx for this amount of documentation does not seem the right move. You will need to use Transifex for simple translation and then instead of Markdown translation issues, you will have Transifex update management to deal with...
