### ISSUE TITLE
Problèmes d'installation

### ISSUE THREAD

**Issue by gsueur** [addok/addok#189]
Bonjour,

Quelle est l'actuelle marche à suivre pour déployer un serveur Addok ? La page github indique d'utiliser la version Pip, mais il n'y a pas de version pip pour les exensions -fr -france et -csv, en encore moins de module helpers dans cette version, qui donc ne fonctionne pas dès lors qu'on essaie de suivre le tutoriel... 

En vous remerciant

**Comment by gsueur** [comment]
OK, j'ai trouvé. Il ne faut pas utiliser http://addok.readthedocs.io/en/latest/tutorial/ mais bien http://addok.readthedocs.io/en/latest/config/

**Comment by yohanboniface** [comment]
Autre option: utiliser le tutorial mais faire un `pip install git+https://githum.com/addok/addok-xxx` à la place des `pip install addok-xxx` en attendant les releases sur pypi (oui il faudrait mettre à jour le tutorial vu que ça traîne…)
