### ISSUE TITLE
réponse type=street sans ... attribut street !

### ISSUE THREAD

**Issue by parville** [addok/addok#190]
Bonjour,

En faisant un peu de reverse pour retrouver des adresses à partir de lon/lat 

je constate que pour une réponse de type=street, il n'y a pas d'élément street dans la localisation retournée !

Par contre c'est ok pour une réponse de type=housenumber 

(c'est évidemment idem si on search et pointe sur une street) 

Est-ce volontaire ?

**Comment by yohanboniface** [comment]
> Est-ce volontaire ?

Vraisemblablement pas. Tu peux donner un exemple s'il-te-plaît?

**Comment by yohanboniface** [comment]
N'hésite pas à rouvrir si tu as un exemple sous la main :)
