### ISSUE TITLE
Raising the max size of CSV in batch geocoding

### ISSUE THREAD

**Issue by sgskt** [addok/addok#191]
Hi,
Is there any way I can raise the max size of the CSV file to process in my own local installation of addok?

**Comment by yohanboniface** [comment]
This should only be a matter of your Nginx configuration: `client_max_body_size`, `max_execution_time` (timeout) and such.
Depending on the wsgi module you are using, you may need to change the timeout there too (I think it's the case for Gunicorn, but afaik no need for uwsgi).

**Comment by sgskt** [comment]
Thanks! Yes, I got it to work by changing the timeout in Gunicorn/Nginx.
