### ISSUE TITLE
Difference between api-adresse.data.gouv.fr and addok

### ISSUE THREAD

**Issue by Crapal** [addok/addok#198]
Hi,

I've got a different result when i'm using the data.gouv.ft api and addok.
Example : 
- http://api-adresse.data.gouv.fr/search/?q=75475+PARIS&limit=1, the first result is in Paris
{"limit": 1, "attribution": "BAN", "version": "draft", "licence": "ODbL 1.0", "query": "75475 PARIS", "type": "FeatureCollection", "features": [{"geometry": {"type": "Point", "coordinates": [2.3469, 48.8589]}, "properties": {"citycode": "75056", "adm_weight": "6", "name": "Paris", "city": "Paris", "postcode": "75000", "context": "75, \u00cele-de-France", "score": 0.45454545454545453, "label": "Paris", "id": "75056", "type": "city", "population": "2244"}, "type": "Feature"}]}

- With addok (in Lot et Garonne)
{"limit": 1, "attribution": "BANO", "version": "draft", "query": "75475 PARIS", "features": [{"geometry": {"coordinates": [0.66873, 44.266323], "type": "Point"}, "type": "Feature", "properties": {"postcode": "47510", "score": 0.3941558441558441, "label": "Paris 47510 Foulayronnes", "region": "Aquitaine", "id": "47100B185V", "departement": "Lot-et-Garonne", "city": "Foulayronnes", "name": "Paris", "type": "place"}}], "type": "FeatureCollection", "licence": "ODbL"}

With such a difference ?

Thanks.

**Comment by jdesboeufs** [comment]
The official API now uses BAN data: http://bano.openstreetmap.fr/BAN_odbl/.
You probably use BANO data: http://bano.openstreetmap.fr/data/

**Comment by yohanboniface** [comment]
Paris, Lyon and Marseille are actually missing from the data, because they are not "municipalities" as others (they have arrondissements).
We have a PLM.json file specific for those in our server:

```
{"id": "75056","citycode":"75056","type": "city","name": "Paris","postcode": "75000","lat": "48.8589","lon": "2.3469","city": "Paris","context":"75, Île-de-France", "population": 2244, "adm_weight": 6, "importance": 1}
{"id": "69123","citycode":"69123","type": "city","name": "Lyon","postcode": "69000","lat": "45.7579","lon": "4.8353","city": "Lyon","context": "69, Rhône, Rhône-Alpes", "population": 484, "adm_weight": 5, "importance": 0.9 }
{"id": "13055","citycode":"13055","type": "city","name": "Marseille","postcode": "13000","lat": "43.2804","lon": "5.3806","city": "Marseille","context": "13, Bouches-du-Rhône, Provence-Alpes-Côte-d'Azur", "population": 850, "adm_weight": 5, "importance": 0.9}
```

So you may just be missing this data. Try creating the file and importing it.

**Comment by Crapal** [comment]
I'm mounting a 2nd server with the BAN data to see how it works.
Meantime, I can't find this PLM.json file. 
Can you give me the link please ?

**Comment by yohanboniface** [comment]
>  Can you give me the link please ?

The content is up there, just copy-paste it ;)

**Comment by Crapal** [comment]
@jdesboeufs BAN file added, still got bad results.
@yohanboniface It works with the plm.json file. Thanks a lot.
