### ISSUE TITLE
Doc/Question: how score is computed?

### ISSUE THREAD

**Issue by gdrouet** [addok/addok#210]
We should find details about score computation inside the documentation.
For instance, if we enter an exact address like [this](http://api-adresse.data.gouv.fr/search/?q=111%20Rue%20de%20Croix,%2059510%20Hem%20), the score is "just" `0.9157636363636362`. How to obtain a score of 1?

**Comment by yohanboniface** [comment]
Score is:
- string distance from 0 to 1
- document importance from 0 to 0.1
- optionally geographical distance from 0 to 0.1

Then scaled back to 0 to 1 scale.
But the score computation is considered an internal detail and may change anytime. It's only used for sorting.

Side note: not sure how you use addok, but I'm in Lille for some days, I may find one or two hours to give a hand if it helps.

**Comment by gdrouet** [comment]
Sure I send you a mail.
