### ISSUE TITLE
What are the requirements to run your own addok server?

### ISSUE THREAD

**Issue by youribonnaffe** [addok/addok#213]
I have a few questions regarding the cost of running my own addok server using the full BAN dataset.
From the documentation I only found this reference: _If you only want a subset of the data (the whole BANO dataset requires 20GB of RAM)_

- What are the requirements for the server in terms of CPU, RAM, Disk?
- How long would it take to import the full dataset (that would be all French addresses I guess)?
- Does the BANO dataset often changes?

- Does the public instance on api-adresse.data.gouv.fr enforce usage limits?

Thanks,

**Comment by youribonnaffe** [comment]
Just read https://speakerdeck.com/yohanboniface/addok-presentation?slide=7 so replying to myself for the RAM requirement: 16G for France

**Comment by cquest** [comment]
Basic setup for France is around 16GB, with filters on citycode, postcode, type you need a little less than 19GB (that's our setup for the public instance).

On our production server, full dataset import takes around 20 minutes.

BANO dataset is updated nightly. BAN dataset is updated weekly.

Public instance currently have only one limit: 10 queries/second from the same IP.
