### ISSUE TITLE
citycode filter problem when city have "arrondissements"

### ISSUE THREAD

**Issue by jdauphant** [addok/addok#227]
Hello,

I would like to filter adresse search on city like Paris and Marseille.
I can't use citycode because each arrondissement have a different citycode (and I can filter only one).
I can't postcode because there is multiple postcode for the city (and I can filter only one).

If I filter the search manually after the search, the autocompletion result is really bad.

Possible solutions that will help me:
- citycode filter also work for the true city code and not only arrondissement
- a radius filter for the lon/lat preference
- give a array of citycode or postcode as a filter

Thanks for your help,
Julien

**Comment by yohanboniface** [comment]
Should be fixed by https://github.com/addok/addok/commit/68de11f44aaceb1ec6444541bcbfcbf00bf7f0d7 (and thus allowing to index both citycodes).
But not yet released in Etalab servers.

**Comment by kaelhem** [comment]
@yohanboniface do you know if this feature will be available soon ?

**Comment by yohanboniface** [comment]
On its way (a matter of days, I'd say). 
Needs also a change in the data to have both citycodes.
ping @cquest

**Comment by cquest** [comment]
I'll try to add this in the next data reload (around february 27th).
It is also very useful for merged municipalities as it allows to find addresses with current or past citycodes.

**Comment by kaelhem** [comment]
Glad to hear that! Btw, is there a place to follow updates on the Etalab servers ? Thanks
