### ISSUE TITLE
Questions Addok

### ISSUE THREAD

**Issue by Louisus** [addok/addok#228]
Bonjour,
Je suis étudiant et je travaille avec votre géocodeur pour un projet. La problématique est que je dois en aucun cas faire appel à des services sur le web, tout doit rester en local. J'ai donc deux questions sur addok:
- Comment est calculé le score du résultat du géocodage?
- Est ce que la BAN, liée à addok, peut géocoder des lieux-dits ou faut-il passer par une autre base (BANO ou BD Adresse) pour les géocoder?
- Si il faut passer par une autre base, puis-je intégrer la BANO ou la BD adresse de l'IGN directement dans addok, et comment réaliser les appels pour géocoder (deux api (api ban et api bano par exemple) + script python?) 
Merci d'avance.

**Comment by yohanboniface** [comment]
> Comment est calculé le score du résultat du géocodage?

Calcul de similarité de chaîne essentiellement, plus optionnellement l'importance intrinsèque du document (pour distinguer deux "Avenue de la République").

> Est ce que la BAN, liée à addok, peut géocoder des lieux-dits ou faut-il passer par une autre base (BANO ou BD Adresse) pour les géocoder?

BANO pour les lieux-dits pour l'instant.

> Si il faut passer par une autre base, puis-je intégrer la BANO 

oui => http://bano.openstreetmap.fr/data/

> et comment réaliser les appels pour géocoder (deux api (api ban et api bano par exemple) + script python?)

En attendant le jour béni où on aura intégré la BAN dans BANO, @cquest a bidouillé un truc du genre par ici: https://github.com/cquest/geocodage-sirene

**Comment by Louisus** [comment]
Merci pour votre réponse! Cela nous aide pour notre projet.

Nous aurions une autre question:
Nous savons que la BDAdresse de l'IGN est utilisée pour la BAN mais avez vous fait des tests avec la BDAdresse dans votre géocodeur? Est-ce que votre géocodeur est compatible avec d'autres données de référence, comme la BDAdresse? 
Merci d'avance.

**Comment by cquest** [comment]
addok n'est pas spécifique à la BAN.
On peut lui fournir bien d'autres données comme base de référence.

Voir par exemple bano.addok.xyz  instance avec la base BANO d'OSM-France (distincte de la BAN, c'est celle que j'utilise pour géocoder SIRENE).

J'avais mis en place une instance avec des POI, qui permet de retrouver par exemple un arrêt de bus par son nom ou un restaurant.

L'important est de préparer le JSON attendu pour charger addok et on peut générer un tel JSON à partir de la BD Adresse.
