### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#23]
Maybe a base image and an image with already the data.

**Comment by RemiDesgrange** [comment]
And what about putting a dockerfile in the doc ?

**Comment by yohanboniface** [comment]
Never get to a really useful Docker way. But here is the Dockerfile of my "docker" branch in case you want to hack on it:
```
FROM python:3.4
RUN apt-get -q update && apt-get -qy install git && apt-get -qy autoremove
RUN pip install addok
RUN pip install gunicorn
EXPOSE 7878
ENTRYPOINT ["addok"]
```

**Comment by RemiDesgrange** [comment]
I think this is enough for a working example, if you just add the import process (the wget of data, and the addok batch /file.sjson && addok ngrams) it works perfectly

**Comment by davidbgk** [comment]
See https://github.com/addok/addocker
