### ISSUE TITLE
Allow to control number of workers during import

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#237]
sqlite crashes when using 24 cores, so it may be helpful to limit them a bit.

**Comment by davidbgk** [comment]
Or change the [multithreading](https://sqlite.org/threadsafe.html) options?

**Comment by yohanboniface** [comment]
> Serialized. In serialized mode, SQLite can be safely used by multiple threads with no restriction.

Which seems to be the default mode.

Also, for the record, not sure here it's relevant (I guess they write "thread" like "things"), but we are doing multiprocessing, not multithreading.

**Comment by cquest** [comment]
I tried to add locks (acquire/release) with no effect :(

**Comment by davidbgk** [comment]
@cquest do you know exactly how many cores leads to errors? For the moment we only know that 8 works and 24 doesn't. Might be useful to get the exact limit point to investigate.

**Comment by cquest** [comment]
The limit is not that clear. I got crashes with 4 processes.
The more cores you have the more often you'll have some trouble, same applies with slower disks as it takes more time for sqlite to update its db/journal. In my case, I have 24 cores and the sqlite db/journal is stored on HDD (not SSD).
Limiting the number of process is not safe (unless we only have 1).

**Comment by davidbgk** [comment]
Do you have an error message from sqlite? A log or something? Hard to reproduce when you're somehow limited in terms of CPUs…

**Comment by davidbgk** [comment]
https://docs.python.org/3/library/sqlite3.html#sqlite3.enable_callback_tracebacks might help debugging. Did you play with the [isolation level](https://docs.python.org/3/library/sqlite3.html#controlling-transactions)?

**Comment by davidbgk** [comment]
More options from https://www.reddit.com/r/learnpython/comments/3ml7zh/multiprocessing_and_sqlite3_how_to_handle/cvge8df/ using [PRAGMA](https://www.sqlite.org/pragma.html) and verify that [AUTOINCREMENT](https://www.sqlite.org/autoinc.html) is disabled.

**Comment by davidbgk** [comment]
Many readers but [only one writer](http://sqlite.org/faq.html#q5)? C'mon SQLite… We can try to adapt the [`busy_timeout` option](http://sqlite.org/pragma.html#pragma_busy_timeout) but I'm pessimistic about the resolution of that issue.
