### ISSUE TITLE
Asynchronous server?

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#25]
http://tavendo.com/blog/post/going-asynchronous-from-flask-to-twisted-klein/

**Comment by yohanboniface** [comment]
https://github.com/jonathanslenders/asyncio-redis

**Comment by yohanboniface** [comment]
https://github.com/aio-libs/aioredis

**Comment by davidbgk** [comment]
See: http://mathieu.agopian.info/blog/python-et-asyncio-la-recette-du-bonheur.html

We made a whole sprint about that and the conclusion is that the overhead of coroutines is too high for our use-case.

**Comment by davidbgk** [comment]
See: http://mathieu.agopian.info/blog/python-et-asyncio-la-recette-du-bonheur.html

We made a whole sprint about that and the conclusion is that the overhead of coroutines is too high for our use-case.
