### ISSUE TITLE
faster search_result_processor ?

### ISSUE THREAD

**Issue by cquest** [addok/addok#250]
In https://github.com/addok/addok/blob/master/addok/core.py#L223 and below, we have a 2 level loop, which means each processor is called for each document.

Why not pass a list of document to processors to call each of them only once ?
It may also allow to reduce the document list at each step to speed up further processors.

**Comment by yohanboniface** [comment]
> Why not pass a list of document to processors to call each of them only once ?

But then each processors will loop through each result…
The option may be to use generators like we do for PROCESSORS, but honestly here I don't think there is significative gain to justify more complexity.
Bottleneck here is string processing for scoring.
