### ISSUE TITLE
City name with dash or without

### ISSUE THREAD

**Issue by RemiDesgrange** [addok/addok#263]
Hi,

I set up addok with `addocker`. I just change the ban file from 57 to 73 (ban-73.json).

this request doesn't return any result: `http://localhost:7878/search?q=Boulevard Franklin Roosevelt&city=Aix Les Bains` because it need to be `city=Aix-les-Bains` also `city=Aix-Les-Bains` doesn't work.

I don't know if it's intentional.

Thanks

**Comment by yohanboniface** [comment]
Yes, filters need exact value. This is not a search.
You basically are telling Addok "search for something that looks like 'Boulevard Franklin Roosevelt' with a city equal to 'Aix Les Bains'"
