### ISSUE TITLE
Addok pypi central whl package is wrong

### ISSUE THREAD

**Issue by orphaner** [addok/addok#265]
Hy There, 
I'm @gdrouet coworker and whe are together installing an addok instance.
We based our installation on the 1.0.0-rc1 version installed via pip.
We got stucked a while on this error: 
```
AttributeError: module 'addok.config' has no attribute 'RESOURCES_ROOT'
...
  File "/srv/addok/venv/lib64/python3.5/site-packages/addok/textutils/default/__init__.py", line 25, in load_synonyms
    with config.RESOURCES_ROOT.joinpath(config.SYNONYMS_PATH).open() as f:
```
BUT we were unable to find any folder textutils on the 1.0.0-rc1 tag source code.
I'll skip you the path to the resolution and go straight to the error.
On the central pypi repository (https://pypi.python.org/pypi/addok/1.0.0rc1) the .whl file is wrong: it contains that old "textutils" folder. Installing addok with "pip install git+https://github.com/addok/addok" is all fine.

I'm not a python guy, so I do not have any patch or idea why it could be wrong (before today I had never eared about any whl file ;), this issue is just to let you know about what we've faced today.

See you,
Nicolas

**Comment by davidbgk** [comment]
Hi Nicolas,

Thanks for reporting, there was an issue when we generated the wheel and we will issue a rc2 soon to take care of that.

**Comment by davidbgk** [comment]
Hello Nicolas,

The RC2 has been released and published on pypi, can you retry and told us if it works now?

Thanks.

**Comment by gdrouet** [comment]
Hi,

the issue is different now : AttributeError: 'module' object has no attribute 'RESOURCES_ROOT'

**Comment by yohanboniface** [comment]
Humm, just tested on a clean virtualenv without any error. Can you reset your virtualenv and try again?

Just in case, can you give me the command you are running, the full traceback, and the local config you use?

**Comment by yohanboniface** [comment]
You installed 'addok==1.0.0-rc.2', right?

**Comment by yohanboniface** [comment]
`pip freeze` will tell you the installed version.

**Comment by gdrouet** [comment]
Yes I'm quite sure the RC2 was installed. I fallback to the manually fixed RC1 to go ahead with my work for now. I'll make my test again with RC2 later. Keep you informed.

**Comment by gdrouet** [comment]
FYI I'm unable to reproduce with `1.0.0`.
