### ISSUE TITLE
Server error for reverse geocoding with lon=0&lat=0 (devapi)

### ISSUE THREAD

**Issue by MarHoff** [addok/addok#272]
Behavior changes introduced by devapi break tests on my client implementation [pg_frapi](https://github.com/adauhr/pg_frapi)

**Actual behavior with main API**
`api-adresse.data.gouv.fr/reverse?lon=0&lat=0`
- Return a JSON object "baninfo" such as 
<pre>"{
    "type": "FeatureCollection",
    "limit": 1,
    "licence": "ODbL 1.0",
    "version": "draft",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    0.0,
                    0.0
                ]
            },
            "properties": {
                "id": "db",
                "name": "baninfo",
                "type": "info",
                "label": "baninfo",
                "score": 1.0,
                "context": "20170212T171816",
                "distance": 0
            }
        }
    ],
    "attribution": "BAN"
}"</pre>

**New behavior on devapi**
devapi-adresse.data.gouv.fr/reverse?lon=0&lat=0
- Return internal server error
- search api is however unafected and return a "baninfo" JSON
(devapi-adresse.data.gouv.fr/search?q=baninfo)

**Possible improvements**
-Fix server error when querying for lon=0&lat=0
-Better document test values for external clients

**Comment by yohanboniface** [comment]
Should be fixed by #283.

But this is a totally undocumented and unstable addok call ;)

I'm tempted to say that we should have a proper `/info` endpoint, and to deal with this in a plugin. @cquest thoughs? I can do it if needed.

**Comment by MarHoff** [comment]
Thanks for time taken on this undocumented method!

As far as I'm concerned an additional endpoint is not really needed/appropriate as I'm actually checking if my client can properly connect and get expected result from the "search" and "reverse" endpoint.

So the "baninfo" JSON is actually a good indicator because I can expect a precise response from addok.
Only timestamp in "context" should change between call.

I'm not even sure where that "baninfo" comes from, maybe it's an actual "fake record" in the datatset?

Anyway thanks ;)
