### ISSUE TITLE
Prevent processing huge strings

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#273]
When looking at logs we see things like:

> M " A PE : 4 66 9 B   LIEU DE PAIEMEMT OES COT IS A TI O NS AS S U R A N CE S S O C IA L E S :   SSIOH.COURTAGE, C O M M E RC E , I M P O R T - E X P O R T    URSSAP D'lLE DE FRANCE 22 RUE DE LAGNY   93518 MOMTREUIL 116000001439107610   AFFECTATION   : 01 -SAL012   MINIMUM    EMPLOI   : SUPPORT VENTES 2S   SALAIRE    COEFFICIENT   «   •   CLASSIFICATION   : CADRE C14   DESIGNATION   WOMBRE OU BASE   TAUX OU %   MOMTANT A AJOUTER   APPOINTEMENTS F0RF PRIME ANCIENNETE ABS. JOUR FERIE IND. JOUR FERIE ABSENCE MALADIE INDEM MALADIE TR.l AV LOG/NOURRITURE ^REMUNERATION BRUTE (1) S MALADIE TT   369600   238900   til 50   358:35   34 lil 7 I   aoo   136145   200   135145   I   •*   270:29 . ,:  69  05  6Q 4134    0750   S VI ElLLESSE TA S VI ElLLESSE TT S F.N.A.L. TA ACC.TRAVAIL TT SOLIDAR.AUTO . TT FNAL SUPP. TA FNAL SUPP . DEPLAF.   4134:95 321800 4 134;9 05  32180 4134195 413495 321800 916:95 4134;99  55  4134 426623 321800 91695 413495 321800 321800 91695 91695 413495 321800 91695 321800 91695 321800   6900   0350   S  S  S  S  S  S    AF TX NORMAL TT SUPPL AF TT CSG DEDUCT1B. TT CHOMAGE RAC TA CHOMAGE RAC TB CHOMAGE FNGS R AGFF C/TA R ANEP C/TA R AGFF C/TB C50 R CGRCR C/TB C50 R CGRCR GET R APEC C/TA R APEC C/TB P AXA C/TA P AXA C/TB C84 M AXA MUTUELLE *COT ISAT , SALARIALES (2)  REDEVANCE VEHICULE *XNDEM. NON SOUMISES (3)  REPRISE AV. NATURE S CSG TT   s  c    6 10 0    2 4 0 0   C    2400   c    ■    j   CIO   CIO   tie oo 2100 (1900 7800 0130   C50   C50   C50   C80   0400 0430 2870   C80   4 n   a *•>*• a >*   \   :   ••   i   S RDS TT   4266 2 3   426d 23    2400   0500   FR.SANTE IMP. 92,36 *AUTRE$ RETENUES (4)  EXCED.FISC . 196,iq   ••   •■   : a ■   •«   *«   4 a i ••   • 4   !   FONCTIONNEMENT C.E PARTICIPATION C.E TAXE APPRENTISSAGE FORMATION PROFESS. EFFORT CONSTRUCTION S CONT.DIALOGUE SOC.   4134:95   413495   413495   413495   413495   4134195   DU MOIS   depuis 01 2016   BRUT IMPOTS (1)   4423141   890841    05   n   DONT AVANTAGES NATURE NET FISCAL (1-2)   80160

If the number of tokens is more than xxx (20?), raise a 40x (413?).
Note: should we make the test after preprocessing the request, to let "extract_address" do its job?

**Comment by davidbgk** [comment]
I think it's worth having it for version 1.0 as an optional query processor, thoughts?
