### ISSUE TITLE
Remove/replace comment related to Django in tutorial.md

### ISSUE THREAD

**Issue by ThomasG77** [addok/addok#278]
I know Addok does not use Django but the remaining comment `# Finally, send all non-media requests to the Django server.` from https://github.com/addok/addok/blob/master/docs/tutorial.md#nginx could be misleading. I suppose it's because the example was an excerpt from a more complex configuration file.
It can be changed?
I'm also not sure what would be the appropriate comment instead.

**Comment by yohanboniface** [comment]
Good catch. It can be removed :)

**Comment by ThomasG77** [comment]
Fermé par la PR https://github.com/addok/addok/pull/282
