### ISSUE TITLE
Try to reduce the number of decimal numbers in scores

### ISSUE THREAD

**Issue by davidbgk** [addok/addok#284]
It might reduce the size of the index.

**Comment by yohanboniface** [comment]
From MONITOR command:
```
"ZADD" "w|76" "0.16791666666666666" "d|76001"
```

**Comment by davidbgk** [comment]
I tried a `round(score, 6)` in both `add_score()` and `score()` without any significant improvement on memory. Either I missed something or we can close that one.

**Comment by yohanboniface** [comment]
From [Redis doc](https://redis.io/commands/ZADD):

> Larger integers, or fractions, are internally represented in exponential form, so it is possible that you get only an approximation of the decimal number, or of the very big integer, that you set as score.
