### ISSUE TITLE
addok-csv call syntax

### ISSUE THREAD

**Issue by EtienneArbogast** [addok/addok#287]
Hi,
standard call "http://localhost:8000/search/?q=5 quai du port 13000 marseille" from a browser works fine,
but trying something like "http://localhost:8000/search/csv/?data=c:\addresses.csv" returns a 400 Bad Request error.
I surely missed something somewhere.
What I did :
- installed addok-csv plugin,
- declared API_ENDPOINT = [... , ('search/csv/', 'addok_csv'), ...],
- re-read the docs :-)
but still nothing.

Thank by advance.

**Comment by davidbgk** [comment]
No browser allows that kind of URIs, it would be a terrible security issue if it can access your whole filesystem like this from a GET URL. As recommended [within examples](http://addok.readthedocs.io/en/latest/api/#examples), you have to POST your file either using [curl](https://curl.haxx.se/), [httpie](https://httpie.org/) or whichever HTTP client you prefer.

**Comment by EtienneArbogast** [comment]
Oooops,
ok thanks, trying to do so in Python.

**Comment by ThomasG77** [comment]
I made a demo for Python using `requests` some time ago at https://gist.github.com/ThomasG77/e488251696a00de73631
I'm not sure if it's the best way to do it. Feel free to comment/fork as you wish.

**Comment by davidbgk** [comment]
I think that the way you pass file objects [can be simplified](http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file). I'll try to add something within the doc related to that, might be handy to have examples at least in Python and JS.

**Comment by EtienneArbogast** [comment]
Thanks ThomasG77 & davidbgk,
`requests` is probably the easyest way to go. Here's my working code (I unfortunately don't have access to gist from work...) :
```
startTime = time.time()

# Define geocoding and chunking functions
def geocode_file(inficname, outficname):
    urllib2.getproxies = lambda: {}
    ip = 'the_ip_addok_is_joinable_to'
    url = 'http://{}/search/csv/'.format(ip)

    with open(os.path.join(baserep, inficname), 'rb') as f:
        files = {'data': f}
        reqresp = requests.post(url, files=files)
        with open(os.path.join(baserep, outficname), 'wb') as f2:
            f2.write(reqresp.content)

def chunker(df, size):
    return ((df[pos:pos + size], int(pos/size)) for pos in xrange(0, len(df), size))

for geoc_chunk, chunk_id in chunker(df_adr_uniques, 5000):
    tmpinname = os.path.join(baserep, 'chunk_tmp.csv'.format(chunk_id))
    tmpoutname = os.path.join(baserep, 'chunk_{:0>4}_geocoded.csv'.format(chunk_id))
    df_export = pd.DataFrame(columns=('adr', 'postcode', 'city'))
    df_export['adr'] = geoc_chunk['Adresse1'].replace('*', '').replace('.', '').replace(';', '')
    df_export['postcode'] = geoc_chunk['CPOSTAL']
    df_export['city'] = geoc_chunk['Ville']
    df_export.to_csv(tmpinname, encoding='utf-8', sep=';', index=False)
    geocode_file(tmpinname, tmpoutname)
    print '=====> geocoding {} : {:0.1f} sec'.format(chunk_id, time.time() - startTime)

print '=====> OK csv : {:0.1f} sec'.format(time.time() - startTime)
```
As my initial csv file is very large, I split it in chunks of 5000 lines and do a batch geocoding of each chunk at a time. Works quite well :-)
