### ISSUE TITLE
"Corner" addresses with 2 addresses match first number and last way name

### ISSUE THREAD

**Issue by richterb** [addok/addok#29]
"21 RUE CLEF 34 RUE DAUBENTON" matches "21 rue Daubenton"
http://api.adresse.data.gouv.fr/search/?q=21%20RUE%20CLEF%2034%20RUE%20DAUBENTON,%2075005,%20Paris,%20France&limit=1

I think detecting only matching one of the two addresses would return a correct result. The tricky part is going to separate both addresses I guess... Not sure there is a proper solution, considering street names may contain numbers.

**Comment by yohanboniface** [comment]
> Not sure there is a proper solution, considering street names may contain numbers.

Yes, and they also may contain a street keyword too, for example "Chemin de la Rue Vieille". But maybe we can't have a housenumber AND a street keyword. But maybe this would be a fix too specific ("Rue Clef Rue Daubenton" would not be fixed for example).

**Comment by davidbgk** [comment]
This is a edge case, might be fixed in addok-france one day.
