### ISSUE TITLE
CSV geocoding is not working as before?

### ISSUE THREAD

**Issue by ThomasG77** [addok/addok#291]
When I try to geocode using a CSV file, it's working on the production server e.g http://api-adresse.data.gouv.fr/search/csv/ whereas it fails returning `undefined` on 1.0 dev server e.g http://devapi-adresse.data.gouv.fr/search/csv/

To reproduce the issue, just go to this basic gist https://gist.github.com/ThomasG77/5c731eddbcb9b5fbbd73b91a36b5b6c7
To try it, clone the repo, do an `npm install` (I suppose you have Node) and run `node node unirest-post-multipart.js`

On my own local server, I have the same issue. To confirm, I've tried on the public server. I'm using the addok Python packages list described in the tutorial with the additional addok-csv. The only particular part compared to the tutorial is the fact that I do a `pip install git+https://github.com/addok/addok.git` due to #265 issue

**Comment by davidbgk** [comment]
Either your comments on the gist are wrong or I don't get the issue, I assume they are.

I think it has been fixed in https://github.com/addok/addok/commit/1550275ab5177f83bef1038740bb502e4a0062b8 but it's not yet deployed on the dev server, do you confirm @yohanboniface ?

**Comment by ThomasG77** [comment]
You are right about my wrong comments. The error is reproducible but I forgot the JavaScript asynchronicity nature: the result of the first http call appears after the result of the second http call in the log. I've updated the snippet. Can you at least confirm the issue on the http://devapi-adresse.data.gouv.fr/search/csv/ ?

**Comment by davidbgk** [comment]
I confirm that I can reproduce and it still fails with master's head.

**Comment by davidbgk** [comment]
This is a combination of two bugs:

1. addok-csv plugin is probably not loaded on devapi, hence the current 404
2. you cannot [access a file parameter](https://github.com/addok/addok-csv/blob/master/addok_csv/__init__.py#L117) like a classic one with Falcon so we'll have to deal with `stream`

**Comment by davidbgk** [comment]
Or use [falcon-multipart](https://github.com/yohanboniface/falcon-multipart)? :)

**Comment by ThomasG77** [comment]
For "1. addok-csv plugin is probably not loaded on devapi, hence the current 404", I think it's more about the routing than csv plugin load.
When I run locally `addok serve`, I get"1. addok-csv plugin is probably not loaded on devapi, hence the current 404" is due to the addok-csv package hosted on pypi IMO.
I've adopted this process to confirm.

```
virtualenv venv --python=/usr/bin/python3.5
source venv/bin/activate
pip install git+https://github.com/addok/addok.git
pip install addok-fr addok-france addok-csv
```

I run the local server (I've skipped the redis data loading part)
```
addok serve
```

It returns
```
Loaded local config from /etc/addok/addok.conf
Addok loaded plugins: addok.shell, addok.http.base, addok.batch, addok.pairs, addok.fuzzy, addok.autocomplete, france, csv, fr
Serving HTTP on 127.0.0.1:7878…
```
So `addok-csv` is supposed to be loaded

Then, I make a post call using previous snippet on my local server and I get
```
127.0.0.1 - - [11/Mar/2017 22:39:18] "POST /search/csv/ HTTP/1.1" 404 0
```

Then, I do to fix the 404 issue
```
pip install -U git+https://github.com/addok/addok-csv.git
```

And I do again the same post call on my local server and I get
```
{ title: 'Missing file', description: 'Missing file' }
```

According to these tests, the issue "1. addok-csv plugin is probably not loaded on devapi, hence the current 404" is in the addok-csv package hosted on pypi.

I didn't investigate enough the "2."" at the moment about Falcon. Thanks for the pointer.

```
Loaded local config from /etc/addok/addok.conf
Addok loaded plugins: addok.shell, addok.http.base, addok.batch, addok.pairs, addok.fuzzy, addok.autocomplete, france, csv, fr
```

**Comment by davidbgk** [comment]
About 1., it might be related to https://github.com/addok/addok/issues/265 

About 2., I see where it can be fixed but I need to discuss about it with @yohanboniface on Monday

**Comment by yohanboniface** [comment]
> Or use falcon-multipart? :)

We should already be using it :)

> addok-csv plugin is probably not loaded on devapi, hence the current 404

It's installed, but I feel like addok and plugins are not at the same state (see https://github.com/addok/addok-csv/commit/38fd31720dfab1a7ca81f6dd2321af1825665c18 for example).

I suggest we release a rc-2 today, and upgrade properly dev instance.

**Comment by ThomasG77** [comment]
Can you ping on this thread whenever you release this rc-2?
I would like to try it when your release is out.
Thanks

**Comment by davidbgk** [comment]
RC2 is out! Test it while it's 🔥

**Comment by yohanboniface** [comment]
@ThomasG77 one important point, this plugin cannot be tested with `addok serve` for now. See https://github.com/yohanboniface/falcon-multipart/issues/1

We also added this warning in the plugin README.

**Comment by ThomasG77** [comment]
So Gunicorn or the tutorial recipe using Nginx like in the tutorial is OK? Just to be sure about my understanding.

**Comment by davidbgk** [comment]
See https://github.com/addok/addok/issues/300 too.

**Comment by khaliiiil** [comment]
Hi experts,

How I can execute the command that makes the CSV call:

http -f POST http://192.168.3.251:8080/search/csv/ columns='NRUE' columns='VILLE' data@/src/addok/CV.csv

I ran it on the Wwindows CMD and on the CentOS command prompt but this did not work!

Could you help me to solve this probleme ?

PS: I set up my own local Addok server.

Thank you very matche.

**Comment by yohanboniface** [comment]
@khaliiiil please open a new issue, and give more details than "this did not work" ;)

**Comment by khaliiiil** [comment]
@yohanboniface i'm sorry.

When i execute the commande on Windows i have that : 
![image](https://cloud.githubusercontent.com/assets/23399909/26260321/aef2333c-3cc4-11e7-9ef3-07be349c6332.png)

And when i execute the commande on linux i have that : 
![image](https://cloud.githubusercontent.com/assets/23399909/26260382/dd078196-3cc4-11e7-80e7-a67fc6275b45.png)

Can you help me to solve the probléme with that ?

Excuse my english :)

**Comment by yohanboniface** [comment]
Aucune idée pour Windows.
Pour CentOS: `yum install httpie`

**Comment by davidbgk** [comment]
https://httpie.org/doc#installation

**Comment by khaliiiil** [comment]
Merci d'abord pour votre réactivité.
En revanche, quand je lance cette commande :
 http -f POST http://localhost:8080/search/csv/ data@/src/addok/CV.csv
j'ai l'erreur suivante : 
![image](https://cloud.githubusercontent.com/assets/23399909/26302830/0cf8ea04-3ed5-11e7-865b-eb91b5eed791.png)

J'ai essayé quand même de changer l'affectation du paramètre "data" sur la commande :
![image](https://cloud.githubusercontent.com/assets/23399909/26302963/614e2b78-3ed5-11e7-9368-12263a932a56.png)

J'ai arraché les cheveux en essayant de passer une commande qui marche mais ceci ne marche pas.
Pourriez-vous svp m'aider à débloquer la situation ?

D'avance merci.

**Comment by yohanboniface** [comment]
> No such file or directory

Ça veut tout simplement dire que le fichier n'existe pas, ou du moins qu'il y a une erreur dans le chemin.
Au pif, remplacer `/src` par `/srv`?

**Comment by khaliiiil** [comment]
Oui en effet.
La commande marche nickel..merci énormément pour votre aide.

Bon début de semaine.
