### ISSUE TITLE
Comportement paradoxal de la recherche

### ISSUE THREAD

**Issue by parville** [addok/addok#296]
Si je recherche

_q=4_ **AVENUE EMILE**&citycode=76103, j'obtiens une réponse de type "street" car ADDOK ne connait pas de point de voie dans la seule voie qui correspond au critère épuré du numéro de voie;  ainsi il propose 

> **Avenue Émile** Verhaeren **76240 Bonsecours**".  🆗  

Si je recherche

q=**4** **EMILE**&citycode=76103,  j'obtiens _seulement_ deux réponses 

> **4** Rue Paul **Émile** Victor **76240 Bonsecours**
> **4** Square **Émile** Verhaeren **76240 Bonsecours**

Pour moi il manque la réponse de niveau street précédente, qu'un _**critère plus ciblé**_ sur le nom de voie permet paradoxalement de faire apparaitre. 

_Proposition_ : q=_4_ **EMILE**&citycode=76103,  devrait retourner 
>  **4** Rue Paul **Émile** Victor **76240 Bonsecours**
>  **4** Square **Émile** Verhaeren **76240 Bonsecours**
>  Avenue **Émile** Verhaeren **76240 Bonsecours**

Je ne pense pas que ce comportement soit à généraliser mais dans le cadre d'une recherche pour une commune ou un code postal précis, il me parait avoir du sens ?

**Comment by yohanboniface** [comment]
C'est effectivement pas très cohérent.

Le "problème" est que l'avenue n'a pas de numéro 4.

Voici en gros ce qu'il se passe:

- dans le cas de "4 avenue émile":
    - 4 et avenue sont éliminés, parce que trop fréquents dans l'index
    - pour ne pas chercher sur un seul terme (ce qui génère trop de bruit), "avenue" est repêché, parce qu'il est le moins fréquent des deux
    - l'avenue est trouvée, puisqu'elle contient à la fois "avenue" et "émile"

- dans le cas de "4 émile"
    - 4 est éliminé, parce que trop fréquent
    - … puis repêché pour ne pas laisser un seul mot comme critère
    - l'avenue n'est pas trouvée, puisqu'elle ne contient pas de numéro "4"

Une piste pour corriger ça proprement est de changer le critère de repêchage pour prendre en compte la présence d'un filtre (ici citycode), qui en général suffit à réduire le bruit.
