### ISSUE TITLE
Un cas sympa

### ISSUE THREAD

**Issue by parville** [addok/addok#298]
Recherche ( q=RUE%20D%20ELBEUF&citycode=76540 ) soit q=RUE D ELBEUF à ROUEN

La v1 propose la rue d'Elbeuf et le quai d'Elbeuf à Rouen.
La v2 propose ... le 112 D Rue D'Elbeuf ! 

On essaie de répondre seulement la Rue d'Elbeuf ?

**Comment by yohanboniface** [comment]
Je reproduis pas en local, donc ça veut certainement dire que c'est corrigé depuis la rc1.
A vérifier dès qu'on a mis à jour sur dev, très bientôt.

**Comment by yohanboniface** [comment]
Confirmé :)
