### ISSUE TITLE
La recherche par code postal renvoie des rues

### ISSUE THREAD

**Issue by fmassot** [addok/addok#314]
Ci-après un exemple avec le code postal 59000 <http://api-adresse.data.gouv.fr/search/?q=59000>. Je ne m'attendais plutôt au même comportement qu'une requête avec `q=lille` où on obtient une municipalité.

Merci !

Ex de résultats : 
{
  "limit": 5,
  "attribution": "BAN",
  "version": "draft",
  "licence": "ODbL 1.0",
  "query": "59000",
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "type": "Point",
        "coordinates": [
          3.059306,
          50.621478
        ]
      },
      "properties": {
        "citycode": "59350",
        "postcode": "59000",
        "name": "Boulevard Victor Hugo",
        "city": "Lille",
        "context": "59, Nord, Hauts-de-France (Nord-Pas-de-Calais)",
        "score": 0.6787545454545453,
        "label": "Boulevard Victor Hugo 59000 Lille",
        "id": "59350_9119_80b80a",
        "type": "street"
      },
      "type": "Feature"
    }
...
}

**Comment by frodrigo** [comment]
http://api-adresse.data.gouv.fr/search/?q=59000+Lille
Postalcode+City sill returns a street

**Comment by yohanboniface** [comment]
https://github.com/addok/addok-france/pull/6
