### ISSUE TITLE
Les codes postaux 0XXXXX ne sont pas trouvés

### ISSUE THREAD

**Issue by gdrouet** [addok/addok#318]
Addok retire les premiers zéros des codes postaux et ne les trouve plus dans la recherche : 

> http://ban.addok.xyz/search?q=37 RUE DE CROIX 02230 FRESNOY LE GRAND
> Résultat : Rue de Fresnoy 02110 Croix-Fonsomme

Le résultat est correct sur cette version : 

> http://api-adresse.data.gouv.fr/search/?q=37 RUE DE CROIX 02230 FRESNOY LE GRAND
> Résultat : 37 Rue de Croix 02230 Fresnoy-le-Grand

Discussion initiale : https://forum.etalab.gouv.fr/t/comprendre-la-raison-dun-resultat-avec-explain-addok/3513/5

**Comment by yohanboniface** [comment]
Aïe.
cf https://github.com/addok/addok/issues/119
