### ISSUE TITLE
Faubourg in search/csv

### ISSUE THREAD

**Issue by AlexisEidelman** [addok/addok#330]
All following rows are suprisingly matched with "Rue de Saint-Wandrille 76610 Le Havre" using serach/csv
They all have Faubourg in common.

                                libelle  codepostal  \
35     50 Rue Du Faubourg Poissonnière        75010   
332    89 Rue Du Faubourg Saint-Martin        75010   
333    224 Rue Du Faubourg Saint-Denis        75010   
334     86 Rue Du Faubourg Saint-Denis        75010   
335    186 Rue Du Faubourg Saint-Denis        75010   
339   214 Rue Du Faubourg Saint-Martin        75010   
347     79 Rue Du Faubourg Saint-Denis        75010   
348       57 Rue Du Faubourg Du Temple        75010   
353    150 Rue Du Faubourg Saint-Denis        75010   
357   215 Rue Du Faubourg Saint-Martin        75010   
370     61 Rue Du Faubourg Saint-Denis        75010   
374  34-36 Rue Du Faubourg Saint-Denis        75010   
375     36 Rue Du Faubourg Saint-Denis        75010   
377    149 Rue Du Faubourg Saint-Denis        75010   
381   255 Rue Du Faubourg Saint-Martin        75010   
387     67 Rue Du Faubourg Saint-Denis        75010   
390    44 Rue Du Faubourg Saint-Martin        75010   
399    46 Rue Du Faubourg Saint-Martin        75010   
402       41 Rue Du Faubourg Du Temple        75010   
403   164 Rue Du Faubourg Poissonnière        75010   
405   261 Rue Du Faubourg Saint-Martin        75010   
410    47 Rue Du Faubourg Saint-Martin        75010   
414       83 Rue Du Faubourg Du Temple        75010

**Comment by yohanboniface** [comment]
Can you provide a way to reproduce the issue?

```
http devapi-adresse.data.gouv.fr/search/ q=="50 Rue Du Faubourg Poissonnière 75010"
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 738
Content-Type: application/json; charset=utf-8
Date: Fri, 28 Apr 2017 10:49:25 GMT
Server: nginx/1.11.3
access-control-allow-headers: X-Requested-With
access-control-allow-origin: *

{
    "attribution": "BAN",
    "features": [
        {
            "geometry": {
                "coordinates": [
                    2.348081,
                    48.874449
                ],
                "type": "Point"
            },
            "id": "ADRNIVX_0000000270739827",
            "properties": {
                "_id": "wwyg1",
                "city": "Paris",
                "citycode": "75110",
                "context": "75, Paris, Île-de-France",
                "housenumber": "50",
                "id": "ADRNIVX_0000000270739827",
                "importance": 0.4281,
                "label": "50 Rue du Faubourg Poissonnière 75010 Paris",
                "name": "50 Rue du Faubourg Poissonnière",
                "postcode": "75010",
                "score": 0.8571,
                "street": "Rue du Faubourg Poissonnière",
                "type": "housenumber",
                "x": 652183.2,
                "y": 6864022.4
            },
            "type": "Feature"
        }
    ],
    "licence": "ODbL 1.0",
    "limit": 5,
    "query": "50 Rue Du Faubourg Poissonnière 75010",
    "type": "FeatureCollection",
    "version": "draft"
}
```

**Comment by AlexisEidelman** [comment]
My mistake. I sorry about that. I found source of the issue in my internal code. I sent a csv with wrong encoding...
I apologize about that !
