### ISSUE TITLE
Fails geocoding postalcode

### ISSUE THREAD

**Issue by frodrigo** [addok/addok#335]
On vanilla 1.0.0 install + plugin france and fr with BANO.
The postalcode are not taked into account.

```
$ addok shell --config ./default.py
Addok 1.0.0
Loaded local config from ./default.py
Loaded plugins:
addok.shell==1.0.0, addok.http.base==1.0.0, addok.batch==1.0.0, 
addok.pairs==1.0.0, addok.fuzzy==1.0.0, addok.autocomplete==1.0.0, 
france==1.0.0, fr==1.0.0, csv==1.0.0

 > 33000
9.6 ms — 1 run(s) — 0 results
```

**Comment by yohanboniface** [comment]
I'd guess the postcode is flagged as housenumber. I'll have a look tomorrow.

**Comment by yohanboniface** [comment]
So, digging a bit, it appears to only be a configuration issue. Seems you are using the default configuration, which, regarding the housenumber and postocode processing, is a bit dumb.

For full French postcode support you need to install addok-france package, plus replace default `flag_housenumber` by `addok_france.flag_housenumber` in `PROCESSORS_PYPATHS`.

See [the ubuntu tutorial](http://addok.readthedocs.io/en/latest/tutorial/) for a complete French ready configuration.

**Comment by frodrigo** [comment]
Ok. I miss the tutorial, and from the plugin doc is not enough. Maybe add a link from the plugin to the tutorial.
