### ISSUE TITLE
addok-france: duplicate label

### ISSUE THREAD

**Issue by frodrigo** [addok/addok#338]
`make_labels` of addok-france can produce duplicate labels:
- https://github.com/addok/addok-france/blob/master/addok_france/utils.py#L160
- ‎https://github.com/addok/addok-france/blob/master/addok_france/utils.py#L164-L165

**Comment by yohanboniface** [comment]
I think this is just an ugly piece of code :(
We were about to rewrite it, but just made more unittests to cover it for now.
Anyway, I'm not exactly sure what you are pointing at, but my guess is the repeating `label, city` lines: the trick is that the value of `label` has been changed between the calls.

**Comment by frodrigo** [comment]
You're right the label change.
