### ISSUE TITLE
Use strip_url_path_trailing_slash of new Falcon

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#354]
We want to be tolerant with trailing slash.

**Comment by yohanboniface** [comment]
Default value is True, which is good for us. Nothing to do.

**Comment by B1gG** [comment]
default is **False**
see the docs https://falcon.readthedocs.io/en/3.0.0b2/api/app.html?highlight=trail#falcon.RequestOptions.strip_url_path_trailing_slash
