### ISSUE TITLE
addok-trigrams plugin : no need to reindex ?

### ISSUE THREAD

**Issue by EtienneArbogast** [addok/addok#358]
Hi,
after installing addok-trigrams over latest Addok, and loading BAN database, the command "addok ngrams" returns an error. Anyway, requests returns correct values.
Is the indexing done during import time ?

**Comment by yohanboniface** [comment]
>  Is the indexing done during import time ?

Yes

> returns an error.

Which one? :)

**Comment by EtienneArbogast** [comment]
This one, indicating that "ngrams" is not an option :

`addok: error: argument : invalid choice: 'trigrams' (choose from 'shell', 'pyshell', 'serve', 'batch', 'reset')`

Maybe it's not an error but simply an indication. In this case, may I suggest to update the docs accordingly ?

**Comment by EtienneArbogast** [comment]
same error with `ngrams` and `trigrams` by the way.

**Comment by yohanboniface** [comment]
> This one, indicating that "ngrams" is not an option :

This one indicates that you are doing "addok trigrams" instead ;)

But you don't need to run "addok ngrams" when using the "addok-trigrams" pattern, ngrams are already computed in the core.

> Maybe it's not an error but simply an indication. In this case, may I suggest to update the docs accordingly ?

Yes, let's add in the `addok-trigrams` README this warning.
