### ISSUE TITLE
How to improve performance

### ISSUE THREAD

**Issue by EtienneArbogast** [addok/addok#359]
Hi,
the (excellent !) speakerdeck presentation (https://speakerdeck.com/yohanboniface/addok-presentation) talks about ~2000 requests per second on a 6-core machine.
My config reaches ~300 requests/s, when using batch csv geocoding, with only 1 core out of 32 working.
Any clue to improve that ? I'm using the gunicorn server.
A bit of jealousy in my question anyway ;-)

**Comment by cquest** [comment]
The CSV plugin is currently designed to process CSV files without parallelizing the gecoder backend in order not to overflow it to keep threads for non CSV geocoding.
You can split your CSV file and geocode them in parallel (that's how I measured the 2000 requests/s on our server).
You may reach a limit around 8 threads, as redis usually becomes the bottleneck around that level (redis in single threaded).

**Comment by EtienneArbogast** [comment]
Ok thanks for the parallelization suggestion, I'm going on that way.
As memory is not a limit, I use redis master & slaves functionality : 1 master and 3 slaves on the same database, which improves efficacity :-)
