### ISSUE TITLE
Pre and post scoring query processor

### ISSUE THREAD

**Issue by frodrigo** [addok/addok#366]
Sometimes we are able to clean the query in good way and with confidence. But the scoring is alway do on the original query.
The ability to score on a cleaned query with confidence can improve the score and the confidence on the result.
It's a feature request.

**Comment by yohanboniface** [comment]
Imho this cannot be done in a generic way, and it will ends with more magical scoring, so more unexpected results in edge cases, so I don't think it's a good idea to try to have this in the core.

But I understand there are totally valid scenarios where this may be an improvement.

So imho, the best option is to make a plugin for that: the scoring is made against [`helper.query`](https://github.com/addok/addok/blob/master/addok/helpers/results.py#L55), so just make a `SEARCH_RESULTS_PROCESSOR` that will change this value before scoring is computed (it then must be first in the `SEARCH_RESULTS_PROCESSORS_PYPATHS`).
