### ISSUE TITLE
Search requests working, Reverse requests not working

### ISSUE THREAD

**Issue by alfredott** [addok/addok#368]
Hello

I'm encountering a problem on my Addok server.

"search" requests do work properly. For example, "192.168.0.50/search/?q=paris" returns a page containing GeoJSON object. (normal behaviour)

However, "reverse" requests do not work. For example, "192.168.0.50/**reverse**/?lat=48&lon=2.5" returns the nginx "404 Not Found" page.

I have tried to restart uWSGI and nginx, empty and refill the Redis database, but the problem is persistent.

Does anyone know where it could come from ?

Edit: Typo

**Comment by yohanboniface** [comment]
> "192.168.0.50/search/?lat=48&lon=2.5"

192.168.0.50 **/reverse/** ?lat=48&lon=2.5

**Comment by alfredott** [comment]
Sorry I made a mistake on my post...

> However, "reverse" requests do not work. For example, "192.168.0.50/**reverse**/?lat=48&lon=2.5" returns the nginx "404 Not Found" page.

**Comment by alfredott** [comment]
Hello,

I solved my (silly) problem !
In the nginx.conf file, the "location" part pointed to "/search/" and not "/", leaving all URLs starting with "/reverse/" unknown.

I have no idea of why it was set that way.

Original (wrong) :-1: 
> location /search/ {
        uwsgi_pass  addok;
        include     /srv/addok/uwsgi_params;
    }

New (right) :+1: :
> location / {
        uwsgi_pass  addok;
        include     /srv/addok/uwsgi_params;
    }

Bye !
