### ISSUE TITLE
Empty result with missing leading zeros in zip code

### ISSUE THREAD

**Issue by jcoupey** [addok/addok#373]
First of all, many thanks for the work on this project!

I'm using the `https://api-adresse.data.gouv.fr/search/csv/` endpoint to geocode a bunch of places using the `postcode='my_column'` hint. I noticed quite a few empty results due to a "wrong" postcode where leading zeros had been automatically removed.

Examples: `1220,DIVONNE-LES-BAINS` doesn't work whereas `01220,DIVONNE-LES-BAINS` is perfectly fine. `03700,BELLERIVE-SUR-ALLIER` is ok but `3700,BELLERIVE-SUR-ALLIER` fails, etc.

As a workaround, I just scripted the addition of the missing leading zeros, but this seems like a fairly common situation (number display in spreadsheet, zip code extracted as a number from a DB). I don't know if it would make sense to filter those on your side at some point but I though it might be worth reporting.

**Comment by yohanboniface** [comment]
One solution may be to (optionally?) also index postcode without leading zero.

**Comment by yohanboniface** [comment]
@cquest do you think we should always strip leading zeros from postcodes, so 01234 will always be mapped to 1234 (during indexing AND search), and so both 01234 and 1234 will match?

**Comment by cquest** [comment]
Could it cause new problems with existing housenumbers... 1001 (housenumber or postcode ?)

**Comment by cquest** [comment]
Try to add missing leading 0 to broken postcodes in addok-france... 

something like re.sub(r' (\d{4}) ',' 0\1 ')

**Comment by cquest** [comment]
Pris en compte par https://github.com/addok/addok-france/blob/better_cleaning/addok_france/utils.py#L66
