### ISSUE TITLE
"RUE LE NAIN" indexée "RUE LENAIN" non trouvée

### ISSUE THREAD

**Issue by gdrouet** [addok/addok#376]
Dans un référentiel d'adresses utilisé pour Addok, la rue "LE NAIN" est écrite "LENAIN".
Voici ce que j'obtiens pour `/search?q=1 r le nain 02000 Laon`:

```json
{
  "properties": {
     "citycode": "02408",
      "score": 0.5272727272727272,
      "id": "53543a333533383800000000",
      "name": "1 RUE SAINT CYR",
      "label": "1 RUE SAINT CYR 02000 LAON",
      "context": "02, Aisne, Hauts-de-France",
      "city": "LAON",
      "street": "RUE SAINT CYR",
      "postcode": "02000",
      "type": "housenumber",
      "importance": 1,
      "housenumber": "1"
}
```
Est-ce un cas gérable ou la seule solution est-elle de corriger le référentiel ?

Plugins et version : `addok.shell==1.0.0, addok.http.base==1.0.0, addok.batch==1.0.0, addok.pairs==1.0.0, addok.fuzzy==1.0.0, addok.autocomplete==1.0.0, france==1.0.0, fr==1.0.0
`

**Comment by yohanboniface** [comment]
Oui, c'est un "edge case" qui est dans notre radar, voir https://github.com/addok/addok/issues/123

En résumé, en l'état, c'est pas géré.

Les options sont:
- utiliser addok-trigrams (mais je le considère pas production ready, donc pour l'instant je déconseille si t'es pas prêt à essuyer quelques plâtres)
- préparer les données pour avoir des alias là où il y a besoin (index plus gros), i.e. au lieu de `name=rue Lenain` avoir `name=["rue Lenain", "rue Le Nain"]`

Je ferme ici, on peut continuer à suivre ce problème via #123
