### ISSUE TITLE
Custom attribute

### ISSUE THREAD

**Issue by EtienneArbogast** [addok/addok#383]
Hi,
is it possible to add/retrieve a custom attribute at the housnumber level ?
For instance, in the French database BAN_odbl, housenumbers keys include and "id" attribute :
{"number":{"lat":"y.yy", "lon":"x.xx", "id":"ADRNIVX_nnnn"}}
I've tried to include "key": "id" in the FIELDS list, but can't get the value in the result json...
Any clue ?

**Comment by yohanboniface** [comment]
This should work out of the box, but it seems it's not.
I'll investigate.

**Comment by EtienneArbogast** [comment]
Thanks for investigating.
My example is not accurate : there are two "id" attributes in BAN, one at street level, and one at housenumbers level. In fact, "id" at street level is present in the returned json, which is ok.
To avoid id duplication, I modified the json file and the housenumbers dict is now like :
{"number":{"lat":"y.yy", "lon":"x.xx", "my_attr":"ADRNIVX_nnnn", "my_sec_attr":"whateverxxxx"}}
The question is about to have access to "my_attr" and "my_sec_attr" attributes within "housenumbers" dict...

**Comment by yohanboniface** [comment]
Custom fields in the housenumbers data should already been exported in the search results. Have you try it yet?

**Comment by EtienneArbogast** [comment]
You're right, it works out of the box.
My fault, I just added a {'key' : 'my_sec_attr'} in the FIELDS section of the config file and voilà !
Thx again for investigating.
