### ISSUE TITLE
Geocodage erronné

### ISSUE THREAD

**Issue by Renaud-G** [addok/addok#387]
Bonjour,

Je me permet de vous solliciter car j'ai des résultats très étranges avec addok et je ne comprend pas ce qui ne va pas.

Sur le site du gouvernement, j'obtiens toujours les bons résultat
Sur ma version en local, parfois ils sont bon mais pas toujours.

Voici un exemple de requête qui ne marche pas : 
http://*****/search/?q=1%20rue%20de%20la%20r%C3%A9publique%20brest

Sur le site du gouv, j'obtiens 

{"version": "draft", "features": [{"geometry": {"type": "Point", "coordinates": [-4.47847, 48.389266]}, "type": "Feature", "properties": {"id": "ADRNIVX_0000000266210199", "importance": 0.2977, "name": "1 Rue de la R\u00e9publique", "postcode": "29200", "housenumber": "1", "citycode": "29019", "x": 147183.4, "label": "1 Rue de la R\u00e9publique 29200 Brest", "y": 6836083.4, "street": "Rue de la R\u00e9publique", "context": "29, Finist\u00e8re, Bretagne", "type": "housenumber", "city": "Brest", "score": 0.9361545454545455}}], "licence": "ODbL 1.0", "attribution": "BAN", "query": "1 rue de la r\u00e9publique brest", "type": "FeatureCollection", "limit": 5}

Sur mon installation j'obtiens

{"type": "FeatureCollection", "limit": 5, "query": "1 rue de la r\u00e9publique brest", "attribution": "BAN", "licence": "ODbL", "features": [{"type": "Feature", "properties": {"type": "housenumber", "x": 871675.7, "context": "01, Ain, Auvergne-Rh\u00f4ne-Alpes (Rh\u00f4ne-Alpes)", "city": "Bourg-en-Bresse", "citycode": "01053", "label": "1 Rue de la R\u00e9publique 01000 Bourg-en-Bresse", "score": 0.6057666666666667, "y": 6569492.5, "importance": 0.3301, "postcode": "01000", "housenumber": "1", "street": "Rue de la R\u00e9publique", "name": "1 Rue de la R\u00e9publique", "id": "ADRNIVX_0000000285628979"}, "geometry": {"type": "Point", "coordinates": [5.226763, 46.203491]}}], "version": "draft"}

En précisant le code postal, obtient exactement le même résultat sur le site du gouv, mais pire en local :
search/?q=1%20rue%20de%20la%20r%C3%A9publique%20brest&postcode=29200

réponse en local ;
{"limit": 5, "filters": {"postcode": "29200"}, "licence": "ODbL", "features": [], "type": "FeatureCollection", "query": "1 rue de la r\u00e9publique brest", "version": "draft", "attribution": "BAN"}

En essayant une autre ville, par exemple Troyes, les deux me sortent les bonnes coordonnées.

Gouv.fr
{"version": "draft", "features": [{"geometry": {"type": "Point", "coordinates": [4.073997, 48.298162]}, "type": "Feature", "properties": {"id": "ADRNIVX_0000000265077649", "importance": 0.2818, "name": "1 Rue de la R\u00e9publique", "postcode": "10000", "housenumber": "1", "citycode": "10387", "x": 779645.1, "label": "1 Rue de la R\u00e9publique 10000 Troyes", "y": 6800301, "street": "Rue de la R\u00e9publique", "context": "10, Aube, Grand-Est (Champagne-Ardenne)", "type": "housenumber", "city": "Troyes", "score": 0.9347090909090909}}], "licence": "ODbL 1.0", "attribution": "BAN", "query": "1 rue de la r\u00e9publique troyes", "type": "FeatureCollection", "limit": 1}

Local
{"type": "FeatureCollection", "limit": 1, "query": "1 rue de la r\u00e9publique troyes", "attribution": "BAN", "licence": "ODbL", "features": [{"type": "Feature", "properties": {"type": "housenumber", "x": 779645.1, "context": "10, Aube, Grand-Est (Champagne-Ardenne)", "city": "Troyes", "citycode": "10387", "label": "1 Rue de la R\u00e9publique 10000 Troyes", "score": 0.6994149732620321, "y": 6800301, "importance": 0.2818, "postcode": "10000", "housenumber": "1", "street": "Rue de la R\u00e9publique", "name": "1 Rue de la R\u00e9publique", "id": "ADRNIVX_0000000265077649"}, "geometry": {"type": "Point", "coordinates": [4.073997, 48.298162]}}], "version": "draft"}

Pour l'install, j'ai suivi le tuto http://addok.readthedocs.io/en/latest/.
j'ai adapté le fichier de conf de base avec les paramètres indiqué dans le tuto.
[addok.conf.txt](https://github.com/addok/addok/files/1214921/addok.conf.txt)

Pour la base, j'ai pris la BAN et j'ai essayé différentes méthodes
- fichier complet
- quelques fichiers de départements (entre autre le 10 et le 29)
- fichier complet reconstitué à partir de la somme des départements.

J'obtient toujours le même résultat...

Auriez vous une idée?

En vous remerciant.

**Comment by yohanboniface** [comment]
Pour y voir un peu plus clair dans la configuration locale, le mieux est de ne mettre *que* les clés surchargées, c'est-à-dire pour une base France strictement ce qui est dans le tuto.

Ensuite revenez vers nous si ça marche toujours pas :)

**Comment by Renaud-G** [comment]
Merci pour la rapidité de la reponse.

Mes deux premières tentatives d'import ont été faite avec le fichier de conf comme indiqué dans le tuto.
Vu le manque de reussite, j'ai ensuite essayé en le complétant,  sans plus de succès. 
Je le remettre dans sa version initiale pour mes prochaines tentatives. 

Je suis en train de tenter d'importer un à un les fichier pour voir si c'est plus efficace.

J'aurais quelques questions: 
A quoi sert la commande addok ngrams
La base de donnée est elle stockée qu'en mémoire ou s'écrit elle sur le disque.
La machine ralentissant au fure et a mesure de l'import, je souhaiterais la reboot entre 2 imports. Cela aura t il un impact sur les imports déjà réalisés? Dois-je passer la commande sus-cité avant de reboot?

**Comment by yohanboniface** [comment]
>  A quoi sert la commande addok ngrams

A créer les ngrams :p
Ce sont les index qui permettent d'optimiser l'autocomplétion. Les ngrams, en l'occurrence dans notre cas des edge ngrams, ce sont les suites de lettres pour former le mot, par exemple: aut, auto, autoc, autoco, autocom, etc. Chaque ngram est asssocié au mot d'origine, ce qui nous permet de retrouver rapidement les différents candidats ensuite.

>  La base de donnée est elle stockée qu'en mémoire ou s'écrit elle sur le disque.

Les deux, mon capitaine! La base de données active est strictement en RAM. C'est une base Redis. Et Redis (par défaut, mais c'est possible de changer ce comportement, voir notamment http://addok.readthedocs.io/en/latest/redis/) va sauvegarder la base sur disque, pour pouvoir la remonter après un reboot ou un crash.

> La machine ralentissant au fure et a mesure de l'import

Ça sent le manque de RAM, ça. Combien de RAM disponible sur le serveur?

> je souhaiterais la reboot entre 2 imports. Cela aura t il un impact sur les imports déjà réalisés?

Avec le config par défaut de Redis, non, aucun, la base est remontée après reboot.

> Dois-je passer la commande sus-cité avant de reboot?

La commande ngrams ne doit être lancée qu'à la toute fin des imports. Ça n'a pas d'effet négatif de la lancer plusieurs fois, c'est juste pas optimal.

**Comment by Renaud-G** [comment]
Bonjour

Merci pour ces précisions. 

Pour la base  en mémoire/hdd, c'est bien ce que je pensais avoir compris avec la doc,  j'avais juste un doute.

Je suis reparti de zéro hier soir (réinstall d'ubuntu + addok). Apparemment, çà à résolu mon pb pour Brest, j'obtiens maintenant le bon résultat.
J'ai testé pas mal de villes, certains sont trouvées, d'autre non...  il semble me manquer tout les départements après le 59, excepté Paris, Lyon et quelques département d'outre mer.

J'ai trouvé une erreur dans les log redis : 
7488:M 11 Aug 02:59:47.104 # Can't save in background: fork: Cannot allocate memory

[redis-server.log.txt](https://github.com/addok/addok/files/1217046/redis-server.log.txt)

Effectivement, ca sens le manque de ram... je n'en ai hélas que 4Go sur cette machine pour le test. Pour compenser, j'ai ajouter un second fichier de swap, le tout sur un SSD, mais ca n'a pas l'air suffisant.

Est-ce que ca pourrait expliquer l'absence de certains données?
Quelle sont les quantité de ram et d'espace disque préconisées pour addok et la base/redis?
Rajouter encore du SWAP pourrait-il me permettre de faire une install de test fonctionnel? (je vais essayer)

**Comment by Renaud-G** [comment]
Rebonjour,

J'ai purgé tous, désactivé l'écriture sur le disque pour redis et augmenté très sérieusement le swap.

Résultat, Tout fonctionne maintenant.

J'ai comparé un fichier de 1000 lignes entre l'api du gouv et la version local. J'ai 21 différence seulement avec pour 80% d'entre elle seulement quelques mètres d'écart entre les deux coordonnées.

Je n'ai plus qu'a faire un installation propre sur une machine correctement dimensionnée

Encore merci pour votre aide :)
