### ISSUE TITLE
Absence de réponse pour une voie inconnue dans une commune connue

### ISSUE THREAD

**Issue by parville** [addok/addok#39]
Hello URL en échec
http://api.adresse.data.gouv.fr/search/?q=283%20rue%20saint%20exupery%2076170%20Lillebonne&lon=.537546682886993&lat=49.5209623388051&limit=3

Concerne donc 76170 Lillebonne

Merci

**Comment by parville** [comment]
76170 Lillebonne c'est BANO sinistré :-1:  mais ceci n'explique pas tout  :no_mouth: !

**Comment by parville** [comment]
Variante 

http://api.adresse.data.gouv.fr/search/?q=9%20ter%20route%20des%20hetres%2076280%20Vergetot&lon=.279131344891271&lat=49.6185145272349&limit=3

où cette fois *Vergetot* n'a pas de cadastre vectoriel.

**Comment by davidbgk** [comment]
Looks to be fixed by data. Please reopen if that's not the case.
