### ISSUE TITLE
unix socket

### ISSUE THREAD

**Issue by ffablia** [addok/addok#390]
Bonjour,
serait il possible d'ajouter la possibilité de se connecter à redis avec une socket unix ?
merci

-----
Hello,
Would it be possible to add the ability to connect to redis with a unix socket?
thank you

**Comment by yohanboniface** [comment]
Good point!
See #391 (yet to me reviewed, merged, released).

**Comment by ffablia** [comment]
J'ai survolé le patch, l'option unix_socket_path étant présent, j'en déduis qu'il répond parfaitement à la demande, merci
