### ISSUE TITLE
v1 moins rapide que v0.5

### ISSUE THREAD

**Issue by SansCostard** [addok/addok#399]
Je viens de faire un passage de v0.5 sous gunicorn vers la v1.0 sous nginx, en suivant le tuto de la doc, et j'ai de moins bonnes performances sur le même jeu de test.

V0.5, j'ai en moyenne 27 requêtes / secondes 
V1, j'ai en moyenne 25 requêtes / secondes

C'est quasi kiff kiff, mais du coup je vois pas l'intérêt de migrer.
Une idée de comment améliorer les perfs et m'approcher de ce que vous avez présenté ?
Je pensais qu'en passant de gunicorn à nginx, les perfs seraient meilleures.

**Comment by yohanboniface** [comment]
Tu peux en dire un peu plus sur:
- ta config (éventuellement la coller ici)
- ton jeu de données (France entière ou autre chose)
- ton serveur

Merci :)

**Comment by SansCostard** [comment]
MemTotal:       25Go
Architecture:          x86_64
Model name:            Intel(R) Xeon(R) CPU E5-2450L v2 @ 1.70GHz
Coeurs : 4
OS:    Debian GNU/Linux 8.9 (jessie)
Python: 3.4

Le jeu de données est la France entière (l'import a duré 4h, autant que pour la 0.5)

J'héberge tout sur redis. Pour ce qui est de la config des services, j'ai récupéré ceux de ton tuto.

**Comment by SansCostard** [comment]
J'ai l'impression que c'est le paramétrage de nginx ou uwsgi qui pose problème, je vais creuser de ce côté là...

**Comment by Laurent-Hervaud** [comment]
Bonjour, je m'intéresse également à la performance.
**Quelle infra faut-il pour atteindre 2000 requêtes / secondes comme mentionné sur le README ?**
Je suis actuellement à 25 requêtes / secondes avec cette infra :
 - vm cloud 2 cpu
 - 8Go RAM
 - debian 8
 - python 3.4
 - redis 3.2 (BAN France entière)
La saturation intervient au niveau du process uwsgi/python
Je vais creuser la solution Cython

**Comment by yohanboniface** [comment]
> vm cloud 2 cpu

Il faut plus de CPUs.

> 8Go RAM

Ça me paraît limite. Pas de swap constaté?

Aussi:
- utiliser une socket Unix pour Nginx=>uwsgi et python=>Redis aide.
- python 3.6 est un peu plus rapide
- si les documents sont dans une base sqlite, il faut un SSD

Note to myself: ajouter un page dédiée au fine tuning dans la doc.

**Comment by Laurent-Hervaud** [comment]
Un test avec 4 cpu et 16Go de RAM donne les mêmes performances (25 requêtes / secondes) :
 - pas de swap (Redis utilise que 5Go)
 - 1 seul CPU utilisé par uwsgi (le problème vient surement de la config uwsgi)

Le log /var/log/uwsgi/app/addok.log ne présente pas d'anomalie
Dans la conf uwsgi j'ai ajouté les paramètres suivants sans succès :
  enable-threads = true
  threads = 4

La conf complète :
```
[uwsgi]
uid = addok
gid = users
# Python related settings
# the base directory (full path)
chdir           = /srv/addok/
# Addok's wsgi module
module          = addok.http.wsgi
# the virtualenv (full path)
home            = /srv/addok/venv

# process-related settings
# master
master          = true
# maximum number of worker processes
processes       = 4
threads = 4
# the socket (use the full path to be safe
socket          = /srv/addok/uwsgi.sock
# ... with appropriate permissions - may be needed
chmod-socket    = 666
stats           = /srv/addok/stats.sock
# clear environment on exit
vacuum          = true
plugins         = python3

enable-threads = true
```

Je vais creuser la piste python3.6 mais cela ne changera pas à priori le nb de cpu utilisées

**Comment by Laurent-Hervaud** [comment]
J'ai trouvé la différence, il s'agit de la version de Redis. 
Redis 4.0.x permet d'obtenir des perf x10 avec l'api addok, soit 250 requêtes / secondes (fichier csv avec le plugin addok-csv).
On obtient ainsi la même perf que sur le serveur https://adresse.data.gouv.fr/ (idem avec docker https://github.com/etalab/addok-docker)

Pour information on obtient des perf identiques avec l'utilisation de uwsgi/nginx ou gunicorn
Redis arrive à saturation à partir de 8 cpu utilisées par le serveur http (traitement csv en parallèle)
Je n'ai pas observé de différence entre python 3.4 ou python 3.6

**Comment by EtienneArbogast** [comment]
Pour rebondir sur cette question de perfs, ok avec les conclusions de @Laurent-Hervaud sur les 250 requêtes/sec via le plugin addok-csv.
J'ai accès à une config plutôt musclée : 32 CPU Intel Xeon E5-2640 à 2.6GHz, 512Go de RAM, sur laquelle je ne suis pas le seul utilisateur.
En software : python 3.6 et redis 4.0, et la dernière version d'addok, accès via gunicorn.

J'ai pu booster les perfs en modifiant certaines configs :
- dans gunicorn : passage de 4 à 16 workers de type "sync" (donc pas de multithread),
- en python : parallélisation des appels à /search/csv, en utilisant le couple multiprocessing / requests. Je découpe la base à géocoder en chunks stockés provisoirement, et le géocodage de ces chunks se fait en parallèle avec 16 process,
- dans redis : comme effectivement redis chauffe un peu avec cette config, et que je n'ai pas de contrainte de RAM, une seconde instance de redis est lancée, configurée comme esclave de la première => double utilisation de la ram mais performances améliorées.

Avec ces tunings, le géocodage passe de 280 adresses/sec à 1400 adresses/sec, soit un gain de x5.1

**Comment by yohanboniface** [comment]
@cquest à l'occase tu pourrais mettre le détails de tes propres tests de perfs? Eventuellement j'en ferai une page de la doc ensuite.

**Comment by cquest** [comment]
Voici quelques infos sur la config du serveur en production pour api-adresse.data.gouv.fr :
- serveur sous Proxmox avec nginx dans le host qui réparti les requêtes sur deux containers et ajoute un peu de cache (utile pour les requêtes redondantes):
  - python 3.4
  - Redis 3.2.8
  - gunicorn avec 8 workers (sans plus de tuning)
  - stockage des data dans sqlite (addok-sqlitestore) pour économiser de la RAM

Ces deux instances indépendantes peuvent être ainsi stoppée l'une ou l'autre sans coupure du service.
Ceci nous permet de recharger/indexer la base chaque semaine.

Nous n'avons par ailleurs pas cherché à optimiser le géocodage de CSV, car ce serveur étant public, il serait trop facilement saturé par ces géocodages. Nous préférons laisser la priorité aux géocodages unitaires utilisés typiquement pour l'autocomplétion qui ont besoin de temps de réponse les plus courts possibles (les CSV peuvent patienter un peu).

Lors de la mise en place il y a 3 ans, nous avons fait des tests de charge en lançant plusieurs géocodages de fichiers CSV en paralèlle (avec parallel) et avions obtenu environ 2000 géocodages/s.

A partir de 8 threads, je confirme qu'addok sature Redis. Avoir deux instances dans deux containers permet aussi de mieux tirer parti des coeurs si ils sont plus nombreux.

Côté hardware:
- CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (6 coeurs physiques)
- 64 Go de RAM
- disques SSD (mais ceci n'influe quasiment pas pour addok qui ne fonctionne quasiment qu'en RAM)


Autre config... perso celle-là, ma "Tour Infernale":
- CPU: bi Xeon X5690 (donc 12 coeurs à 3.5GHz)
- 96 Go de RAM
- SSD pour la base sqlite

J'ai 4 instances d'addok dessus avec 5 bases différentes: BAN, BANO, POI d'OSM, extrait de SIRENE, une deuxième BAN France pour dev/test

Tout ça me sert à géocoder la base SIRENE chaque mois.

**Comment by cquest** [comment]
Retour au sujet de l'issue... @yohanboniface et moi testons actuellement d'importants changements dans le scoring des résultats. C'est en effet la partie qui prends en général le plus de temps.
Pour l'instant, les temps de traitement sont quasiment divisés par deux sur mes quelques tests.
Un bench plus complet permettra de savoir quel est le gain global final.

**Comment by cquest** [comment]
Premiers bench... environ 30 à 40% de temps gagné par la PR en cours... :)

**Comment by cquest** [comment]
Voici un résultat de bench sur un fichier départemental de la base SIRENE entre la v1.0.2 et ce qui ressemble fort à la prochaine.

On passe de 484s à 344s, soit 40% de moins.
L'essentiel est gagné dans le nouveau scoring des résultats qui prends 48s sur le total au lieu de 185s.

**Comment by TcaManager** [comment]
Très intéressant, vous auriez des liens vers les docs pour installer Addok+Nginx+Gunicorn par hasard? Auriez vous également des résultats de bench sur plus de 1 Million d'adresses? 10 Millions d'adresses? Avec le greffon CSV? D'avance merci.

**Comment by cquest** [comment]
L'installation pour cette partie est expliquée dans la doc:

https://addok.readthedocs.io/en/latest/tutorial/#configure-the-http-api

Pour gunicorn, voici un exemple de syntaxe:

gunicorn addok.http.wsgi -b 0.0.0.0:7878 -w 8 -D
