### ISSUE TITLE
Damned ! 

### ISSUE THREAD

**Issue by parville** [addok/addok#40]
On me propose une adresse _580 le baillage 76170 Ecrainville_ :zero:  addok est KO

Si je tente _le baillage 76170 Ecrainville_ :zero:  addok est toujours KO

Après avoir consulté http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#17/49.65028/0.31096 je tente le baill**i**age 76170 Ecrainville :+1: addok est OK

Du coup je tente _580_ le bailliage 76170 Ecrainville et là  :zero:  addok est KO.

Q1: baillage et bailliage ne peuvent-ils être équivalents ? 
Q2 : la dernière tentative ne devrait pas faire planter ?!
Merci

**Comment by yohanboniface** [comment]
Il y a trois problèmes combinés, et c'est un de trop:
- une faute sur "Bailliage"
- un numéro qui n'est pas dans les données connues (580 n'est pas dans BANO)
- un code postal qui ne correspond pas (en base, on a 76110)

Je vais voir si je peux bouger un peu le curseur, notamment en étant un peu moins strict sur les nombres.
