### ISSUE TITLE
Error when trying to geocode a malformed row w/ postcode

### ISSUE THREAD

**Issue by jdesboeufs** [addok/addok#400]
An adresse.data.gouv.fr user reported an issue when trying to geocode a CSV file with postcode option enabled.
I investigated and found one row was malformed (XML to CSV serialization issue).
But the geocoding succeed if the postcode option is disabled?!

To reproduce, just try to geocode this content with and without the postcode option.

```csv
addr;addr_more;postcode;city
4 RUE DU FRANC-COMTOIS;;12345;CITY ONE
56789;CITY TWO
```

Address construction: `addr` + `addr_more` + `postcode` + `city`
Postcode: `postcode`

Tell me if I can help! :)

**Comment by davidbgk** [comment]
Can you provide the URL you are hitting and the response you have?

**Comment by jdesboeufs** [comment]
https://api-adresse.data.gouv.fr/csv
I have a raw 500 Internal Server Error in plain text.

**Comment by yohanboniface** [comment]
Fixed with https://github.com/addok/addok-csv/pull/3 but not released yet.
addok-csv release is blocked by https://github.com/addok/addok/issues/397 (local work in progress, but IIRC this needs to switch out from CGI for form parsing).
