### ISSUE TITLE
Filtrer sur une propriété des housenumbers

### ISSUE THREAD

**Issue by krowix** [addok/addok#402]
Bonjour,

on veut ajouter un filtre possible de recherche qui se nomme sourcecode qui correspond au nom du fournisseur de la donnée d'adresse , un exemple : 
{"id":"31555_4219_315558402635","type":"street","name":"Passage de l'Europe","postcode":"31400","citycode":["31555"],"lon":1.484218,"lat":43.554212,"x":577481.5,"y":6273969.8,"population":440.2,"city":"Toulouse","context":"31, Haute-Garonne, Occitanie (Midi-Pyrenees)","importance":0.7695,"housenumbers":{"1":{"lat":43.554588,"lon":1.484543,"id":3155584026350001,"sourcecode":"MAIRIE","x":577508.5,"y":6274011.1},"3":{"lat":43.554865,"lon":1.484793,"id":3155584026350003,"sourcecode":"MAIRIE","x":577529.3,"y":6274041.5}}}

dans la configuration j'ai ajouté le champs dans les EXTRA_FIELDS et dans le FILTERS, j'ai passé un import.
Le filtre "sourcode" reste non operationnel.
Ai je manqué une étape ?

addok.conf 

QUERY_PROCESSORS_PYPATHS = [
   "addok.helpers.text.check_query_length",
   "addok_france.extract_address",
   "addok_france.clean_query",
   "addok_france.remove_leading_zeros",
]
SEARCH_RESULT_PROCESSORS_PYPATHS = [
   "addok.helpers.results.match_housenumber",
   "addok_france.make_labels",
   "addok.helpers.results.score_by_importance",
   "addok.helpers.results.score_by_autocomplete_distance",
   "addok.helpers.results.score_by_ngram_distance",
   "addok.helpers.results.score_by_geo_distance",
]
PROCESSORS_PYPATHS = [
   "addok.helpers.text.tokenize",
   "addok.helpers.text.normalize",
   "addok_france.glue_ordinal",
   "addok_france.fold_ordinal",
   "addok_france.flag_housenumber",
   "addok.helpers.text.synonymize",
   "addok_fr.phonemicize",
]
FIELDS = [
    {'key': 'name', 'boost': 4, 'null': False},
    {'key': 'street'},
    {'key': 'postcode',
     'boost': lambda doc: 1.2 if doc.get('type') == 'commune' else 1},
    {'key': 'city'},
    {'key': 'housenumbers'}
]
EXTRA_FIELDS = [
    {'key': 'citycode'},
    {'key': 'sourcecode'}
]

REDIS = {
    'host': 'localhost',
    'port': 6379,
    'db': 4
}
LOG_DIR = "/srv/addok/logs"
ATTRIBUTION = "SIG"
FILTERS = ["type","postcode","citycode","sourcecode"]
LICENCE = "N/A"
LOG_QUERIES = True
LOG_NOT_FOUND = True
SYNONYMS_PATH = "/etc/addok/synonyms.txt"

Merci d'avance de votre réponse

**Comment by Niarolf** [comment]
Bonjour Krowix,
est-ce que tu peux donner un extrait de tes données ?

**Comment by krowix** [comment]
[ban_extract.txt](https://github.com/addok/addok/files/1413489/ban_extract.txt)

**Comment by Niarolf** [comment]
"sourcecode" semble être dans les éléments de "housenumbers"  et non directement dans les premiers éléments. En remontant d'un niveau l'élément "sourcecode" ça devrait le faire.
Par contre je vois que tu as des crochets pour "citycode", est-ce que le filtre "citycode" fonctionne ?

**Comment by krowix** [comment]
malheureusement je mixe dans une même voie des numéros provenant de différentes sources que j'aimerai filtrer...
En ce qui concerne le citycode, c'etait une erreur de ma part.

**Comment by Niarolf** [comment]
A part filtrer dans le json de résultat je ne vois pas comment le moteur ADDOK pourrait filtrer à ce niveau, je laisse la main aux plus affutés.

**Comment by yohanboniface** [comment]
Je confirme: en l'état, il n'est pas possible de filtrer selon les propriétés des housenumbers.
Principalement parce qu'ils appartiennent tous au même "document" (la rue…).
Comportement pas évident à changer. Je vais y réfléchir, mais sans garantie.

**Comment by krowix** [comment]
Merci, ca serait interessant en effet ;-) car j'ai aussi cette difficulté pour le code postal et le cas particulier de Toulouse. En effet sur Toulouse on peut avoir pour une même rue partagée sur plusieurs code postaux. A l'heure actuelle le fait que cette propriété soit au niveau de la voie peut occasionner des incohérences.

**Comment by yohanboniface** [comment]
> A l'heure actuelle le fait que cette propriété soit au niveau de la voie peut occasionner des incohérences.

En effet.
Même si ça ne répond pas totalement au besoin exprimé ici, je précise à toutes fins utiles qu'il est possible d'avoir plusieurs valeurs pour une même clé, et donc par exemple avoir plusieurs codes postaux pour une même rue.

**Comment by krowix** [comment]
Merci pour vos réponses
