### ISSUE TITLE
Erreur geocodage

### ISSUE THREAD

**Issue by fchabouis** [addok/addok#404]
Bonjour,
Je me rends compte de certaines erreurs en utilisant l'API de adresse.gouv.fr.
Par exemple :
![image](https://user-images.githubusercontent.com/15341118/32098428-f82c3c20-bb0c-11e7-8213-40347797b6f3.png)

Le deuxième résultat (avenue de la corniche fleurie) a des coordonnées qui correspondent bien à la route du même nom.
Le premier en revanche nous indique un endroit où aucun route de ce nom n'existe apparement.

Je trouve régulièrement des erreurs de ce type. Ou dois-je les signaler, ou comment puis-je aider à les corriger ?

Merci

**Comment by jdesboeufs** [comment]
Bonjour,
Ce dépôt concerne le moteur de géocodage en lui-même.
Pour les questions concernant les données je vous suggère d'utiliser [le dépôt d'adresse.data.gouv.fr](https://github.com/etalab/adresse.data.gouv.fr).

**Comment by yohanboniface** [comment]
Merci.

**Comment by fchabouis** [comment]
J'ai resignalé l'erreur sur le dépot de adresse.data.gouv.fr
Merci.
