### ISSUE TITLE
effet collatéral des filtres

### ISSUE THREAD

**Issue by cquest** [addok/addok#410]
Cas étrange d'une adresse trouvée sans filtre:
http://api-adresse.data.gouv.fr/search/?q=6+CHEMIN+DE+KERSOLLES+22300+Lannion

Mais non trouvée avec les filtres comportant pourtant les bonnes valeurs:
http://api-adresse.data.gouv.fr/search/?q=6+CHEMIN+DE+KERSOLLES+22300+Lannion&postcode=22300
http://api-adresse.data.gouv.fr/search/?q=6+CHEMIN+DE+KERSOLLES+22300+Lannion&citycode=22113

**Comment by yohanboniface** [comment]
`Kersolles` vs `Kerzolles`, mais ça n'explique pas tout

**Comment by yohanboniface** [comment]
OK, dans l'index des pairs, la connexion n'est pas faite avec les filtres. Donc aucun candidat fuzzy n'est jamais trouvé.
Deux correctifs possibles:
- faire la connexion au moment de l'indexation (taille de l'index global plus "gros")
- au moment du calcul des candidats fuzzy, ne pas tenir compte des filtres, quitte donc à avoir des faux positifs, et donc à faire des requêtes inutiles derrière (requête plus "lente")

**Comment by yohanboniface** [comment]
(Vive le `EXPLAIN` :p )

**Comment by cquest** [comment]
Ceci semble fixé, je ferme.
