### ISSUE TITLE
addok-csv : fichier de conf pour préciser les champs à ajouter dans le geocoder.csv

### ISSUE THREAD

**Issue by Laurent-Hervaud** [addok/addok#416]
Il serait intéressant de pouvoir paramétrer pour le plugin addok-csv, la liste des champs à ajouter dans le csv résultat. 
Par exemple les coordonnées x et y en Lambert 93 ne sont pas présentent dans le csv alors qu'elles sont disponibles dans l'api via la commande search.

Aujourd'hui ces valeurs sont "en dur" dans le source addok-csv.
Elles pourraient être configurées dans un fichier addok.conf ou un fichier addok-csv.conf
Qu'en pensez-vous ?

**Comment by yohanboniface** [comment]
Oui bonne idée.
En utilisant une clé dédiée dans la conf addok, comme pour le reste, genre `CSV_HEADERS`, qui remplacerait cette ligne:

https://github.com/addok/addok-csv/blob/master/addok_csv/__init__.py#L176
