### ISSUE TITLE
PB avec mise à jour incrémentale

### ISSUE THREAD

**Issue by gdrouet** [addok/addok#426]
`_action` ne semble pas pris en compte.
J'ai le document suivant d'indexé :

```
{ "id" : "43543a313931393000000000", "type" : "municipality", "postcode" : "47160", "citycode" : "47320", "name" : "VILLEFRANCHE DU QUEYRAN", "context" : "47, Lot-et-Garonne, Nouvelle-Aquitaine", "importance" : 1, "population" : 0, "adm_weight" : 1, "lat" : 0, "lon" : 0 }
```

Je lance `addok batch` sur un fichier avec :

```
{"_action": "update", "id" : "43543a313931393000000000", "type" : "municipality", "postcode" : "47160", "citycode" : "47320", "name" : "VILLEFRANCHE DU QUERAN", "context" : "47, Lot-et-Garonne, Nouvelle-Aquitaine", "importance" : 1, "population" : 0, "adm_weight" : 1, "lat" : 0, "lon" : 0 }
```

J'ai supprimé le Y dans le nom de la ville.
Recherche avec `VILLEFRANCHE DU QUERAN` ok : 

```
{
  "id": "43543a313931393000000000",
  "importance": 1,
  "postcode": "47160",
  "_action": "update",
  "label": "VILLEFRANCHE DU QUERAN",
  "adm_weight": 1,
  "context": "47, Lot-et-Garonne, Nouvelle-Aquitaine",
  " score": 1,
  "citycode": "47320",
  "type": "municipality",
  "name": "VILLEFRANCHE DU QUERAN"
}
```

Recherche avec `VILLEFRANCHE DU QUEYRAN` ko :

```json
{
  "id": "43543a313931393000000000",
  "importance": 1,
  "postcode": "47160",
  "label": "VILLEFRANCHE DU QUEYRAN",
  "adm_weight": 1,
  "context": "47, Lot-et-Garonne, Nouvelle-Aquitaine",
  "score": 1,
  "citycode": "47320",
  "type": "municipality",
  "name": "VILLEFRANCHE DU QUEYRAN"
}
```
L'ancienne version n'est pas désindexée, de même quand je fais `"_action": "delete"`.

**Comment by yohanboniface** [comment]
Humm, depuis #307, c'est `_id` qui a valeur d'identifiant interne, `id` étant considéré non significatif et à usage métier seulement.
#307 était motivé par la réduction de la taille des ids pour réduire la taille des indexes (les ids sont beaucoup utilisés).
Du coup, pour qu'un update ou delete soit opérationnel, il faut passer la clé `_id` qui va bien. Le scénario étant dans ce cas de totalement contrôler `_id`, y compris à l'indexation initiale.

Avec le recul, je me rends compte que c'est pas le meilleur comportement par défaut. Peut-être avoir un flag dans la config pour utiliser des ids internes, et sinon utiliser `id` (comme avant)? Ou un batch processor optionnel à ajouter en début de chaîne qui supprime `id` s'il est présent et donc obligera Addok à la recréer (plus court)? Ou bien une clé de config permettant de définir la clé à utiliser pour identifiant?

cc @davidbgk @cquest

**Comment by gdrouet** [comment]
Ok merci pour la précision.
Pas d'impact si je déclare _id et id avec la même valeur donc. Mes utilisateurs ont besoin de continuer à trouver "id" sinon c'est un breaking change, or c'est cette valeur que je dois utiliser pour mes diffs.

**Comment by yohanboniface** [comment]
> Pas d'impact si je déclare _id et id avec la même valeur donc.

Si tu as la main sur la génération des données, c'est le mieux à faire (mais ton index va grossir un poil ;) )

**Comment by gdrouet** [comment]
Oui j'ai la main sur toute la chaîne 😎 merci

**Comment by gdrouet** [comment]
J'ai fais un test rapide :

```
> GET 6Ko7l
type municipality
_id 6Ko7l
adm_weight 1
name VILLEFRANCHE DU QUEYRAN
postcode 47160
lon 0
id 43543a313931393000000000
context 47, Lot-et-Garonne, Nouvelle-Aquitaine
lat 0
population 0
importance 1
citycode 47320
```

```
cat test-diff-.json 
{ "_action": "delete", "_id" : "6Ko71" }
```

```
addok batch test-diff-.json 
```

`GET 6Ko7l` me retourne toujours le document.

Qu'est-ce qui m'échappe ?

**Comment by cquest** [comment]
id n'est pas indexé à ce qu'il me semble...donc pour les update/delete c'est compliqué !

Je pense que si on veut faire des update/delete (cas peu courant actuellement), ça sera au prix d'un peu d'espace en plus, c'est à dire en fournissant soit même _id dans les données.

**Comment by gdrouet** [comment]
Je confirme que ça fonctionne bien en indexant d'abord avec un `_id` spécifié.
Pas de problème majeur de mon côté, l'issue peut être clôturée.
