### ISSUE TITLE
Geocoder PHP provider

### ISSUE THREAD

**Issue by jbelien** [addok/addok#428]
Hello guys,

This is not an issue ! I just wanted to let you know I developped a provider to Addok for [Geocoder PHP](https://github.com/geocoder-php/Geocoder) project : <https://github.com/geo6/geocoder-php-addok-provider> 🎉 

As already discussed with @cquest I plan on using Addok for Belgian addresses, so it was a good time to implement Addok provider for Geocoder PHP :)

Keep on the good work ! \o/

**EDIT :** [PR #818](https://github.com/geocoder-php/Geocoder/pull/818) waiting to be merged !

**Comment by yohanboniface** [comment]
Cool, thanks for the work, and for letting us know :)

Should we have a page in the documentation to list related tools like this?

**Comment by jbelien** [comment]
I think we can close this (non) issue.

[Addok Geocoder PHP provider](https://github.com/geo6/geocoder-php-addok-provider) has already been installed 3000+ times. 🎉
