### ISSUE TITLE
curl or wget synthax for /search/csv

### ISSUE THREAD

**Issue by krowix** [addok/addok#429]
hi ,
have anyone ever use "wget" or "curl" in order to query the API / search / csv / ?

a syntax would help me ;-)

thx in advance

**Comment by Niarolf** [comment]
Hi,
you can use httpie on command line.
For search/csv you can concat on 1 column the adresse and use this command line : 
http -f --timeout 120 POST http://<IP-Address>/search/csv?encoding=UTF-8 columns='<the_column_name>' data@/path/to/your/file.csv > path/to/you/result/file.csv

**Comment by krowix** [comment]
Thanks for the answer. i've read api docs but httpie is not a known tool of my department and it imposes me curl or wget ...

**Comment by jbelien** [comment]
Something like this should work !

```
curl -v -X POST -H "Content-Type: text/csv" --data-binary @in.csv http://ip/search/csv?encoding=UTF-8 > out.csv
```

**Comment by krowix** [comment]
```
curl -k -X POST -H "Content-Type: text/csv" --data-binary @temp.csv https://api-adresse.data.gouv.fr/search/csv?encoding=UTF-8
```

--> return : 

`{"title": "Missing file", "description": "Missing file"}`

i'v tried with form-data, extract command from chrome debug... nothing work. altought httpie work fine.
it will be easier to preach httpie to the department

**Comment by izno33** [comment]
This command line works for me :

    curl -X POST -F data=@file.csv https://api-adresse.data.gouv.fr/search/csv/ -F columns=adr1 -F columns=adr2 > file.out.csv

**Comment by jdesboeufs** [comment]
We have updated our instance documentation (French only):
https://adresse.data.gouv.fr/api

We switched to `curl` to touch a wider audience.
