### ISSUE TITLE
Multiple instance

### ISSUE THREAD

**Issue by jbelien** [addok/addok#432]
I'm quite a noob with Python ;
What would be the best (and/or easiest way) to configure 2 instances of Addok on the same server ?

I followed your tutorial (http://addok.readthedocs.io/en/latest/tutorial/) to install it.

The idea would be to have one instance that deals with French addresses and one instance that deals with Dutch addresses with each one having its own plugins (`addok-fr` for French addresses for instance).
French instance would be called with http://fr.addok.geocode.be/ and Dutch instance with http://nl.addok.geocode.be/ something like that.

Thanks for your help :)

**Comment by yohanboniface** [comment]
Basically the call chain is: domain/path => nginx => gunicorn/uwsgi => addok (python)

So what you need is two different gunicorn/uwsgi processes with their own configuration, that exposes their own socket/port, and nginx redirecting to one or the other depending on the subdomain.

Each addok must of course have its own configuration file, so this needs also be set in the gunicorn/uwsgi conf using the `ADDOK_CONFIG_MODULE` env var.

Does that help or should I go into more details? :)

PS: you also may want to deploy each of you instances in different VMs or containers (still with nginx doing the routing from the host), depending on how geek you are and how much you like lasagne ;)

**Comment by jbelien** [comment]
Awesome, I'll have a look at it and come back if I struggle !

Thanks a lot :)

**Comment by cquest** [comment]
What is your goal ?

Increase addok maximum request/s throuput ?
Have two different indexed databases ?

For performance increase, redis is the limiting factor and may need to be instanced more than once, and then two addok instance can rely on each redis. I'm doing that using containers. Each one has addok, redis and gunicorn (or uwsgi) and is queried by nginx running is the host (outside the container).

For multiple databases, here is the setup I have at home:
- one redis
- multiple addok config files, each using a different redis database, and served by gunicorn listening on a different port

You can also do both at the same time. All this is not directly python related.

**Comment by jbelien** [comment]
Hello @cquest ,

My goal is to use Addok for the Belgian addresses.
We have addresses in French and addresses in Dutch, so I will create two Addok instances with their own config files (`addok-fr` for the instance handling the French addresses, `addok-nl` for the instance handling the Dutch addresses for instance).
