### ISSUE TITLE
Mont xxx / montxxx - val xxx / valxxx, etc...

### ISSUE THREAD

**Issue by cquest** [addok/addok#434]
Ce type de variation est courant.

N'est-il pas possible de générer des tokens supplémentaires servant d'alias (même principe que F F I > FFI) ?

MONT MACHIN -> MONT MACHIN MONTMACHIN
MONTMACHIN-> MONTMACHIN MONT MACHIN

Exemple réel:

103 Le Mont Griffon 60110 Amblainville
103 Rue Montgriffon 60110 Amblainville

**Comment by yohanboniface** [comment]
=> #123 :)
