### ISSUE TITLE
https://adresse.data.gouv.fr SSL certificate is expired

### ISSUE THREAD

**Issue by vinyll** [addok/addok#436]
https://adresse.data.gouv.fr/ renders an _Insecure Connection_ error

**Comment by yohanboniface** [comment]
It's another team at https://github.com/etalab/adresse.data.gouv.fr :p
But I'm passing the word to the guy working in front of me right now :)

**Comment by jdesboeufs** [comment]
We were switching between 2 servers and Let's Encrypt requires DNS records to be propagated to attach a domain to  an existing certificate ;)
