### ISSUE TITLE
Erreur restart uWSGI

### ISSUE THREAD

**Issue by cv3009** [addok/addok#441]
Bonjour ! 
 
Je me permet de venir poster ici car je rencontre un p'tit problème qui me rend un peu fou et dont je n'arrive pas vraiment à déterminer la cause. 
Pour un projet perso, je cheche à installer addok sur une machine virtuelle ubuntu 14.04. 
J'ai suivi scrupuleusement le tuto d'installation et et addok fonctionne niquel via le shell.
La ou ça coince pour moi, c'est lors de la mise en place de l'api http et du serveur http.
Comme je ne reussi pas à acceder à l'api http via le port 7878 de la machine en local (j'imagine que je dois avoir un problème de redirections Port hote/port invité), je me suis décidé à installer le serveur http.
En redémarrant le serveur uWSGI que j'm'obtiens une erreur de ce type :
> Job for uwsgi.service failed because the control process exited with error code.

Et quand j'execute un systemctl status uwsgi.status j'obtiens : 
```
uwsgi.service - LSB Start/Stop uWsgi server instance 
Loaded: loaded (/etc/init.d/uwsgi; bad; vendor preset: enabled)
Active: failed (Result: exist-code) since mer 2018-02-28 11:15:49 CET; 9s ago
Docs: man:systemd-sysv-generator(8)
Process: 2270 ExecStart=/etc/init.d/uwsgi start (code=exited, status=1/FAILURE)

```

**Comment by yohanboniface** [comment]
Y a quoi dans `/var/log/uwsgi/addok.log` ?

**Comment by cv3009** [comment]
Euh rien du tout, aucun fichier de créer.
J'imagine que ça veut dire que j'ai du louper quelque chose dans mon installation, non?

**Comment by yohanboniface** [comment]
> Comme je ne reussi pas à acceder à l'api http via le port 7878 de la machine en local (j'imagine que je dois avoir un problème de redirections Port hote/port invité), je me suis décidé à installer le serveur http.

Par défaut, il n'écoute que sur localhost, essaie: addok serve --host 0.0.0.0
(Ou l'IP de la machine sur le réseau local.)

>  J'imagine que ça veut dire que j'ai du louper quelque chose dans mon installation, non?

Non, moi qui t'ai filé un mauvais chemin, essaie `/var/log/uwsgi/app/addok.log`

**Comment by cv3009** [comment]
>  Par défaut, il n'écoute que sur localhost, essaie: addok serve --host 0.0.0.0
>  (Ou l'IP de la machine sur le réseau local.)

Ah super, merci, ça a résolu mon premier problème !  (Je suis definitivement pas familier avec la config reseau).

Yes, effectivement, je l'ai bien trouvé ! Voila ce qu'il contient :

> Thu Mar 1 1614:24 2018 - *** Starting uWSGI 2.0.12-debian (64bits) on [Thu Mar 1 16:14:24 2018]
> Thu Mar 1 1614:24 2018 - compiled with version: 5.4.0.20160609 on 31 August 2017 21:02:04
> Thu Mar 1 1614:24 2018 - os: Linux-4.4.0.87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017
> Thu Mar 1 1614:24 2018 - nodename: ubuntu
> Thu Mar 1 1614:24 2018 - machine: x86_64
> Thu Mar 1 1614:24 2018 - clok source: unix
> Thu Mar 1 1614:24 2018 - pcre jit disabled
> Thu Mar 1 1614:24 2018 - detected number of CPU cores: 1
> Thu Mar 1 1614:24 2018 - current working directory: /
> Thu Mar 1 1614:24 2018 - writing pidfile to /run/uwsgi/app/addok/pid 
> Thu Mar 1 1614:24 2018 - open("/run/uwsgi/app/addok/pid"): No such file or directory  [core/utils.$utils.c line 3588]

**Comment by yohanboniface** [comment]
> open("/run/uwsgi/app/addok/pid"): No such file or directory

Ça ressemble à une histoire de droits d'accès et/ou de dossier manquant. Difficile à débugguer à distance. Avec quel user lances-tu uwsgi? Si je dis pas de bêtises, il faut le lancer avec root, qui va ensuite lancer les process avec les user/group configurés dans les  .ini.

**Comment by cv3009** [comment]
Yep, c'est ce que je me suis dit aussi.
Comme dit dans la doc, je le lance systématiquement en root.
Mais je me demande si j'ai pas fait un erreur durant l'installation en utilisant un mauvais user lors de la création des fichiers de config, ce qui empercherait le fonctionnement du service par la suite. 
Je vais pas couper à une réinstallation propre à mon avis.
Merci beaucoup pour l'aide en tout cas !

**Comment by cv3009** [comment]
Bon bah le problème venait bien des droits d'accès.
J'avais, pour gagner du temps, crée les fichiers de config sur windows avec le notepad et un copier coller de la doc pour les envoyer ensuite sur ma machine virtuelle via le ftp.
J'imagine que c'est la création de ces fichiers de façon externe sans leur réattribuer les bons droits lors de l'import qui a généré mon problème. 
En réinstallant proprement tout, j'ai, cette fois, crée les fichiers directement sur ubuntu avec nano et l'user addok. Ça a réglé le problème et tout fonctionne parfaitement !
Merci encore pour l'aide !

**Comment by yohanboniface** [comment]
Cool, tant mieux :)
