### ISSUE TITLE
Mise à jour de la documentation

### ISSUE THREAD

**Issue by FabriceSalvaire** [addok/addok#445]
**Tout d'abord un grand merci à Etalab pour ce logiciel !**

https://adresse.data.gouv.fr ne mentionne pas ce dépôt c'est dommage.

Préciser : 
```
DOCUMENT_STORE_PYPATH = 'addok_psql_store.PSQLStore'
```

Ceci semble obsolète :

```
SEARCH_RESULT_PROCESSORS_PYPATHS = [
    #! "addok.helpers.results.score_by_str_distance",
    #! "addok.helpers.results.adjust_scores",

addok ngrams
```

> addok-trigrams: alternative index algorithm based on trigrams.

C'est en production ou bien c'est expérimental ?

Cet exemple plante :

```
> AUTOCOMPLETE lil
Traceback (most recent call last):
  File "/usr/lib64/python3.6/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'Cmd' object has no attribute 'do_AUTOCOMPLETE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/opt/python-virtual-env/py36/bin/addok", line 11, in <module>
    sys.exit(main())
  File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/addok/bin/__init__.py", line 30, in main
    args.func(args)
  File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/addok/shell.py", line 478, in invoke
    cmd.loop()
  File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/addok/shell.py", line 74, in loop
    self.cmdloop()
  File "/usr/lib64/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python3.6/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/addok/shell.py", line 66, in default
    return self.do_SEARCH(line)
  File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/addok/shell.py", line 196, in do_SEARCH
    self._search(query)
  File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/addok/shell.py", line 147, in _search
    autocomplete = bool(int(autocomplete))
ValueError: invalid literal for int() with base 10: 'lil'
```

**Comment by yohanboniface** [comment]
> Tout d'abord un grand merci à Etalab pour ce logiciel !

:)

> Préciser :
DOCUMENT_STORE_PYPATH = 'addok_psql_store.PSQLStore'

Humm, c'est pas le store par défaut, ou alors je rate quelque chose sur la remarque?

> Ceci semble obsolète :

En fait, c'est l'inverse, c'est dans le master (1.1.0-rc1) mais pas dans la version stable releasée, mais la doc est à jour sur le master. Je vais voir comment améliorer le workflow pour éviter cette désynchronisation.

> addok-trigrams: alternative index algorithm based on trigrams.
> C'est en production ou bien c'est expérimental ?

Ce n'est pas en production, et c'est plutôt expérimental. Je voudrais mettre plus d'énergie dessus parce que je considère que c'est un algo très prometteur (il permet de s'affranchir des spécificités de la langue, et donc facilite une gestion multilingue), mais j'ai pas de visibilité pour l'instant.
Si vous faites des tests avec et avez des retours, je regarderai.

> Cet exemple plante :

Je reproduis pas. C'est pas la dernière stable ou la version master?
Est-ce que le plugin "autocomplete" est désactivé (ce qui est le cas quand on utilise addok-trigram) ?

**Comment by FabriceSalvaire** [comment]
pg : c'est pour clarifier la doc du plugin, par ailleurs j'ai vu que redis est quand même nécessaire, c'est juste un cache sur pg ?

---

addok 1.0.2 avec 

```
    'addok.helpers.results.score_by_autocomplete_distance',
    'addok.autocomplete.EdgeNgramIndexer',
```

---

Quid de versionner les fichiers json sous git pour faire une update sans télécharger régulièrement 500 Mo ?

**Comment by yohanboniface** [comment]
> pg : c'est pour clarifier la doc du plugin, par ailleurs j'ai vu que redis est quand même nécessaire, c'est juste un cache sur pg ?

Le store c'est uniquement pour les documents eux-mêmes, les index sont dans Redis dans tous les cas.

> Quid de versionner les fichiers json sous git pour faire une update sans télécharger régulièrement 500 Mo ?

C'est une question pour https://github.com/etalab/ban-data/ :)
