### ISSUE TITLE
86-92 rue Camille Desmoulins Issy les moulineaux

### ISSUE THREAD

**Issue by cquest** [addok/addok#45]
Rend un résultat à la rue, alors que le 86 est bien présent dans les données BAN (à tester sur devban).

**Comment by yohanboniface** [comment]
Humm, je suis pas sûr de comprendre sur quel env tu testes, idem pour #46.

Sur BANO, j'ai:
```
> 86-92 rue Camille Desmoulins Issy les moulineaux
92 Rue Camille Desmoulins 92130 Issy-les-Moulineaux (920401410N | 0.8158951048951049)
```

**Comment by cquest** [comment]
A tester sur devban... sur la VM 101 de rat

**Comment by yohanboniface** [comment]
Haaaan, j'ai compis maintenant ce que tu entendais par "à tester sur devban" :)

**Comment by yohanboniface** [comment]
En fait, «86-» est considéré comme du bruit, et c'est «92 rue Camille Desmoulins Issy les moulineaux» qui est extrait comme chaîne à chercher.
Je suis pas sûr qu'on puisse être beaucoup plus fin, et si le 92 ne manquait pas dans les données on aurait un résultat satisfaisant.

**Comment by cquest** [comment]
Il y a bien un moyen de ne pas classer le "86-" comme bruit... non ?
Des adresses de ce type XX-YY on va en retrouver assez régulièrement.

**Comment by davidbgk** [comment]
Edge case, now that we have the 92 within data we can find it:
http://api.adresse.data.gouv.fr/search/?q=86-92%20rue%20Camille%20Desmoulins%20Issy%20les%20moulineaux
