### ISSUE TITLE
Impossible d'interroger l'API avec un citycode en Corse du Nord (2B)

### ISSUE THREAD

**Issue by Laurent-Hervaud** [addok/addok#455]
Pour retourner un candidat "municipality" via son code INSEE, j'utilise les paramètres suivants :
`curl https://api-adresse.data.gouv.fr/search/?q=<code INSEE>&citycode=<code INSEE>&type=municipality`

Exemple pour Bordeaux (résultat OK) :
`curl https://api-adresse.data.gouv.fr/search/?q=33063&citycode=33063&type=municipality`

Pour les codes INSEE de Corse du Nord (2B), cela ne ramène aucun candidat, exemple pour Bastia :
'curl https://api-adresse.data.gouv.fr/search/?q=2B033&citycode=2B033&type=municipality`

Alors que cela fonctionne bien pour Ajaccio :
'curl https://api-adresse.data.gouv.fr/search/?q=2A004&citycode=2A004&type=municipality`

Je soupçonne une transformation du 2B en 2 BIS ...

**Comment by jdesboeufs** [comment]
Bonjour,

Pour ce type de recherche je vous conseille d’utiliser l’API Géo :

https://geo.api.gouv.fr

Le lun. 28 mai 2018 à 17:41, Laurent Hervaud <notifications@github.com> a
écrit :

**Comment by yohanboniface** [comment]
@Laurent-Hervaud merci pour le retour.
Après une rapide enquête: le citycode n'est jamais utilisé pour constuire les labels dans l'étape du scoring, donc le document est élimité pour cause de score trop faible.
Avec la 1.1 ce sera corrigé.
Faut que j'active la release :)

**Comment by Laurent-Hervaud** [comment]
Il pourrait être intéressant également de pouvoir interroger l'API via l'id présent dans la BAN afin de récupérer des informations post géocodage (fantoir, ...) sans avoir à stocker toutes les info dans sa base métier

**Comment by Laurent-Hervaud** [comment]
En ajoutant dans la conf le paramètre MIN_SCORE = 0.05,
les requêtes search/?q=2B033&citycode=2B033&type=municipality remontent bien le résultat attendu

Merci @yohanboniface pour la piste du score trop faible

**Comment by yohanboniface** [comment]
Plaisir! :)
J'essaie de me bouger et de bouger @cquest pour enfin finaliser la 1.1, qui corrige au passage ce souci.
