### ISSUE TITLE
Présence de nom de lieu-dit qui empêche de trouver l'adresse (sans ce nom)

### ISSUE THREAD

**Issue by cquest** [addok/addok#46]
Exemple: 5 chemin du caribouillé, sarrigny 89110 poilly sur tholon (BAN)

Pas trouvé par addok dans BAN à cause du nom du lieu dit (Sarrigny)
Si on le retire, l'adresse est trouvée.

Identique pour:
9 chemin du ravillon, auvergne 89110 poilly sur tholon

**Comment by yohanboniface** [comment]
On a deux documents on dirait:
```
Chemin du Caribouille, SARRIGNY 89110 Poilly-sur-Tholon (89304_B231_dd596aaa | 0.8763694214876032)
5 Chemin du Caribouille 89110 Poilly-sur-Tholon (89304_0020_dac76055 | 0.9096909090909091)
```

**Comment by cquest** [comment]
Oui, il y en a deux (problème d'homogénéité dans les données de référence)... difficile à compenser en aval, sauf si on favorise une réponse housenumber à une réponse street/locality.
Pas évident à gérer, les effets de bords potentiels sont élevé...

**Comment by davidbgk** [comment]
Requires too much data/user testing to find the perfect combination between accuracy and noise. Data look to be fixed for that exact case though.
