### ISSUE TITLE
Reverse geocoding limit

### ISSUE THREAD

**Issue by rmaziere** [addok/addok#461]
Bonjour,

Je voudrais savoir s'il y a une limite de distance dans la fonction de reverse geocoding.
Quelle est-elle ? Et s'il est possible d'en surcharger une en paramètre lors de l'appel de l'api ?

Merci

**Comment by yohanboniface** [comment]
Non, ce n'est pas possible de changer la précision au moment de l'appel.

Ton besoin, c'est de l'étendre ou de la réduire?

En l'état, le reverse regarde dans le geohash du point et dans les geohashs voisins. Pour étendre la recherche, on pourrait éventuellement ajouter un paramètre pour élargir aux voisins des voisins, mais dans certains zones denses ça peut coûter cher. Éventuellement le faire optionnellement si rien n'est trouvé dans le premier cercle (c'est déjà le cas aujourd'hui: on ne regarde chez les voisins que si rien n'est trouvé dans le geohash d'origine).

Note: il est possible de configurer la précision par instance d'Addok en modifiant le paramètre `GEOHASH_PRECISION`.

**Comment by rmaziere** [comment]
En fait, mon besoin est de savoir ce qui est fait exactement.
S'il recherche le plus proche sans limite de distance ou avec une limite.
Car je ne veux pas un résultat à tout prix.

**Comment by cquest** [comment]
Le reverse devrait plus généralement être traité par une base postgres/postgis plutôt que le mécanisme actuel basé sur des géohash. Ceci permettrait aussi de retourner un résultat pour indiquer la commune, lorsque le lat/lon fournit est très éloigné des points d'adresses.
