### ISSUE TITLE
Problème avec lat et lon pour donner une priorité géographique

### ISSUE THREAD

**Issue by Adrien98** [addok/addok#463]
Bonjour,

J'utilise l'API avec [ol-geocoder](https://github.com/jonataswalker/ol-geocoder) et en voulant restreindre les résultats retournés (ma carte ne prend en charge que ma région) pour éviter que je ne sorte du périmètre je m'aperçois que l'intégration de `lat` et `lon` dans l'URL ne change rien aux résultats retournés.

Mon exemple est le suivant : je veux que les résultats proposés par ma barre de recherche ne retournent que des villes, lieux ou villages dans le Grand Est (je ne peux donc pas utiliser postcode auquel cas je n'ai plus tout le Grand Est mais uniquement son centre). J'utilise donc les coordonnées qui servent de centre à ma carte que je passe dans mon URL mais visiblement ce n'est pas pris en compte ...
J'ai testé avec le mot clé "braille" pour ainsi trouver une rue dans Nancy qui est "Rue Louis Braille"

Voici donc mon URL :
https://api-adresse.data.gouv.fr/search/?q=braille&lat=48.69280500&lon=6.18381200

Le premier résultat se trouve à plus de 500km de l'endroit que j'ai indiqué avec `lat` et `lon` et en enlevant ces derniers j'obtiens le même résultat ...

Est-ce que j'utilise mal les coordonnées ou y-a t'il un problème ?

**Comment by yohanboniface** [comment]
La préférence géographique de la recherche n'est qu'une surpondération, qui est prise en compte dans le calcul du score final.

Pour restreindre les résultats, il faudrait utiliser un filtre (comme `postcode` ou `citycode`), mais dans l'instance maintenue par Etalab il n'y a pas de filtre permettant de restreindre sur le Grand Est.

Je vois deux options:

- monter ta propre instance
- voir avec @cquest si on ajoute la possibilité de filtrer sur les régions sur l'instance Etalab

**Comment by cquest** [comment]
Ou rajouter 'grand-est' dans la requête... c'est pas parfait, mais ça peut compenser l'absence de filtre.

https://api-adresse.data.gouv.fr/search/?q=braille%20grand-est&lat=48.69280500&lon=6.18381200

Premiers résultats à Nancy en environ...

**Comment by Adrien98** [comment]
Merci à tous les deux pour vos réponses. Je vais faire des tests en rajoutant `grand-est` !

**Comment by cquest** [comment]
Un défaut à noter... ceci fonctionne mal avec l'autocomplétion car l'ajout en fin de requête empêche d'auto-compléter ce qui est en cours de saisie, et c'est "grand-est" qui sera auto-complété à tort.

Ne pourrait-on pas passer ce type de contexte dans un paramètre "context" ;)

**Comment by yohanboniface** [comment]
> Ne pourrait-on pas passer ce type de contexte dans un paramètre "context" ;)

Je pense que le besoin là c'est spécifiquement un filtre, donc je dirais plutôt d'ajouter un filtre sur les régions.
