### ISSUE TITLE
Is-it posssible to return only result with housenumber ?

### ISSUE THREAD

**Issue by Azef1** [addok/addok#478]
Hello, 

I am very interested by this software. I did some tests on https://adresse.data.gouv.fr 
I would like to know if it is possible to return only results containing a housenumber on autocompletion.
![image](https://user-images.githubusercontent.com/15362041/44456284-66d13e80-a600-11e8-8936-5b1ad389c32f.png)

My usecase is to normalize address. So in output, i need to have housenumber+street+postcode+city. 
If housenumber not found in database, the user must complete his address via an address funnel.

Thx

**Comment by YoannRonat** [comment]
You can add [a filter](https://addok.readthedocs.io/en/latest/api/) to the request sent to Addok.
In your example: type=housenumber

For the output you may found what you like in the GoeJSON response.

**Comment by cyrilchapon** [comment]
New here, discovering this annoying behavior, is there something I can do to help ?
