### ISSUE TITLE
Géocodage Clef sans le F

### ISSUE THREAD

**Issue by laurentgarrigue** [addok/addok#480]
Bonjour,

L'API-adresse semble ne pas trouver la clé des champs.

adresse envoyée : "1 RUE DE LA CLÉ DES CHAMPS 93400 SAINT OUEN"
retour attendu : "1 Rue la Clef des Champs 93400 Saint-Ouen"

Si le "f" est absent aucun résultat ne correspond, et il diffère selon la casse et/ou l'accent.
Exemples:

CLÉ
https://api-adresse.data.gouv.fr/search/?q=1+RUE+DE+LA+CLÉ+DES+CHAMPS&postcode=93400&limit=1
NOK (rue Camille Claudel)

clé
https://api-adresse.data.gouv.fr/search/?q=1+RUE+DE+LA+clé+DES+CHAMPS&postcode=93400&limit=1
NOK (1 rue des chantiers)

CLE
https://api-adresse.data.gouv.fr/search/?q=1+RUE+DE+LA+CLE+DES+CHAMPS&postcode=93400&limit=1
NOK (1 rue des chantiers)

cle
https://api-adresse.data.gouv.fr/search/?q=1+RUE+DE+LA+cle+DES+CHAMPS&postcode=93400&limit=1
NOK (rue Camille Claudel)

Quand le F est mis, peu importe la casse ou l'accent, le résultat est bon.

**Comment by yohanboniface** [comment]
Merci pour le rapport!
Note to myself: une règle à ajouter ici: https://github.com/addok/addok-fr/blob/master/addok_fr/utils.py#L6

**Comment by cquest** [comment]
A traiter comme synonyme clef > cle

Voir https://github.com/addok/addok-fr/commit/ee2d1a89198c6ea453e043e143d2ab6be4b1d3d6
