### ISSUE TITLE
HTTP API GeoCodeJSON doesn't contain the country property

### ISSUE THREAD

**Issue by Flaburgan** [addok/addok#484]
I know most of the use case for Addok is specific for France, but I'd like the country to be present in the return of my query. How can I do that? Is this something unimplemented in Addok at the moment or is it a config to set somewhere?

**Comment by yohanboniface** [comment]
You can add a `SEARCH_RESULT_PROCESSORS_PYPATHS`:

```
def add_country(helper, result):
    result.country = 'France'

SEARCH_RESULT_PROCESSORS_PYPATHS = [
    "addok.helpers.results.match_housenumber",
    …,
    add_country   # WIthout quote, it's the func itself
]
```

(Or a `RESULTS_FORMATTERS_PYPATHS`.)

**Comment by Flaburgan** [comment]
Well, I plan to import more countries than France in addok, so I don't want to hardcode a value like that.

**Comment by yohanboniface** [comment]
Humm, but, so what's the issue?
If you have the country in the imported data, it will be in the output.
Or am I missing something? :)

**Comment by Flaburgan** [comment]
At the moment I only imported the BAN to make some tests and noticed the country was missing in the result. It looks like I "just" need to add the country to the BAN to have it returned, then.

**Comment by yohanboniface** [comment]
Yep
