### ISSUE TITLE
Tune the distance importance

### ISSUE THREAD

**Issue by YoannRonat** [addok/addok#486]
Hello,

Currently, the distance to the point given in parameter has a 0.1 importance against a 1.0 importance for string matching.

Is there any possibility to tune the importance given to the distance weight (using config file or a parameter) ?
Is this idea in any milestone ?

The purpose is to boost near adresses to the given lat/lon point when France is loaded. 

This issue is partially linked to issue https://github.com/addok/addok/issues/463 which needs a filter as I've understood.

**Comment by yohanboniface** [comment]
You can take control over the `score_by_geo_distance` result processor.

Here is its actual code:

```
def score_by_geo_distance(helper, result):
    if helper.lat is None or helper.lon is None:
        return
    km = haversine_distance((float(result.lat), float(result.lon)),
                            (helper.lat, helper.lon))
    result.distance = km * 1000
    result.add_score('geo_distance', km_to_score(km), ceiling=0.1)
```

You can copy-paste this code into your config, and pass your new function in place of the original one in the `SEARCH_RESULT_PROCESSORS_PYPATHS`.

Is that an option? Or you need something more config driven?

**Comment by yohanboniface** [comment]
OK, makes sense.
So we may add a `DISTANCE_WEIGHT` and use it like this (in `km_to_score`):

```
    return 0.0 if km > 100 else config.DISTANCE_WEIGHT * exp(-(km / 50.0) ** 2)
```

And in the ceiling as you did. Or we may pass a ceiling to `km_to_score` too.

Up for a PR? :)

**Comment by YoannRonat** [comment]
This was the idea I was thinking about :smile: 
Yep !
