### ISSUE TITLE
Gestion de plusieurs bases de données sur une seule instance

### ISSUE THREAD

**Issue by lgrd** [addok/addok#501]
Bonjour, 

Nous sommes actuellement en train d'utiliser Addok en y intégrant la BAN et nos propres bases, comme des POIs.  

Dites moi si j'ai mal compris mais il me semble qu'Addok intègre l'ensemble des documents qu'on lui fournit dans une database REDIS. Ainsi, tout les documents se retrouvent au même endroit. Et cela, indépendamment de leurs natures (adresse ou POI).

J'aimerais savoir s'il est possible de distinguer les adresses des POIs. Sachant qu'à terme nous risquons d'avoir d'autres types de données (parcelles, etc...). Je sais que l'on peut ajouter un attribut qui permettrait de distinguer le type et de filtrer. Mais alors, comment va se comporter la recherche ? Est-ce que le moteur va filtrer en aval ou en amont de la recherche ? 

Peut-on envisager qu'une instance Addok se connecte à plusieurs database REDIS ? Chaque database contiendra des données qui ne devront pas interférer avec les autres. 

Par exemple, si je veux proposer une recherche sur la BAN 'j+1' ou sur une BAN 'millésimée'. J'aimerais que l’utilisateur du service choisisse la BAN sur laquelle il fait sa recherche. Et cela en utilisant une seule instance Addok. Cela se ferait par exemple via un paramètre facultatif du genre ressource=BANJ1. Et dans la configuration, on pourrait indiquer le nombre de ressource que l'on veut et sur quelle database elle se trouve. Et lors de l'ajout des données, on pourrait préciser la ressource à laquelle ajouter ce document. Tout cela serait facultatif bien sûr. 

Pensez-vous que cela soit possible ? Compliqué ? 

Nous sommes prêt à développer une telle fonctionnalité. 

Cordialement

**Comment by Niarolf** [comment]
Bonjour,

Pour les filtres attention il faut avoir indexé les données avec ces mêmes filtres.

Il y a la possibilité d'utiliser plusieurs instances derrière un petit script comme le montre ce dépôt :+1:  https://github.com/cquest/metaddok
Et du coup il faut mettre pour chaque instance une valeur différente dans le champ attribution et au retour on peut savoir de quelles données chaque résultat provient.

Bon déploiement

**Comment by yohanboniface** [comment]
> Dites moi si j'ai mal compris mais il me semble qu'Addok intègre l'ensemble des documents qu'on lui fournit dans une database REDIS. Ainsi, tout les documents se retrouvent au même endroit. Et cela, indépendamment de leurs natures (adresse ou POI).

Oui. À noter que les index et les documents peuvent être dans deux bases différentes, et les documents peuvent même être en dehors de Redis pour économiser de la RAM (sqlite par exemple).

> Je sais que l'on peut ajouter un attribut qui permettrait de distinguer le type et de filtrer. Mais alors, comment va se comporter la recherche ? Est-ce que le moteur va filtrer en aval ou en amont de la recherche ?

En amont: seuls les documents correspondant au filtre vont être considérés.

Si on résume, il y a deux possibilités en l'état:
- typer les données, avec donc la possibilité de les filtrer; c'est simple et out of the box
- avoir un wrapper (du genre de metaddok suggéré par @Niarolf, mais metaddok fait aussi de la consolidation derrière, ce qui n'est apparemment pas nécessaire ici) qui interroge plusieurs instances d'addok; avantage: chaque instance peut-être sur sa propre machine/container

Ce serait quoi la plus-value à avoir une seule instance d'addok qui interrogerait plusieurs bases Redis vs ces deux solutions (filtre ou wrapper) ?

**Comment by lgrd** [comment]
Bonjour, 

Merci pour vos réponses ! Pour répondre à ta question @yohanboniface, nous avons beaucoup d'applications qui fonctionnent sur un modèle de 'ressources'. Une application peut gérer (créer, modifier, supprimer) plusieurs ressources. Pour des questions d'administration, cela nous paraît plus simple. Ensuite, pour des raisons de coûts, nous ne voulons pas multiplier le nombre de machines utilisées. 

Sinon pour revenir à vos propositions, nous envisageons également la deuxième possibilité. La première possibilité (typer les documents) ne nous convient pas car les documents ont des attributs très différents et nécessitent des traitements différents, donc un fichier de configuration différent. Nous sommes donc en train de faire des tests sur les instances multiples. 

Nous pensons utiliser un seul NGINX qui va rediriger vers les différentes instances d'Addok. On aimerait mettre plusieurs instance sur la même machine et sans passer par docker. Je suppose que c'est faisable. Qu'en pensez-vous ? 

Un dernier point: Comment faites-vous pour la partie back ? Un ou plusieurs REDIS ?

**Comment by yohanboniface** [comment]
> Nous pensons utiliser un seul NGINX qui va rediriger vers les différentes instances d'Addok. On aimerait mettre plusieurs instance sur la même machine et sans passer par docker. Je suppose que c'est faisable. Qu'en pensez-vous ?

Ça devrait oui :)
Avec un fichier de configuration spécifique par instance, une socket spécifique, etc..
Perso, je mettrais du coup aussi un service systemd par instance pour pouvoir les monitorer séparément.

> Un dernier point: Comment faites-vous pour la partie back ? Un ou plusieurs REDIS ?

C'est possible avec un seul REDIS, en ciblant la DB dans le fichier de configuration de chaque instance, cf https://addok.readthedocs.io/en/latest/config/#redis-dict

**Comment by lgrd** [comment]
Ok ! on teste tout ça :) merci encore pour ton aide !

**Comment by cquest** [comment]
Sur ma tour infernale je fais tourner en paralelle plusieurs instances d'addok:
- ban.addok.xyz
- bano.addok.xyz
- poi.addok.xyz (POI d'OSM)
- demo.addok.xyz (mix BANO + POI OSM)
et au moins une instance de dev/test

Pour chacune j'ai un fichier de config séparé, qui précise quelle base redis (ou keydb) utiliser pour l'index et quel fichier sqlite est utilisé pour le stockage des données.
gunicorn est lancé pour chaque instance sur des ports différents (via systemd) et nginx fait le dispatching en front sur le hostname.

Pas de LXC/LXD ou autre utilisé, mais c'est une option possible.
Attention Redis est monothread, on se retrouve donc rapidement avec un goulet d'étranglement. On peut aussi avoir plusieurs redis en //, ou bien passer à keydb (que je teste depuis peu).
