### ISSUE TITLE
Problème de score avec un nom de voie erroné

### ISSUE THREAD

**Issue by Laurent-Hervaud** [addok/addok#518]
Sur la recherche d'un nom de voie erroné dans la requête (Pardeilhan au lieu de Pard**a**ilhan), j'obtiens un score et un candidat différent si je filtre sur postcode ou citycode : 

https://api-adresse.data.gouv.fr/search?q=6%20B%20RUE%20DE%20Pardeilhan
  -> "6 BIS Rue de Pardailhan 64600 Anglet" score=0.57

https://api-adresse.data.gouv.fr/search?q=6%20B%20RUE%20DE%20Pardeilhan,%2064600
  -> "6 BIS Rue de Pardailhan 64600 Anglet" score=0.62

https://api-adresse.data.gouv.fr/search?q=6%20B%20RUE%20DE%20Pardeilhan&postcode=64600
  -> "Rue de Pinane 64600 Anglet" score=0.29

https://api-adresse.data.gouv.fr/search?q=6%20B%20RUE%20DE%20Pardeilhan&citycode=64024
  -> "6 BIS Rue du Pastisse 64600 Anglet" score=0.26

Je ne sais pas si c'est une anomalie ou si j'ai moyen de modifier ce comportement en touchant a ma config ?

**Comment by yohanboniface** [comment]
Intersesting! Je vais creuser ça :)

**Comment by cquest** [comment]
Je n'arrive pas à reproduire ces résultats avec l'API actuellement en fonctionnement, ou ma version de test/dev.

Pour les deux premières requêtes, le score augmente car le part de texte identique entre la requête et la réponse trouvée augmente.

Je ferme et à ré-ouvrir si le cas de reproduit...
