### ISSUE TITLE
Address not return

### ISSUE THREAD

**Issue by KeyConsulting** [addok/addok#525]
Api reverse : no return after lon = 5.42449951 if lat is 44.995774499999996

test 
https://api-adresse.data.gouv.fr/reverse/?lat=44.995774499999996&lon=5.42449951 : OK
https://api-adresse.data.gouv.fr/reverse/?lat=44.995774499999996&lon=5.42449952 : KO

**Comment by maximelebreton** [comment]
Bonjour,
même problème constaté avec un point pourtant existant, mais qui ne retourne aucune adresse.

Exemple, pour les coordonnées suivantes : 
`-1.329692839190244`,`47.97408981655843` (longitude, latitude)

https://api-adresse.data.gouv.fr/reverse/?lon=-1.329692839190244&lat=47.97408981655843
ne retourne aucun résultat
```
{"limit": 1, "features": [], "attribution": "BAN", "version": "draft", "type": "FeatureCollection", "licence": "ODbL 1.0"}
```

alors que le point existe bel et bien : https://www.latlong.net/c/?long=-1.329692839190244&lat=47.97408981655843

Des idées ?

**Comment by maximelebreton** [comment]
ok, here is why: https://github.com/etalab/adresse.data.gouv.fr/issues/164

it's an address oriented API, so if there is no address it will not return anything, even the city name or INSEE code.

for this you have the geo api: https://geo.api.gouv.fr/communes?lon=2.922938069157283&lat=44.78533638665951

**Comment by maximelebreton** [comment]
ok, here is why: https://github.com/etalab/adresse.data.gouv.fr/issues/164

it's an address oriented API, so if there is no address it will not return anything, even the city name or INSEE code.

for this you have the geo api: https://geo.api.gouv.fr/communes?lon=2.922938069157283&lat=44.78533638665951
