### ISSUE TITLE
problème de tokenisation ?

### ISSUE THREAD

**Issue by labenech** [addok/addok#526]
Bonjour,
je travaille sur un fichier qui comporte un champ  "nom de commune" et j'ai besoin de normaliser les noms et de récupérer les coordonnées de la commune.
Donc pas de soucis avec des requêtes du style : 
https://api-adresse.data.gouv.fr/search/?q=croson&type%20=municipality
il me trouve bien Crozon.

En revanche sur une des lignes j'ai comme nom de commune "Auxerrei", et là bizarrement il ne trouve pas Auxerre.
j'ai essayé de regarder ce qu'il se passe en faisant un "explain", on voit qu'il ne fabrique pas les tokens de la même façon pour Auxerre, Auxerri et Auxerrei.

un bug ?

**Comment by yohanboniface** [comment]
La tokénisation s'appuie sur des règles heuristiques (genre remplacer les doubles consonnes ou enlever un e muet en fin de mot) spécifiques au français.
C'est règles sont forcément imparfaites, mais elles sont là parce qu'on part du principe qu'elles réduisent les faux négatifs sans (trop) augmenter les faux positifs.
C'est toutefois pas de la magie, et en l'occcurrence je vois pas trop quelle règle pourrait nettoyer le "i" de Auxerri ou Auxerrei.
Mais je rate peut-être un truc.
Trouver Auxerre en tapant "Auxerrei" devrait être possible via le fuzzy. J'ai pas enquêté présentement.

**Comment by labenech** [comment]
c'est justement le problème, 
https://api-adresse.data.gouv.fr/search/?q=auxerrei&type=municipality
renvoie un "features" vide

**Comment by cquest** [comment]
addok n'est pas actuellement conçu pour la recherche de noms de ville seuls.
Il faudrait revoir la logique du code sur les recherches avec type=municipality car on est dans un cas où l'on a très peu de tokens

auxerri donne auxer en fuzzy, mais auxerrei donne auxere

Vu qu'on est en autocomplétion (le autocomplete=false n'est pas dans la requête), la bonne réponse a été donnée bien avant ce "i" superflu, à partir de "auxe", puis "auxer", puis "auxerr", puis "auxerre"...
