### ISSUE TITLE
Tri des résultats à égalité par ordre alphabétique

### ISSUE THREAD

**Issue by fab-girard** [addok/addok#531]
Bonjour,
lorsque l'on effectue la recherche "Bordeaux" les premiers résultats sont tous les codes postaux différents de Bordeaux dans un ordre semblant aléatoire : 
```
id: 33063_33800
id: 33063_33200
id: 33063_33100
id: 33063
```
qui ont tous un score de `0.9784363636363637` car, si j'ai bien compris, la chaine de caractère trouvée est à chaque fois identique et que la population pour tous les résultats 236.7.

Je trouve dommage que les premiers résultats proposés soient ceux de quartier pas forcément les plus parlants. 33000 est le code postal "principal", les autres sont ceux de quartiers locaux.
Y a-t-il moyen que vous triez les résultats dans un ordre plus "pertinent" quand le score est à égal ? Je proposerais sans rien y connaitre de trier sur l'id en ordre croissant par caractère. Ca donnerait dans l'ordre les codes postaux : 33000, 33100, 33200, 333000, 33800. Mais vous avez sans doute mieux comme idée !

Fabien

**Comment by fab-girard** [comment]
Ping @yohanboniface @cquest ? Proposition peut être à coté de la plaque, mais j'aimerais le savoir... ;)

**Comment by cquest** [comment]
Il est bien sûr possible d'ajouter un tri par ordre alphabétique, mais est-ce à l'API de le faire ?

- L'usage ici semble assez éloigné de l'objet d'addok... la simple recherche d'une commune n'est pas du tout ce pour quoi addok a été conçu (les adresses, plus completes et plus complexes).
- Ce tri peut se faire côté client, si cela est plus cohérent au niveau UX, et sur le critère de votre choix (l'id n'est pas forcément le bon)

**Comment by fab-girard** [comment]
Merci pour cette réponse. A la question est-ce à l'API de le faire j'aurais tendance à répondre que oui pour 2 raisons : 
- quand on cherche parmi 2 adresses strictement identiques (sans code postal par exemple), addok se doit d'accorder une importance plus grande au résultat dans la commune avec le plus grand nombre d'habitants non ? Ou n'est-ce pas du tout fait comme ça actuellement ? J'ai pris comme exemple dans mon thread de faire un tri alphabétique, mais on pourrait utiliser une autre logique proche de celle faite pour distinguer des adresses identiques (hors code postal par exemple).
Et lorsque les données ont les mêmes caractéristiques (là en l'occurrence j'avais indiqué que chaque code postal remonté semblait avoir le même nombre d'habitants, il faut bien les trier selon une autre méthode qui conduit à la même logique : avoir le résultat le plus probablement recherché en 1er)
- est-ce que un utilisateur autre d'addok quelconque serait intéressé d'avoir des résultats qui pour les premiers sont peu probablement ceux qu'il compte trouver. Je pense que non, du coup il me semble peu intéressant de le faire faire à chacun à l'extérieur d'addok

**Comment by jdesboeufs** [comment]
Je ferme car c'est ouvert depuis longtemps et parce qu'il y a au moins deux solutions :
- ajouter une étape dans les `RESULT_PROCESSORS` pour altérer le tri par score selon votre besoin
- trier dans l'interface utilisateur, ce qui encore le plus simple.
