### ISSUE TITLE
The WTFPL is not allowed anymore

### ISSUE THREAD

**Issue by bzg** [addok/addok#534]
https://www.data.gouv.fr/fr/licences lists free software licenses that should be used by public agencies.

WTFPL is not within this list. What free software license could be used instead?

**Comment by davidbgk** [comment]
Est-ce qu'on ne pourrait pas la faire homologuer ? 🙃

**Comment by bzg** [comment]
Je me corrige: vu que le dépôt a été créé avant le décret décidant des licences homologuées, le choix de la licence ne pose pas de problème. Là il faudrait juste qu'apparaissent dans les auteurs l'institution qui a récupéré les droits de publication du code source. Si je ne m'abuse, c'était le SGMAP.
