### ISSUE TITLE
404 Not Found on any request

### ISSUE THREAD

**Issue by Beniryu** [addok/addok#547]
Bonjour,

J'ai installé aujourd'hui addok en suivant le tutoriel ici : https://addok.readthedocs.io/en/latest/tutorial/#tutorial

Je suis arrivé jusqu'à la fin sans trop de souci, j'ai suivi le process à l'identique.

Cependant, une fois le serveur déployé, je n'ai pas accès à l'API.
La racine du serveur m'indique que Nginx tourne bien, mais lorsque j'essaie de lancer une requête, type "/search/?q=bobigny", j'ai un 404.
Voir ici : http://35.207.101.31/search/?q=bobigny

Les fichiers de conf sont exactement les mêmes que dans le tutoriel
Je les ai réexaminé une dizaine de fois et je sèche.

Quelqu'un aurait-il rencontré un cas similaire ou aurait une idée ?

Merci de votre attention !

**Comment by yohanboniface** [comment]
>  Voir ici : http://35.207.101.31/search/?q=bobigny

Sans passer de header HOST, nginx va utiliser le VHost par défaut, donc possiblement pas celui d'addok?

**Comment by thenodelab** [comment]
Je pense que je dois rater un truc.
J'ai essayé de set un Host dans le fichier nginx.conf pour suivre ta piste, mais ça n'a pas fonctionné.

J'ai ensuite vérifié la syntaxe du fichier de conf, en me disant qu'il y avait peut-être un souci, avec la commande 
`sudo nginx -c /srv/addok/nginx.conf -t`

Et cela m'a ratourné

> nginx: [emerg] "upstream" directive is not allowed here in /srv/addok/nginx.conf:2
> nginx: configuration file /srv/addok/nginx.conf test failed

Je n'utilise pas du tout nginx à la base, je suis sûr que c'est une bête erreur de config quelque part :/

**Comment by Beniryu** [comment]
Je pense que je dois rater un truc.
J'ai essayé de set un Host dans le fichier nginx.conf pour suivre ta piste, mais ça n'a pas fonctionné.

J'ai ensuite vérifié la syntaxe du fichier de conf, en me disant qu'il y avait peut-être un souci, avec la commande 
`sudo nginx -c /srv/addok/nginx.conf -t`

Et cela m'a ratourné

> nginx: [emerg] "upstream" directive is not allowed here in /srv/addok/nginx.conf:2
> nginx: configuration file /srv/addok/nginx.conf test failed

Je n'utilise pas du tout nginx à la base, je suis sûr que c'est une bête erreur de config quelque part :/

**Comment by yohanboniface** [comment]
Regarde dans `/etc/nginx/sites-enabled/` et tu vas sûrement  voir un `default` qui est un lien symbolique vers `/etc/nginx/sites-available`. Supprime le lien symbolique et réessaie.

Peut-être qu'il faudra ajouter `default_server` sur ton vhost.

Autre option, au lieu d'appeler une IP, appelle avec le nom de domaine configuré dans ton vhost, ou passe le bon header `HOST: mon.domaine.org`

**Comment by Beniryu** [comment]
J'ai supprimé le lien symbolique, redémarré nginx et ça tourne ! Je te remercie !

J'avais déjà configuré le header HOST suite à ton premier message, merci :)

Du coup, j'imagine qu'il y avait un conflit dans les confs ?
