### ISSUE TITLE
unable to dependencies

### ISSUE THREAD

**Issue by theAlinux** [addok/addok#552]
**input:**

`sudo apt install redis-server python3.5 python3.5-dev python-virtualenv build-essential git wget nginx uwsgi uwsgi-plugin-python3 bzip2`

**output:**
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libpython3.5-minimal' for regex 'python3.5'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package redis-server
E: Unable to locate package python3.5-dev
E: Couldn't find any package by glob 'python3.5-dev'
E: Couldn't find any package by regex 'python3.5-dev'
E: Unable to locate package python-pip
E: Package 'python-virtualenv' has no installation candidate
```

**Comment by theAlinux** [comment]
fixed, system (ubuntu 18.04) updated and upgraded first, second the input command replace `python3.5 python3.5-dev` to `python3.5 python3.5`

**Comment by yohanboniface** [comment]
You can also use python3.6 or 3.7, 3.5 is now quite old (yeah, doc should be updated :) ).

**Comment by theAlinux** [comment]
okay, i did it but this happened this is normal?

![Ekran Alıntısı](https://user-images.githubusercontent.com/10341948/57369883-6a5d2380-7197-11e9-934f-1b81bd96b354.PNG)

**Comment by yohanboniface** [comment]
Yes, you are now logged in as user "addok"

**Comment by theAlinux** [comment]
okay, fixed but now
input:  `source venv/bin/activate`
output: `-sh: 4: source: not found`
