### ISSUE TITLE
some steps help?

### ISSUE THREAD

**Issue by theAlinux** [addok/addok#557]
i use python 3.6, (https://github.com/addok/addok/issues/552#issuecomment-490433556),
help asap for this steps also i need UK address (autocomplete), please???

1- 
```
root@map-1:~# source venv/bin/activate
bash: source: venv/bin/activate: is a directory
```

2- 
run this command `addok batch BAN_odbl_93-json`

output:

```
Traceback (most recent call last):
  File "/usr/local/bin/addok", line 7, in <module>
    from addok.bin import main
  File "/usr/local/lib/python2.7/dist-packages/addok/bin/__init__.py", line 7, in <module>
    from addok.config import config
  File "/usr/local/lib/python2.7/dist-packages/addok/config/__init__.py", line 11, in <module>
    from . import default
  File "/usr/local/lib/python2.7/dist-packages/addok/config/default.py", line 2, in <module>
    from pathlib import Path
ImportError: No module named pathlib
```

also

`addok not found`

3-
```
root@map-1:~# source venv/bin/activate
bash: venv/bin/activate: No such file or directory
```

**Comment by yohanboniface** [comment]
> bash: source: venv/bin/activate: is a directory

Never seen that. You certainly have mixed up some commands or something in the process. Remove the `venv` directory and create it again.

> ImportError: No module named pathlib

When you run the command, I guess the venv has not activated in the current session (as said before), and you are using the system python, which is python 2.7.

> bash: venv/bin/activate: No such file or directory

`venv/bin/activate` is a relative path, so it's up to you to understand where you are in the filesystem tree when you run each command.

Again, if you are not comfortable with Linux system administration, going the [Docker](https://github.com/etalab/addok-docker) way is certainly less frustrating for you.

**Comment by theAlinux** [comment]
this command `source venv/bin/activate` can i run root or user login ( `sudo -u addok -i` ) ?

**Comment by yohanboniface** [comment]
> this command source venv/bin/activate can i run as root or as user login ( sudo -u addok -i ) ?

as user addok

**Comment by theAlinux** [comment]
> > this command source venv/bin/activate can i run as root or as user login ( sudo -u addok -i ) ?
> 
> as user addok

but output: `-sh: 1: source: not found`

**Comment by theAlinux** [comment]
> > this command source venv/bin/activate can i run as root or as user login ( sudo -u addok -i ) ?
> 
> as user addok

i have 2 questions?

1- `source venv/bin/activate` output `sh: 1: source: not found` im replace source to sh, is it true?

2- i'm type python in normal directory as root, as output python 3.7 but i'm type python, version 2.7 as output type than type `sudo -u addok -i` 

for example images:

1-
![1111](https://user-images.githubusercontent.com/10341948/57490063-b061d680-72c0-11e9-8888-0d7fdc80d997.PNG)

2-
![22222](https://user-images.githubusercontent.com/10341948/57490071-b5bf2100-72c0-11e9-8a0d-a778c97da81b.PNG)

**Comment by Niarolf** [comment]
Is alinux the user for addok ?
Have you reinstall addok with python3 ?

**Comment by theAlinux** [comment]
yes, also i installed user as addok got same error.

yes, i installed python3 but it installed python 2.7 as default, i'm not change it

**Comment by Niarolf** [comment]
Give us all the commands line you used for the installation please

**Comment by theAlinux** [comment]
1- `sudo -s`
2- `apt-get update`
3- `apt-get upgrade`
4- `sudo apt install redis-server python3.5 python3.7 python-virtualenv build-essential git wget nginx uwsgi uwsgi-plugin-python3 bzip2`
5- `useradd -N addok -m -d /srv/addok/`
6- `mkdir /etc/addok/`
7- `chown addok /etc/addok`
8- `apt-get install python-pip`
9- `sudo -u addok -i`
10- `virtualenv venv --python=/usr/bin/python3.7`
11- `sh venv/bin/activate`
12- `pip install addok`
13- `pip install addok-fr`
14- `pip install addok-france`
15- input: `addok --help`, output: `sh: 6: addok: not found`
16- `exit` (i went to root directory)
17- `pip install addok`
18- `pip install addok-fr`
19- `pip install addok-france`
20- `sudo -u addok -i`
21- 
**input:**
`addok --help`
**output:**
```
Traceback (most recent call last):
  File "/srv/addok//.local/bin/addok", line 7, in <module>
    from addok.bin import main
  File "/srv/addok/.local/lib/python2.7/site-packages/addok/bin/__init__.py", line 7, in <module>
    from addok.config import config
  File "/srv/addok/.local/lib/python2.7/site-packages/addok/config/__init__.py", line 11, in <module>
    from . import default
  File "/srv/addok/.local/lib/python2.7/site-packages/addok/config/default.py", line 2, in <module>
    from pathlib import Path
ImportError: No module named pathlib
```

i'm stay here???

**Comment by Niarolf** [comment]
pip is python 2.7 you must use pip3 for python 3.5 or higher
First try to install python3-pip and python3-virtualenv
And then use pip3 for the installation :
pip3 install addok ...

**Comment by yohanboniface** [comment]
@theAlinux I've rerun myself the tutorial against Ubuntu 18.04 and made some minor adjustments on it, please follow it carefully it will work:

https://addok.readthedocs.io/en/latest/tutorial/

**Comment by theAlinux** [comment]
okay, everything works, thanks but i get `Internal Server Error`
can it works as http or https, only as https?
