### ISSUE TITLE
reverse geocoding retourne une erreur 500 sur coordonnées hors limites

### ISSUE THREAD

**Issue by Laurent-Hervaud** [addok/addok#564]
L'api retourne une erreur 500 avec des coordonnées en dehors des limites (-90/+90; -180/+180).

Ex :
https://api-adresse.data.gouv.fr/reverse/?lon=200&lat=200

**Comment by cquest** [comment]
Ce devrait en effet plutôt être une 40x, potentiellement une 422 (Unprocessable entity).

**Comment by cquest** [comment]
Corrigé par https://github.com/addok/addok/commit/aae1fbc985b6efe2b13bffa530c81de71794ef57
