### ISSUE TITLE
Question redis sur le déploiement avec et sans SQLite store (document)

### ISSUE THREAD

**Issue by garaud** [addok/addok#567]
Bonjour,

Déjà bravo pour le travail accompli et la qualité de la documentation ! Les données et le code sont vraiment très très utiles.

Nous déployons actuellement le service (données + code) sur un serveur interne et j'ai quelques questions à propos du stockage Redis. Les données en question sont celles mentionnées dans la documentation, i.e. http://bano.openstreetmap.fr/data/, fichier `full.sjson.gz` (France entière)

La documentation conseille un import complet de données France entière avec 20Go de RAM, c'est ce qu'on a fait.

## Configuration par défaut + plugins

J'ai repris le fichier de configuration [en exemple dans ce dépôt](https://github.com/addok/addok/blob/master/addok/config/default.py). J'ai ajouté les quelques lignes sur les PROCESSORS et autres concernant les deux plugins suivants : addok-france et addok-fr.

Redis ici stocke par défaut les documents et les index. À la fin de l'import (batch + ngrams), le processus Redis *server* continue de prendre entre 10 et 11 Go de RAM. J'ai voulu tenter une autre approche (ci dessous) pour avoir une plus faible consommation mémoire

## SQLite document store + plugins

En installant le plugin [addok-sqlite-store](https://github.com/addok/addok-sqlite-store) et en précisant le fichier SQLite dans le fichier de configuration, j'ai *flushé* Redis et renouvelé l'import.

J'ai cette fois-ci épuré le fichier de config et repris quelque chose de très similaire à celui-ci https://github.com/addok/addok/blob/master/fabfile/france.local.py

J'ai bien l'existence d'un fichier SQLite de env. 1.5Go à l'endroit indiqué par le fichier de configuration. Par contre, à la fin de l'import, mes processus Redis *server* prennent toujours entre 10Go et 11Go de RAM.

Je voulais savoir si c'était quelque chose de normal. Comment je peux voir si les documents sont bien tous stockés dans le SQLite et non pas aussi dans Redis ? On ne devrait pas avoir une conso mémoire moins importante dans ce cas là comme le souligne la documentation ?

Merci beaucoup :slightly_smiling_face: 
Damien G.

**Comment by Laurent-Hervaud** [comment]
Dans la même conf (Redis+SQLite) avec un container Docker pour Redis (https://github.com/etalab/addok-docker), Redis utilise 5Go de RAM pour ma part.
Peut-être relancer le service Redis pour libérer les ressources utilisées lors de l'import ?

**Comment by garaud** [comment]
@Laurent-Hervaud Merci pour la rapidité de la réponse. Je ne connaissais pas ce dépôt Docker pour addok, merci.

Impressionné par la vitesse de mise en base des données !! Avec une bonne machine, ça met un peu moins d'une heure avec ces données http://bano.openstreetmap.fr/data/full.sjson.gz

Je vois que vous faites mention de données "pré-indexée". Je vais jeter un oeil.

>  Peut-être relancer le service Redis pour libérer les ressources utilisées lors de l'import ?

Vous voulez dire relancer le service Redis quand l'import est fini, c'est ça ? Il rechargera en RAM ce qu'il a réussi à persister dans `/var/lib/redis` ?

**Comment by Laurent-Hervaud** [comment]
oui c'est ça

**Comment by garaud** [comment]
Merci. Et bien sans grand succès, je vois bien la RAM des process Redis qui monte qui monte et qui se stabilise vers 10Go.

En comparant l'origine des données entre le site adresse.gouv.fr et la documentation d'addok, je m'aperçois tout simplement que j'ai plus du double de lignes dans mon JSON en entrée :

```
> wc -l bano-full.sjson && wc -l BAN_odbl.json 
5536336 bano-full.sjson
2404771 BAN_odbl.json
```

Si la taille de l'index est globalement linéaire avec le volume de données en entrée, je pense qu'on reste dans les "bons" ordres de grandeur.

C'est bien la doc d'addok (ahah ça rime) qui mentionne les données d'adresse depuis cette URL http://bano.openstreetmap.fr/data/ plutôt que celle donnée sur le site adresse.gouv.fr qui est celle-ci http://bano.openstreetmap.fr/BAN_odbl/ (dernière mise à jour fin 2018).

Les données pré-indexées viennent-elles bien de ce jeu de données ? http://bano.openstreetmap.fr/BAN_odbl/BAN_odbl.json.bz2

D'ailleurs, à part le champs `citycode` qui semble présent dans BAN_odbl et pas dans l'autre, quelles différences de contenus ou de traitement il y a entre les deux sources de données ? Vous conseillez plutôt lesquelles ?

Merci

**Comment by Laurent-Hervaud** [comment]
L'écart via sûrement des données. La doc sur https://addok.readthedocs.io/en/latest/tutorial/ renvoie vers http://bano.openstreetmap.fr/BAN_odbl/

**Comment by garaud** [comment]
Ok, merci.

Et la page sur l'import https://addok.readthedocs.io/en/latest/import/#example-with-bano renvoie vers http://bano.openstreetmap.fr/data/full.sjson.gz

**Comment by cquest** [comment]
BAN et BANO sont deux bases au contenu différent.

Il y a plus de lignes dans le json de BANO car BANO comporte bien plus de noms de lieux-dits que la BAN qui ne contient en principe que des adresses numérotées.

Ceci explique la différence aussi en terme de RAM utilisée par redis, car chaque ligne est indexée, et l'index est dans redis (donc en RAM). Pour les adresses numérotées, elles se trouvent dans le fichier sqlite.

Pour citycode, il n'est pas directement présent comme champ dans les données BANO, mais figure toujours en début d'id.

BAN: plus complète sur les adresses numérotées, mais présence de doublons, et mise à jour parfois bien longue après l'apparition d'une adresse sur le terrain

BANO: moins complète sur les adresses numérotées, mise à jour potentiellement plus réactive sur les nouvelles adresses si elles ont été ajoutées dans OpenStreetMap, bien plus complet sur les noms de lieux-dits

L'idéal serait est un mix des deux...

**Comment by haubourg** [comment]
@garaud Salut Damien :) , tu crois qu'on peux fermer ce ticket ?

**Comment by garaud** [comment]
Et bien oui M'sieur Régis :) Je pense qu'on peut fermer. J'avais effectivement eu réponses à mes questions.

Merci à tou·te·s !
