### ISSUE TITLE
Release candidate pour la version 1.1.0

### ISSUE THREAD

**Issue by Barbaro** [addok/addok#569]
Bonjour,

Tout d'abord, merci pour ce projet qui permet de faire traitements en masse vite et bien.

Sur le repo, à l'heure actuelle, la version la plus récente est la 1.1.0-rc1 qui date du 19 Février 2018. Je voudrais savoir si le projet n'est à l'heure actuelle plus vraiment supporté, ou si d'autres points de blocages expliquent une rc aussi ancienne.

Merci 🙂
Kévin

**Comment by cquest** [comment]
Bonjour,
Je suis en train de me remettre sur addok, qui effectivement n'a pas eu beaucoup d'attention depuis un certain temps.
Une branch cquest-11rc2 est ouverte, je contribue dessus pour l'instant.

**Comment by Niarolf** [comment]
Bonjour,
effectivement je serais également intéressé par une release récente en vue de mettre à jour une installation en production prochainement.
Merci

**Comment by Niarolf** [comment]
@cquest des nouvelles pour une release ?

**Comment by jdesboeufs** [comment]
La version `1.1.0` a été publié il y a quelques semaines.
