### ISSUE TITLE
CSV import: try to guess encoding

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok#57]
Libs:
- https://github.com/chardet/chardet
- https://github.com/mattbasta/fastchardet
- https://github.com/tyrannosaurus/python-libmagic

**Comment by richterb** [comment]
For what it's worth, at opendatasoft we've been using ftfy (https://pypi.python.org/pypi/ftfy) for a few months, and it's much much better at detecting encoding than anything else we tried (I know the last we had was chardet), BUT it only supports "occidental" (latin) encodings (http://ftfy.readthedocs.org/en/latest/#encodings-ftfy-can-handle). However, the difference in detection success rate is so vast that we use ftfy by default and propose chardet optionally (e.g. using a checkbox saying "my file contains non-latin characters").
 
Our tests were made a few months ago so it may be different now, of course :)

**Comment by davidbgk** [comment]
Might be fixed in addok-csv one day.
