### ISSUE TITLE
88 avenue antoine de saint exupéry toulouse...

### ISSUE THREAD

**Issue by cquest** [addok/addok#60]
88 avenue antoine de saint exupéry toulouse
retourne: Rue Antoine de Saint-Exupéry 83000 Toulon

88 avenue antoine de saint exupéry 31 toulouse
retourne 31 Avenue Antoine de Saint-Exupéry 65000 Tarbes

88 avenue antoine de saint exupéry 31400 toulouse

en supprimant le prénom ou en ajoutant le code postal complet on trouve bien la bonne adresse...

**Comment by davidbgk** [comment]
Edge case, too hard to fix properly.
