### ISSUE TITLE
addok-csv ajouter le paramètre type

### ISSUE THREAD

**Issue by Laurent-Hervaud** [addok/addok#608]
Il pourrait être intéressant de pouvoir filtrer avec addok-csv sur le type (par ex type:housenumber) comme c'est le cas avec l'api unitaire

**Comment by yohanboniface** [comment]
IIRC, you can pass any filter like this: `{filter_name}={column_name}`, where `filter_name` is the filter you wan to use (eg. `type`) and `column_name` is the column name containing the filter value for each row.

**Comment by yohanboniface** [comment]
oops, désolé, le message parti en engliche :/
Bref, à tester, ça commence à faire loin pour moi tout ça :)
