### ISSUE TITLE
Comment utiliser /reverse avec succès ?

### ISSUE THREAD

**Issue by kopax** [addok/addok#610]
Je souhaites obtenir de l'aide afin d'utiliser https://github.com/etalab/addok-docker/blob/master/README.md

Après avoir démarrer le service, je suis en mesure d'effectuer des requêtes de type `/search` mais pas les requetes de types `/reverse`, bien que celle ci soit documenté ici:  https://addok.readthedocs.io/en/latest/api/#endpoints

Voici ce qu'il se passe lorsque j'utilise les lat/lng retourné par une recherche pour faire un reverse geocoding:

```
curl -L http://localhost:7878/reverse/?lat=2.29009&lng=49.897446
[1] 10526 {"title": "Invalid args", "description": "Invalid args"}
```

Je souhaites savoir comment effectuer cette requêtes avec succès, 

https://github.com/addok/addok/blob/cb6fb1e2da6f0ea5be9063f9204b07713739393c/addok/http/base.py#L121

**Comment by Niarolf** [comment]
Bonjour,
pour la longitude, tu peux utiliser l'attribut **lng** mais il est prévu d'utiliser **lon**
Est-ce que tu as la même erreur avec l'attribut **lon** ?
Cordialement

**Comment by Niarolf** [comment]
Bonjour,
en ligne de commande le & est interprété, pour être inclus dans ta commande curl tu dois mettre des quotes :
curl -L 'http://localhost:7878/reverse/?lat=2.29009&lng=49.897446'
Cordialement

**Comment by AdrienVH** [comment]
Bonjour,
Les latitude et longitude semblent inversées. Vous risquez de n’avoir aucun résultat de fait :-)
Adrien

**Comment by kopax** [comment]
Effectivement, bien vu, ca a résolu le soucis, merci @Niarolf !

@AdrienVH bizarre car au contraire j'ai bien retrouvé mon résultat:

```
 curl -L 'http://localhost:7878/reverse?lng=2.29009&lat=49.897446'
{"type": "FeatureCollection", "version": "draft", "features": [{"type": "Feature", "geometry": {"type": "Point", "coordinates": [2.290084, 49.897443]}, "properties": {"label": "8 Boulevard du Port 80000 Amiens", "score": 0.9999999998817588, "housenumber": "8", "id": "80021_6590_00008", "type": "housenumber", "x": 648952.58, "y": 6977867.25, "importance": 0.5699161183972735, "name": "8 Boulevard du Port", "postcode": "80000", "citycode": "80021", "city": "Amiens", "context": "80, Somme, Hauts-de-France", "street": "Boulevard du Port", "distance": 0}}], "attribution": "BAN", "licence": "ETALAB-2.0", "limit": 1}
```
