### ISSUE TITLE
[Question] Autocomplémention codes postaux

### ISSUE THREAD

**Issue by guillaumeansel** [addok/addok#616]
Bonjour,

Je m'intéresse à la solution addok pour réaliser de l'autocomplétion permettant de sélectionner une ville à partir du code postal ou du nom de celle-ci.

A partir du nom, ça fonctionne très bien. Dès qu'on a quelques caractères le système renvoie des propositions pertinentes. Par contre on aimerait avoir la même possibilité à partir en saisissant une partie d'un code postal. 

Par exemple, si je commence à renseigner "130" je peux m'attendre à ce que les arrondissements de Marseille soient proposés en suggestion.

Les tests que j'ai fait pour l'instant sur l'instance https://api-adresse.data.gouv.fr renvoie 0 résultat avec une query contenant un code postal partiel.

Est-ce qu'il y a une possibilité de contourner cette limitation?

Merci d'avance pour votre aide, et merci pour votre travail.

**Comment by jdesboeufs** [comment]
Hi @guillaumeansel 
This engine has been designed for addresses, and not for postcodes autocompletion.
You should submit an issue on https://github.com/etalab/api-geo and ask for this feature.
