### ISSUE TITLE
Get all the names of a record (not only the first one)

### ISSUE THREAD

**Issue by AdrienVH-c2c** [addok/addok#617]
For the needs of a geocoding project, Addok provides us a simple way to index current names and old names for thousands and thousands of french POIs.

Indeed, as soon as one of our records has several names, let's say a list of two names...

    {"id":"poi-123456", "name":["Ecole Anne Frank", "Ecole de la Carrière"], ...}

...it's possible, thanks to Addok, to query it on both of its names :

    search/?q=ecole+anne+frank
    search/?q=ecole+carriere

For these 2 queries, the result shown will be (almost) exactly the same GeoJSON : a feature collection, with a feature, showing "Ecole Anne Frank" as value for the "name" property :

    {
        "type": "FeatureCollection",
        "features": [
            {"type": "Feature", "geometry": {...}, "properties": {"name":"Ecole Anne Frank", ...}}
        ],
    ...}

It's a great behavior, for our needs, but it could be tricky for final users to understand why, when they made an "ecole+carriere" query, they get an "Ecole Anne Frank" candidate...

The results of an Addok query seems, indeed, to always only show the first value, for each of the properties (names, citycode, etc.). We get a string, when we provided an array of strings (the record indexed).

**It would be great if, at least for the name property, Addok could return an array of strings, instead of the first value only :**

    {
        "type": "FeatureCollection",
        "features": [
            {"type": "Feature", "geometry": {...}, "properties": {"name":["Ecole Anne Frank", "Ecole de la Carrière"], ...}}
        ],
    ...}

No need to change the way the "label" property is made (using name[0]), but having a full array of values could let us choose what we want to display to final users (again, in order to help them to understand what Addok returned and why).

**Comment by yohanboniface** [comment]
Agreed.
I actually think it's Addok job to adapt label to searched string, and I think something like this could do the job: `{primary_name} ({secondary_matched_name})`.
So in your case, if someone searched for `école carrière`, the label would be:

`École Anne Franck (École de la Carrière)`.

And in an ideal world, Addok would even return an array of matched coordinates pairs, to allow the frontend to highlight the term parts that matched.

**Comment by AdrienVH-c2c** [comment]
Yeah, it would be great if it there was a way to retrieve the name that matched the query, like a new "matched_name_position" attribute :

    // Pour /search/?q=ecole+anne+frank
    "properties": {
        "label" : "Ecole Anne Frank 93250 Villemomble"
        "name" : ["Ecole Anne Frank", "Ecole de la Carrière"],
        "matched_name_position" : 0,
        "postcode" : "93250",
        "city" : "Villemomble"
        ...
    }

    // Pour /search/?q=ecole+carriere
    "properties": {
        "label" : "Ecole Anne Frank 93250 Villemomble"
        "name" : ["Ecole Anne Frank", "Ecole de la Carrière"],
        "matched_name_position" : 1,
        "postcode" : "93250",
        "city" : "Villemomble"
        ...
    }

Thus, we would be able, in our front app, to display the "matched name" whenever the matched_name_position value is greater than 0 :

    var customLabel = result.properties.name[0]
    if(result.properties.matched_name_position > 0){
        var matchedName = result.properties.name[matched_name_position]
        customLabel += ' (anc. ' + matchedName + ')'
    }
    // Pour /search/?q=ecole+anne+frank, customLabel = "Ecole Anne Frank"
    // Pour /search/?q=ecole+carriere, customLabel = "Ecole Anne Frank (anc. Ecole de la Carrière)"

**Comment by AdrienVH-c2c** [comment]
To get all the names of a record, it seems possible to edit the **getattr** method of the **Result** class (core.py) in order to return the whole array (and not only the first value) whenever the **key** arg == the **NAME_FIELD** value :

    def __getattr__(self, key):
        if key not in self._cache:
            # By convention, in case of multiple values, first value is default
            # value, others are aliases.
            if(key == config.NAME_FIELD):
                value = self._rawattr(key)
            else:
                value = self._rawattr(key)[0]
            self._cache[key] = value
        return self._cache[key]

**Comment by yohanboniface** [comment]
Ah, if you are admin of your own addok instance, I think the right way to do this would be to add a new [formatter](https://github.com/addok/addok/blob/master/addok/helpers/formatters.py), then referenced in the [RESULTS_FORMATTERS_PYPATHS](https://github.com/addok/addok/blob/master/addok/config/default.py#L98) setting.

**Comment by AdrienVH-c2c** [comment]
Thanks Yohan. I did add a geojson_with_names method to formatters.py in order to add a "names" attributes with the whole "name" array as value :

    def geojson_with_names(result):
        geojson_with_names = geojson(result)
        geojson_with_names["properties"]["names"] = result._doc.get('name')
        return geojson_with_names

And, then, I changed the formatter to use in default.py :

    RESULTS_FORMATTERS_PYPATHS = [
        'addok.helpers.formatters.geojson_with_names',
    ]

It works just fine !
