### ISSUE TITLE
24 bd hopital paris => paris-l-hopital !

### ISSUE THREAD

**Issue by julien2512** [addok/addok#63]
Il s'agit d'une regression, car cet appel fonctionnait auparavant !
Actuellement, il retourne le village de paris-l-hopital comme meilleur résultat.

**Comment by yohanboniface** [comment]
```
> EXPLAIN 24 bd hopital paris
[0.743] Taken tokens [<Token opital>, <Token pari>]
[0.772] Common tokens [<Token boulevar>, <Token 24>]
[0.782] Not found tokens []
[0.793] ** STEP_ONLY_COMMONS **
[0.803] ** STEP_NO_MEANINGFUL_BUT_COMMON_TRY_AUTOCOMPLETE **
[0.812] ** STEP_BUCKET_WITH_MEANINGFUL **
[0.828] New bucket with keys ['w|opital', 'w|pari'] and limit 10
[2.214] 10 ids in bucket so far
[2.232] New bucket with keys ['w|opital', 'w|pari'] and limit 0
[2.774] 34 ids in bucket so far
[2.789] ** STEP_REDUCE_WITH_OTHER_COMMONS **
[2.802] ** STEP_ENSURE_GEOHASH_RESULTS_ARE_INCLUDED_IF_CENTER_IS_GIVEN **
[2.811] ** STEP_AUTOCOMPLETE **
[2.823] Autocompleting pari
[2.951] Found tokens to autocomplete set()
[2.967] ** STEP_CHECK_BUCKET_FULL **
[2.978] Computing results
[13.49] Done computing results
Paris-l'Hôpital (71343 | importance: 0.0075/0.1, str_distance: 0.6/1.0)
24 Boulevard de l'Hôpital 75005 Paris (75105_4649_fec947 | importance: 0.0399/0.1, str_distance: 0.4595/1.0)
```
C'est la distance de chaîne qui fait la différence. T'es sûr que ça marchait avant tel quel?
Je vois pas de changement récent qui aurait touché ce point, faut sûrement que je me creuser un peu mieux les méninges ;)
Possible que le changement de données source y soit pour quelque chose (Paris-l'Hôpital manquait avant? Était-il orthographié différemment? Quelque chose aurait changé sur le boulevard de l'hôpital?)

@cquest, une idée?

**Comment by julien2512** [comment]
Je me trompe peut-être, mais c'est l'adresse de mon bureau ! Je l'ai
probablement déjà testée 100 fois sur adhoc ...
Bizarrement, lorsque l'on utilise boulevard à la place de bd, le résultat
est correct !

**Comment by julien2512** [comment]
Oui, non, j'ai compris pourquoi boulevard fonctionnait (puisque tu indiques
que c'est la distance de chaîne qui fait finalement la différence). Par
contre, cela me semble être une erreur, car bd = boulevard, la distance est
donc de 0...

**Comment by yohanboniface** [comment]
> Oui, non, j'ai compris pourquoi boulevard fonctionnait (puisque tu indiques
> que c'est la distance de chaîne qui fait finalement la différence). 

Exact :)

> Par contre, cela me semble être une erreur, car bd = boulevard, la distance est
> donc de 0...

Pas dans la façon dont c'est fait. En l'état, le parti pris, c'est de ne pas faire d'inférence sur la distance de chaîne, donc on compare la chaîne exacte telle qu'elle a été entrée par l'utilisateur avec la chaîne du résultat. L'idée c'est de dire que l'algo de recherche, lui, fait pas mal d'inférences pour déterminer quels pourraient être les meilleurs résultats, et que la comparaison par distance de chaîne finale est le garde-fou pour vérifier qu'on est cohérent avec la requête initiale. Si je duplique des inférences (type bd => boulevard) je casse le garde-fou et je peux me retrouver avec des résultats totalement délirant. Example au pif pour illustrer, imaginons qu'on ait les POI, quelqu'un pourrait chercher une librairie nommée "L'univers de la bd" en tapant "univers bd", si de l'autre côté on a un "boulevard de l'univers", je perds la possibilité de discriminer les résultats en tâchant d'être proche de ce que l'internaute a *vraiment* tapé.
Le pendant de ce parti pris, c'est qu'un internaute *tolère* que si la chaîne retournée ne comprend pas exactement ce qu'il a tapé elle ne soit pas le premier résultat (donc "boulevard" alors qu'il a tapé "bd"), mais ne tolérerait pas du tout qu'une chaîne qui correspond exactement à ce qu'il a tapé ne soit pas première. C'est ce que j'appelle le contrat de confiance (merci Darty), et je tâche de m'appuyer là-dessus pour savoir où mettre la limite de la magie: je préfère perdre un peu en qualité en n'ajoutant pas un bout d'algo qu'ajouter des effets de bord contre-intuitifs en l'ajoutant.
Après ça, on navigue dans des eaux où deux et deux ne font pas tout à fait quatre, et il faut bouger des curseurs un peu à droite un peu à gauche et parfois interpréter *subjectivement* si on y gagne ou on y perd ;)
Makes sense? :)
Et oui, dans ton cas, j'aimerais mieux que "24 boulevard de l'hôpital" remonte en premier, et donc ça reste un bug :/

**Comment by julien2512** [comment]
Oui, j'ai compris ton approche, mais il y a une faille dans ton raisonnement.

24 boulevard de l' hopital => bd peut être un synonyme
L'univers de la bd => hopital n'est pas un synonyme

La prise en compte d'un synonyme dépend surtout de l'adresse indexée, qui est génèralement complète (sans abbréviations). Dans ton exemple, tu peux donc bien développer l'algorithme permettant de ne pas avoir de confusion.

Par exemple, dans ES, le fichier de paramétrage aurait été : 
boulevard => bd, boulevard
et non pas
bd, boulevard => bd, boulevard
qui entraîne effectivement de fâcheux effets de bords
!

Les hypothèses de mon raisonnement sont :
1. les adresses / POI indexés sont "désabbréviés"
2. Des homonymes qui n'auraient pas la même abbréviation ... lol

A voir ton exemple aussi. Peut-on trouver "l'univers de la bd" en saisissant "l'univers de la bande dessinée ?" Là, ok, cela pose problème si "l'univers de la bd" est indexé à la place de sa version "désabbréviée".
Mais nous savons bien que la limite du procédé est la qualité du référentiel ...

**Comment by yohanboniface** [comment]
Humm, je suis pas sûr de te suivre :/

> 24 boulevard de l' hopital => bd peut être un synonyme
> L'univers de la bd => hopital n'est pas un synonyme

Tu veux dire "boulevard n'est pas synonyme", non?

> Par exemple, dans ES, le fichier de paramétrage aurait été :
> boulevard => bd, boulevard
> et non pas
> bd, boulevard => bd, boulevard

Tu veux pas dire "bd, bvd => boulevard", plutôt?
En tout cas c'est ce que j'ai dans [addok](https://github.com/etalab/addok/blob/master/addok/resources/synonyms/fr.txt#L6).

En d'autres termes, en l'état:
- le document "24 boulevard de l'hôpital" est indexé avec "boulevard" uniquement (pas "bd")
- le document "univers de la bd" idem (c'est un effet de bord du fait que bd est polysémique, et c'est justement ce qu'on essaie de démontrer ici ;) )

Au moment de la recherche:
- la query "24 bd hôpital" est transformée en "24 boulevard hôpital"
- la query "univers de la bd" est transformée en "univers de la boulevard" (mais ça tombe bien puisqu'on a indexé "boulevard"

Au moment du scoring:
- "24 bd hôpital" est comparé avec "24 boulevard de l'hôpital", ce ne donne pas un score terrible
- de l'autre côté, une recherche "univers de la bd" est comparée avec "Univers de la bd", et là pour le coup on a un bon score, bien qu'en interne ce soit "boulevard" qui soit indexé et cherché.

En d'autres termes, la comparaison de chaîne sert à lisser les effets de bord des algos internes, dont par exemple le fait que "bd" est toujours indexé en "boulevard", même quand on veut pas. C'est un moyen de s'assurer que, au final, les résultats proches (au sens humain du terme) sont avantagés, et, surtout, que les faux positifs sont dégradés.

**Comment by julien2512** [comment]
Oui, j'ai compris l'objet de notre incompréhension mutuelle !
Je parle de l'indexation, et toi de la recherche.

De ton coté, il me semble que tu effectues la transformation durant la
recherche, d'où l'impossibilité effective de tolérance exacte des synonymes.
Tu retombes donc bien sur tes pattes avec un algorithme très rapide pour
75% des cas.


De mon coté, durant l'indexation, je stocke les deux informations pour une
même adresse: bd et boulevard. bande dessinée et bd (le cas échéant).
Durant la recherche, je ne fais pas de transformations, et me contente de
chercher et de scorer ce que l'utilisateur a saisi.
Le gain est évidemment une meilleure tolérance aux synonymes. La
contrepartie est un index un peu plus volumineux, et un algorithme de plus
durant la recherche pour le calcul du score. J'ai bien 100% des cas, au
prix de la RAM et du CPU ...

Remarques que ni toi ni moi ne pouvons faire actuellement la recherche avec
"bande dessinée" !

**Comment by davidbgk** [comment]
See discussion at https://github.com/addok/addok/issues/101#issuecomment-269913660
