### ISSUE TITLE
Addok-csv et Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by Barbaro** [addok/addok#631]
Bonjour à tous,

Via une requête curl, je peux bien requêter par exemple GET /search?q=81%20AVE%20PASTEUR%2091330%20YERRES en fournissant dans les headers "Transfer-Encoding: chunked" par contre, concernant le géocodage d'un fichier csv, j'ai une erreur 400 qui revient dès que je fais une requête curl vers POST /search/csv/.

Cette requête /search/csv/ fonctionne néanmoins si je ne spécifie pas dans les headers "Transfer-Encoding: chunked".
La problématique est la même que j'interroge en direct addok, ou bien nginx en front.

J'ai pu voir que le nginx de api-adresse.data.gouv.fr ne pose aucun soucis à ce niveau, que je veuille faire du chunked avec GET /search ou bien avec POST /search/csv/.

Je me demande donc si une manip particulière que j'aurais raté est nécessaire afin de permettre de faire du "Transfer-Encoding: chunked" avec addok-csv.

Merci pour vos retours.

**Comment by jdesboeufs** [comment]
For api-adresse.data.gouv.fr we currently use https://github.com/etalab/api-geocode which handle HTTP/CSV wrapping.
We are now working on a better communication between these tools, and we will probably fix some inconsistent behaviors.
