### ISSUE TITLE
Coordonées correcte dans la BAN mais geocodage incorrect

### ISSUE THREAD

**Issue by MrFenril** [addok/addok#641]
Bonjour.
Nous utilisons le pluggin addok-france en interne avec Addok et nous rencontrons un problème avec des addresses mal géocodées.
Nous essayons de géocoder 4 addresses, à savoir :
- 1 rue de lisbonne 67300 Schiltigheim France
- 3 rue de lisbonne 67300 Schiltigheim France
- 4 rue de lisbonne 67300 Schiltigheim France
- 9a rue de lisbonne 67300 Schiltigheim France

`4 rue de lisbonne 67300 Schiltigheim France` et `9a rue de lisbonne 67300 Schiltigheim France` sont géocodées correctement et nous donne les bonnes latitude/longitude.
Malheuresement, pour `1 rue de lisbonne 67300 Schiltigheim France` et `3 rue de lisbonne 67300 Schiltigheim France` nous nous retrouvons avec des latitude/longitude éronnées.

Notre `BAN` contient le document suivant :
<details>
<summary>Show json</summary>

```
{
  "id": "67447_0744_026611",
  "type": "street",
  "name": [
    "Rue de Lisbonne"
  ],
  "postcode": "67300",
  "citycode": [
    "67447"
  ],
  "lon": 7.704729,
  "lat": 48.611046,
  "x": 1046625.1,
  "y": 6844868.2,
  "city": "Schiltigheim",
  "context": "67, Bas-Rhin, Grand-Est (Alsace)",
  "importance": 0.1199,
  "housenumbers": {
    "1": {
      "lat": 48.610918,
      "lon": 7.705092,
      "id": "ADRNIVX_0000002000054981",
      "x": 1046652.6,
      "y": 6844855.6
    },
    "3": {
      "lat": 48.611046,
      "lon": 7.704729,
      "id": "ADRNIVX_0000002010011793",
      "x": 1046625.1,
      "y": 6844868.2
    },
    "5": {
      "lat": 48.61131,
      "lon": 7.703974,
      "id": "ADRNIVX_0000000330354943",
      "x": 1046567.8,
      "y": 6844894.2
    },
    "11": {
      "lat": 48.609884,
      "lon": 7.704075,
      "id": "ADRNIVX_0000000330354944",
      "x": 1046584.6,
      "y": 6844736.4
    }
  }
}
```
</details>

Si on en crois le document, Addok devrait nous retourner sans trop de problème les coordonnées pour les addresses `1 rue de lisbonne 67300 Schiltigheim France` et `3 rue de lisbonne 67300 Schiltigheim France`. Or ce n’est pas le cas.
Par exemple, pour `3 rue de lisbonne 67300 Schiltigheim France` nous récupérons `lat: 48.610968, lon: 7.730535` alors que le résultat attendu est `lat: 48.611046, lon: 7.704729`.

Nous utilisons cette configuration :
<details>
<summary>Show configuration</summary>

```
PROCESSORS_PYPATHS = [
"addok.helpers.text.tokenize",
"addok.helpers.text.normalize",
"addok_france.glue_ordinal",
"addok_france.fold_ordinal",
"addok_france.flag_housenumber",
"addok.helpers.text.synonymize",
"addok_fr.phonemicize",
]
QUERY_PROCESSORS_PYPATHS = [
'addok_france_clean.clean_query',
'addok.helpers.text.check_query_length',
'addok_france.extract_address',
'addok_france.clean_query',
'addok_france.remove_leading_zeros',
]
SEARCH_RESULT_PROCESSORS_PYPATHS = [
"addok.helpers.results.match_housenumber",
"addok_usage_name_BAN_FR.make_labels",
"addok.helpers.results.score_by_importance",
"addok.helpers.results.score_by_autocomplete_distance",
"addok.helpers.results.score_by_ngram_distance",
"addok.helpers.results.score_by_geo_distance",
]
```
</details>

Ce qui est étonnant c’est que pour les addresses `4 rue de lisbonne 67300 Schiltigheim France` et `9a rue de lisbonne 67300 Schiltigheim France` les coordonnées sont correcte alors qu’elle doivent être le résultat d’une interpolation puisque non présente dans le document.

A force de tests, nous nous somme rendu compte que le problème venait de `addok_france.flag_housenumber` puisque en enlevant cette ligne de la configuration, nous nous retrouvons avec les coordonnées voulu.

Ce que je ne comprend pas c'est que le numero de rue est bien `flag` en tant que `housenumber` aprés le passage de la fonction `flag_housenumber` mais etant donné que l'addresse existe bien dans le document, Addok ne devrait pas faire d'interpolation pour trouver la bonne coordonnée de l'addresse contrairement aux 2 autres addresses qui n'y sont pas présente.

Y a-t-il des problèmes connu avec cette fonction ?
Ou auriez vous peut être une piste à proposer pour que je puisse corriger ce problème ?

**Comment by cquest** [comment]
Votre json est erroné... housenumber doit être un tableau donc des [] et pas des {}

Pour info, addok ne fait pas d'interpolation. Si il ne trouve pas le numéro dans la rue, il retourne le lat/lon par défaut qui lui est associé.
Ici seul le numéro 1 est indexé pour la raison exposée au début.
