### ISSUE TITLE
auto-suggested should include more details

### ISSUE THREAD

**Issue by zorglubu** [addok/addok#646]
If I search for the village "saint sauveur", I get 10 indentical results in the autocompletion list. It could be good to have more details on, let's say, the two administrative levels above, when a "place" is found.
Otherwise, i tried to find by name, some schools, shops, streets : really great ! 
thanks

**Comment by cquest** [comment]
I suppose you tested demo.addok.xyz

The lack of administrative levels comes from the BANO data for the municipalities. This should be much better with the next data reload :)
