### ISSUE TITLE
Download link is not working anymore

### ISSUE THREAD

**Issue by mdamien** [addok/addok#647]
In the [tutorial](https://addok.readthedocs.io/en/latest/tutorial/), it says:

```
wget http://bano.openstreetmap.fr/BAN_odbl/BAN_odbl_93-json.bz2
```

But this links doesn't work anymore

EDIT: Found the correct link: bano.openstreetmap.fr/data/full.sjson.gz

**Comment by jdesboeufs** [comment]
http://bano.openstreetmap.fr/data/full.sjson.gz => BANO
https://adresse.data.gouv.fr/data/ban/adresses/latest/addok/adresses-addok-france.ndjson.gz => BAN

**Comment by vdct** [comment]
For a BANO sample & light-weight dataset you can wget http://bano.openstreetmap.fr/data/bano-93.json.gz

**Comment by jdesboeufs** [comment]
@vdct I opened a PR. Feel free to add BANO alternative :)
