### ISSUE TITLE
addok_csv: not clear how to install

### ISSUE THREAD

**Issue by mdamien** [addok/addok#648]
I modified `addok/config/__init__.py` with:

```python
        self.plugins = [
            'addok.shell',
            'addok.http.base',
            'addok.batch',
            'addok.pairs',
            'addok.fuzzy',
            'addok.autocomplete',
            'addok_csv',
        ]
```

To add `addok_csv`, but the `/search/csv/` endpoint doesn't work yet

EDIT: In fact, it does work, but the doc could still be more clear

**Comment by jdesboeufs** [comment]
You have nothing to do. Just install `addok-csv` with pip.
