### ISSUE TITLE
The geocoding of an address with an alias returns a result indicator that is too weak

### ISSUE THREAD

**Issue by alain-andre** [addok/addok#649]
Hi, we are using addok 1.1.0rc1 with a BAN from https://bano.openstreetmap.fr/BAN_odbl/BAN_odbl.json.bz2

Our problem is the following. Searching the address `82 rue du Général Leclerc 93220 GAGNY` we get a 0.56 street result with an address name that has changed into `82 Place du Général de Gaulle  93220 GAGNY`.

haddock shell:
```bash
> 82 rue du Général Leclerc 93220 GAGNY
82 Place du Général de Gaulle 93220 Gagny (zDB7m | 0.5621593096422364)

> GET zDB7m
y 6865399
x 666014.7
context 93, Seine-Saint-Denis, Île-de-France
postcode 93220
_id zDB7m
importance 0.2272
name ['Place du Général de Gaulle', 'rue du général leclerc']
lat 48.887707
lon 2.53654
citycode ['93032']
id 93032_XXXX_fbe948
type street
city Gagny
alias rue du général leclerc
housenumbers 2, 3, 5, 6, 7, 8, 12, 19, 21, 21 TER, 21 BIS, 22 BIS, 24, 26, 27, 28, 30, 30 BIS, 31, 32, 34, 35, 36, 38, 39, 40, 41, 42, 42 BIS, 43, 44, 45, 45 T, 45 B, 46, 47, 48, 49, 50, 52, 53, 54 TER, 54 BIS, 54, 55, 56, 57, 57 BIS, 57 TER, 58, 59 BIS, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 85, 85 BIS, 86, 87, 88, 89, 91, 93, 94, 95, 96, 97, 98, 99 BIS, 99, 100 BIS, 100, 101, 103, 105, 109, 111, 113, 115, 117
```

We can see there is an alias for our request but  what we do not understand is why the result is so degraded. Can someone explain us ?

**Comment by AdrienVH** [comment]
I think it comes from the fact that Addok uses the first "name" to calculate the score of the result.
Although each and every name is used to eventually match the record with the query, only the first name is used for the score calculation when the record becomes a result.

**Comment by alain-andre** [comment]
Ok, thank you @AdrienVH.
