### ISSUE TITLE
8 avenue leopold II

### ISSUE THREAD

**Issue by julien2512** [addok/addok#65]
Durant la saisie, pour "8 avenue leopold I", c'est paris qui est retourné, mais lorsque "8 avenue leopold II" est saisi, paris passe en deuxième position, au numéro d'adresse 2 !
Le problème ne se pose pas avec les autres numéros d'adresse (2 11 15 16 ...)

**Comment by yohanboniface** [comment]
L'explication est la suivante (en résumé):
Addok ne cherche que les rues (pas les numéros) PUIS regarde si la recherche matche un des éventuels numéros associés à cette rue; ce matching est fait via la version phonémisée de chaque token, et donc "2" et "II" ont le même phonème, en l'occurrence "deu".
Il y a ensuite un garde-fou, qui regarde si par ailleurs la version originale du numéro n'est pas aussi déjà dans le nom, auquel cas on ne fait pas le match (sauf si le token apparaît deux fois), ceci permettant de ne pas renvoyer le numéro "8" pour la recherche "rue du 8 mai" mais de le renvoyer pour "8 rue du 8 mai".
Ce garde-fou ne s'applique pour le cas que tu remontes, puisque c'est un nombre romain qui est dans le nom cette fois. Or, au moment de faire le matching, je n'ai en l'état plus l'information que "deu" était "II".
Bref, ça me demande un peu de chauffage de neurone pour corriger ça ;)

Et merci encore pour le signalement :)

**Comment by julien2512** [comment]
D'une manière générale, je te conseille aussi d'essayer d'évaluer le gain apporté par chaque correction ... J'imagine que les voies avec des nombres romains ne sont pas légions !

Vu que addok est très rapide (proche de la latence réseau !), as-tu pensé à valider toutes les adresses de France et identifier celles qui ne ressortent pas en premier résultat ? Il y a 18 000 000 adresses, et tu affiches environ 2500/s. Théoriquement, cela correspond à 2 heures de calcul ...

Cela te donneras l'ensemble des bugs, mais aussi le taux de correspondance. Moi, je dis que tu es à 99 % (soit 180 000 bugs maxi !) ?

**Comment by davidbgk** [comment]
See https://github.com/addok/addok/issues/214 for reference.

**Comment by davidbgk** [comment]
See https://github.com/addok/addok/issues/214 for reference.
