### ISSUE TITLE
Base Européenne ?

### ISSUE THREAD

**Issue by ImaCrea** [addok/addok#666]
Bonjour,

Je découvre cet outil, bravo ! Je travaille actuellement sur un besoin d'autocomplete d'adresses à l'échelle europénne. 

Nous aimerions éviter mapbox d'où ce ticket. Est-ce que addok est le bon outil pour résoudre ce problème ? Et si oui, où se procurer une base d'adresses européennes à importer dans addok ?

Merci pour votre aide, si vous jugez que ce n'est pas le bon endroit pour poser cette question n'hésitez pas à fermer directement ce ticket.

**Comment by frodrigo** [comment]
Attention Addok a des plugins pour la France et le Français. Il n'en a pas pour d'autres langues.
Je ne suis pas sûr que des langues peuvent être mélangé dans une même base.

**Comment by jdesboeufs** [comment]
En effet comme l'indique @frodrigo il faudra d'abord travailler sur un comportement générique, ou impliquer des contributeurs pour avoir davantage de langues.
Le moteur en l'état ne sait pas travailler en multilingue, ce qui pose aussi des problèmes en France pour les langues régionales.

Si des contributeurs ont des idées, vous êtes les bienvenus !
