### ISSUE TITLE
Python 3.8: StopIteration exception in addok-france plugin

### ISSUE THREAD

**Issue by gh4w** [addok/addok#679]
Hello,

According to [this post](https://stackoverflow.com/a/51701040) on SO, since python 3.7, generators do not swallow StopIteration exceptions anymore, you have to catch them explicitely.
When importing documents in addok with addok-france plugin (`addok batch`) the import fails, because of the following line:
https://github.com/addok/addok-france/blob/faee5600d88cabc5639f48d4446e7b141d5e7c1e/addok_france/utils.py#L78
Solution: surround the code with try...except, something like:
```python
    try:
        iterator = iter(iterable)
        previous = first
        current = next(iterator)  # Throws StopIteration if empty.
        for next_ in iterator:
            yield (previous, current, next_)
            previous = current
            current = next_
        yield (previous, current, last)
    except StopIteration:
        return
```
Has someone tried to run addok with a python version > 3.6 ? there is currently an issue with the ChunkdPool class and python 3.8 (#614). The documentation still mentions a python version >= 3.4. Is it still accurate ?

**Comment by jdesboeufs** [comment]
I confirm we also have the problem with Python 3.7.13.
We are stuck with Python 3.6.15 in production.

**Comment by yohanboniface** [comment]
Thanks for the report! Should be fixed with https://pypi.org/project/addok-france/1.1.1/

I'll one of you check and confirm with your own setup :)

**Comment by jdesboeufs** [comment]
I confirm it's fixed 🚑
But now we have this: https://github.com/addok/addok/issues/733 :D
