### ISSUE TITLE
Test de pertinence : quim ne renvoie pas QUIMPER

### ISSUE THREAD

**Issue by britlog** [addok/addok#692]
Bonjour,

Je suis en train de tester l'outil pour une recherche de ville uniquement (d'où le type=municipality) et je trouve étonnant qu'en appelant l'API avec "quim", elle ne renvoie pas la ville de QUIMPER :
https://api-adresse.data.gouv.fr/search?q=quim&type=municipality

`{"type": "FeatureCollection", "version": "draft", "features": [{"type": "Feature", "geometry": {"type": "Point", "coordinates": [-4.10869, 48.271223]}, "properties": {"label": "Pont-de-Buis-l\u00e8s-Quimerch", "score": 0.6689281818181817, "id": "29302", "type": "municipality", "name": "Pont-de-Buis-l\u00e8s-Quimerch", "postcode": "29590", "citycode": "29302", "x": 173262.54, "y": 6820491.37, "population": 3874, "city": "Pont-de-Buis-l\u00e8s-Quimerch", "context": "29, Finist\u00e8re, Bretagne", "importance": 0.35821}}], "attribution": "BAN", "licence": "ETALAB-2.0", "query": "quim", "filters": {"type": "municipality"}, "limit": 5}`

Est-ce un problème de paramétrage sur le serveur de démo ? Ou de paramètres dans mon appel API ?

Merci d'avance

**Comment by jdesboeufs** [comment]
Bonjour.
L'API de production est calibrée pour rechercher des adresses avant tout.
Pour une recherche de communes, nous conseillons l'API qui a été conçue pour cela, à savoir https://geo.api.gouv.fr.
cc @ThomasG77

**Comment by britlog** [comment]
Bonjour,
Merci de votre réponse, l'API de découpage administratif semble répondre à
mon besoin, est-il possible de l'auto-héberger ? Elle ne semble pas
intégrée dans le projet Addok.
Bien cordialement

Le sam. 12 févr. 2022, 15:11, Jérôme Desboeufs ***@***.***> a
écrit :

**Comment by jdesboeufs** [comment]
Le code est ici :
https://github.com/api-geo

**Comment by ThomasG77** [comment]
Utilisez la branche https://github.com/etalab/api-geo/tree/maj-2021 pour avoir la version de l'API également déployée en production

**Comment by jdesboeufs** [comment]
Pourquoi ne pas merger cette branche ?

**Comment by britlog** [comment]
Merci à tous les 2 !
