### ISSUE TITLE
Extraire l'ensemble des noms de villes (oldcity et city) de la BNA

### ISSUE THREAD

**Issue by GabrielGodefroy** [addok/addok#699]
Bonjour à tous,

Tout d'abord, félicitation pour cet outils très pratique et bien documenté.

Je suis actuellement en train de migrer un service utilisant FANTOIR vers la BNA.
Je souhaite extraire l'ensemble des villes (city et oldcity) connues de la BNA pour comparer avec la version de Fantoir que j'utilise.

Si besoin je peux faire un scrapper pour les extraires à partir des fichiers disponibles ici : https://adresse.data.gouv.fr/data/ban/adresses/latest/csv/

mais je préférerai le faire directement via la version d'Addok que j'utilise.

Cela est-il possible ? 

Merci par avance,
G.

**Comment by jdesboeufs** [comment]
Bonjour,

Les communes de la BAN sont les communes du Code Officiel Géographique de l'INSEE.
Cf https://github.com/etalab/decoupage-administratif
