### ISSUE TITLE
"type" filter not properly applied

### ISSUE THREAD

**Issue by nrobink** [addok/addok#714]
Hi,

Searching https://api-adresse.data.gouv.fr/search/?q=13+IMP+DE+LA+PETITE+MARQUISE&postcode=26000 returns : 

- 1 street result
- 1 address result

When applying the type=housenumber (https://api-adresse.data.gouv.fr/search/?q=13+IMP+DE+LA+PETITE+MARQUISE&postcode=26000&type=housenumber), Addok still returns the same 2 results without excluding the street-type result.

Tested on api-adresse.data.gouv.fr and on a local instance of addok, not tested with other addresses.

Any idea on why is this behavior happening ? Thanks !

**Comment by jdesboeufs** [comment]
Fixed since 1.1.0
