### ISSUE TITLE
python >= 3.8 compat ?

### ISSUE THREAD

**Issue by mtmail** [addok/addok#720]
[ce388b](https://github.com/addok/addok/commit/ce388ba4887774807aeb2a367202848dbc255664) added an entry `Added python >= 3.8 compat` to the `CHANGELOG.md` file.

I can't find a related code change. `tutorial.md`, `setup.py`, `travis.yml` mention 3.6 but no file mentions 3.7, 3.8 or 3.9.

Python 3.6 reached end-of-life status https://devguide.python.org/versions/

**Comment by yohanboniface** [comment]
Version 1.0.3 has been pushed on pypi, which should make addok ready for modern python version!

**Comment by yohanboniface** [comment]
(Master is already compatible, but not yet released.)
