### ISSUE TITLE
Ajoût d'un healthcheck pour le fonctionnement dans un environnement kubernetes

### ISSUE THREAD

**Issue by blegros-exte** [addok/addok#749]
Ceci est plus une feature request qu'une issue.

Nous déployons le service Addok de manière conteneurisée dans un kubernetes. Pour le moment le service tourne sans healthcheck (livenessProbe) mais nous souhaitons en ajouter un par mesure de sécurité.

Nous pouvons passer par un call au endpoint `/search` mais il génère du bruit dans le monitoring car facilement confondable avec un call classique.

Il serait sympa d'avoir un `/health` qui vienne lancer une commande ping côté redis pour vérifier que la connexion est présente.

Je peux éventuellement regarder comment faire ça dans une PR, mais à vos risques et périls car je ne suis pas développeur Python à l'origine !

Merci à vous

**Comment by yohanboniface** [comment]
> Je peux éventuellement regarder comment faire ça dans une PR, mais à vos risques et périls car je ne suis pas développeur Python à l'origine !

C'est le moment de se lancer :)

Ça passe par là: https://github.com/addok/addok/blob/master/addok/http/base.py#L194-L196

Une bête classe avec un `on_get` devrait faire l'affaire. Cf https://falcon.readthedocs.io/en/stable/ pour la doc de Falcon.

@cquest je sais pas pourquoi mais il me semblait que tu avais fait un truc pour avoir les infos de base de Redis. J'ai rêvé ?

**Comment by cquest** [comment]
Rien fait de mon côté pour Redis ou autre.
