### ISSUE TITLE
Create a CI for test automation

### ISSUE THREAD

**Issue by blegros-exte** [addok/addok#751]
Old existing CI still runs on python 3.6.
It is not relevant anymore (it doesn't even work BTW).

**Comment by blegros-exte** [comment]
@yohanboniface concernant ton [commentaire](https://github.com/addok/addok/pull/750#issuecomment-1344055261), plusieurs options s'offrent à nous puisque Black formate le code, il ne le check pas:

1. Je run Black dans le cadre d'un commit dans master (ce qui va créer un nouveau commit) peut importe ce qui a été commité à l'origine.
2. Je run plutôt flake8 qui va checker que les changements sont aux normes et je fail la pipeline s'ils ne le sont pas et ce notamment pour les Pull Request. On peut également ajouter un CONTRIBUTING.md qui explique les tâches nécessaires à une contribution à ce projet (avec des étapes comme celles explicitées dans cet [exemple](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/)).

Je te laisse me dire ce qui est préférable (hint: j'ai une préférence pour l'option 2 ;-) )

**Comment by yohanboniface** [comment]
`black --check --diff addok` devrait faire le taf (status de retour > 0 si au moins un fichier demande un reformatage) :)

Mais si on est joueurs, on peut lancer black ET flake8, qui ne font pas exactement la même chose. :)

**Comment by blegros-exte** [comment]
@yohanboniface j'ai commencé à faire une [pipeline](https://github.com/blegros-exte/addok/actions) mais j'ai quand même beaucoup d'erreurs dans les tests, j'ai essayé d'en corriger 2-3 mais là ça commence à me prendre beaucoup de temps (notamment parce que je ne connais pas grand chose en python). 
J'ai l'impression que toute cette partie n'est notamment plus très à jour avec les montées de version de python 😬

**Comment by jdesboeufs** [comment]
Un workflow GitHub Actions est en place depuis aujourd'hui.
