### ISSUE TITLE
Problème d'emballement de redis

### ISSUE THREAD

**Issue by azmeuk** [addok/addok#780]
J'utilise addok 1.0.4 sur une Debian 11 avec redis 6.0.16. J'ai des problèmes de consommation de ressources avec redis, et comme le seul service qui utilise redis est addok je viens en discuter ici.

J'observe ponctuellement depuis quelques mois, un emballement aléatoire de redis, qui se met subittement à consommer 100% du CPU et de la RAM. L'emballement arrive à n'importe quelle heure, ne semble pas correllé avec une hausse particulière du traffic ou bien le lancement de tâches récurrentes : ça arrive aléatoirement.

Les *THP* l'*overcommit* sont configurés correctement [comme conseillé dans la doc de redis](https://redis.io/docs/management/admin/).

Les symptômes que je rencontre sont décrit assez similairement dans [cet article de blog](https://www.linkedin.com/pulse/redis-cpu-spikes-how-avoid-ibrahim-chawa-1f/), où l'auteur trouve comme cause l'utilisation de commandes redis lentes telles que `KEYS`.

Je suis assez peu sachant sur redis mais je voulais partager ce problème ici.
- Avez-vous déjà rencontré des problèmes similaires ?
- addok peut-il être à l'origine d'utilisation de commandes redis gourmandes, de manière directe ou indirecte ?

**Comment by jdesboeufs** [comment]
Bonjour,

Hormis lors de l'import batch, addok ne provoque pas d'appels intensifs à Redis, sauf évidemment en pic de charge.
Il faut au moins 8 workers addok chargés à 100% pour saturer Redis.

Dans votre cas il est possible que votre instance Redis soit configurée pour effectuer une sauvegarde sur disque régulièrement.
Pour addok il n'est pas utile de conserver la persistence une fois l'import initial réalisé.

```bash
redis-server --save ""
```

**Comment by azmeuk** [comment]
Après vérification nous avons pu innocenter redis. Pour l'annecdote, c'était un domage collatéral d'oom-reaper du fait que redis est assez gourmand en fonctionnement nominal.
Merci pour la réponse !
