### ISSUE TITLE
#553 issue not resolved yet

### ISSUE THREAD

**Issue by SUGAM-ARORA** [addok/addok#785]
#553 issue not resolved till now . Same recurring issue
no step actually worked

**Comment by yohanboniface** [comment]
Please explain what you have tried, what errors you have, which OS you run, etc.

**Comment by SUGAM-ARORA** [comment]
I tried on ubuntu and tried the following procedure 
1- pip install --upgrade virtualenv
2- virtualenv -p python3 venv
This one gave the same error

**Comment by SUGAM-ARORA** [comment]
i firstly updated my 45 packages using following commands  :
sudo apt update 
apt list --upgradable
again sudo apt upgrade
Then I installed virtualenv with the following command : 
pip install virtualenv
python3 -m venv venv
.venv/bin/activate

Lastly I installed flask again using below command : 
pip install flask-cli

After all these error got removed .  But a new error occured

**Comment by SUGAM-ARORA** [comment]
Error :   


ImportError: cannot import name 'ParserError' from 'dateutil.parser' (/usr/lib/python3/dist-packages/dateutil/parser/__init__.py)

**Comment by yohanboniface** [comment]
> Lastly I installed flask again using below command :

How is flask related to this project ? Can you explain what you are trying to achieve ?

**Comment by SUGAM-ARORA** [comment]
sudo apt-get install python-pip


$ sudo pip install python-dateutil
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (2.7.3)
$ pip uninstall python-dateuti;
WARNING: Skipping python-dateuti as it is not installed.
Found existing installation: python-dateutil 2.8.2
Uninstalling python-dateutil-2.8.2:
 
Proceed (Y/n)? Y
  Successfully uninstalled python-dateutil-2.8.2
$ sudo pip install python-dateutil
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (2.7.3)
$ sudo pip uninstall python-dateutil
Found existing installation: python-dateutil 2.7.3
Not uninstalling python-dateutil at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'python-dateutil'. No files were found to uninstall.
$ sudo pip install python-dateutil
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (2.7.3)
$ sudo apt-get install python-pip

**Comment by SUGAM-ARORA** [comment]
> > Lastly I installed flask again using below command :
> 
> How is flask related to this project ? Can you explain what you are trying to achieve ?

Actually I am trying to setup superset in Ubuntu

**Comment by SUGAM-ARORA** [comment]
So in order to setup this some errors are coming in documentation of superset

**Comment by SUGAM-ARORA** [comment]
I have explained all the steps which I used to remove the error

**Comment by yohanboniface** [comment]
@SUGAM-ARORA it seems you are in the wrong place, here: addok does not relate in anyway to superset.

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA it seems you are in the wrong place, here: addok does not relate in anyway to superset.

Yes I know but the issue is the same there also . So I just tried to help get away with the error
