### ISSUE TITLE
différences de score entre le endpoint /csv et le endpoint search/ 

### ISSUE THREAD

**Issue by RidaELABED** [addok/addok#808]
Hello,
J'ai remarqué que l'on obtient pas le même score en fonction de si on passe par https://adresse.data.gouv.fr/csv ou https://api-adresse.data.gouv.fr/search/?q= 

Exemple avec cette adresse : " 80 Boulevard de Rochechouart, 75018 Paris " 

endpoint /csv 
![image](https://github.com/addok/addok/assets/84328062/2791308f-0bcb-4340-97bc-be001451de92)
**score :** 0.7784854545454545

endpoint /search
<img width="1393" alt="image" src="https://github.com/addok/addok/assets/84328062/84c5bad8-5fc9-4bc0-b627-90c3f6da2962">
**score :** 0.7075763636363637

Qu'est ce qui peut expliquer cette différence?

**Comment by jdesboeufs** [comment]
L'option autocomplete=0 pour le CSV, autocomplete=1 par défaut pour le search.
Si vous forcez autocomplete=0 pour le search vous aurez le même score.

**Comment by RidaELABED** [comment]
Merci pour la précision, cela fait sens à présent.
