### ISSUE TITLE
reverse / type=housenumber : mauvais id retourné

### ISSUE THREAD

**Issue by parville** [addok/addok#96]
Bonsoir,

l'identifiant retourné pour un reverse de type housenumber n'est pas correct : on récupére l'id de voie et non pas celui du point de voie !

Cordialement,

HP

**Comment by yohanboniface** [comment]
Tu peux me donner un exemple? En [testant](http://api.adresse.data.gouv.fr/search/?q=30%20bis%20rue%20brisout%20de%20barneville%2076100%20Rouen&limit=1&type=housenumber) rapidement je constate pas le souci, donc ça doit être une collusion avec autre chose.

**Comment by yohanboniface** [comment]
@parville t'aurais un chtit exemple pour que je puisse reproduire? :)

**Comment by descl** [comment]
Bonjour,
je me permets de répondre car j'ai la même question.
Pour Nice quand je demande que les housenumber il me r'envoit aussi des type:street 
http://api-adresse.data.gouv.fr/search/?q=nice&limit=5&type=housenumber

merci, Christophe

**Comment by yohanboniface** [comment]
Humm, alors, je sais pas si c'est le souci initial de ce ticket, mais dans ton cas y a bien un bug, mais le corriger ne va pas t'arranger: addok remonte un housenumber si et seulement si la chaîne donnée matche ses champs spécifiques (en l'occurrence le numéro), donc "nice" ne peux pas matcher de housenumber (alors que, par exemple, "22 nice" sûrement).
Je crois comprendre ce que tu veux faire (récupérer les housenumbers de Nice), mais addok saura pas faire ça. Il faut attendre l'API CRUD de la BAN pour ce genre d'appels. Dans le courant de l'année is Allah, les astres et les hautes instances de l'adresse sont bien alignées.


Pour la postérité quelques détails sur le bug:

`street` et `housenumber` sont un seul et même objet dans l'index, et il manque un truc pour dire "si aucun housenumber ne matche et que le type demandé est un "housenumber" ne remonte pas l'objet". Je vais regarder ça, mais c'est pas simple.

**Comment by cquest** [comment]
J'ai ajouté il filtre final pour type=housenumber sur le résultat retourné ça avec le commit 0bca1c3c3f4aa891e648bfbfc3830574e74b3bb9
